// Package gtk was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gtk

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type PasswordEntryBufferClass struct {
	_ structs.HostLayout

	ParentClass EntryBufferClass
}

func (x *PasswordEntryBufferClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// A `GtkEntryBuffer` that locks the underlying memory to prevent it
// from being swapped to disk.
//
// `GtkPasswordEntry` uses a `GtkPasswordEntryBuffer`.
type PasswordEntryBuffer struct {
	EntryBuffer
}

var xPasswordEntryBufferGLibType func() types.GType

func PasswordEntryBufferGLibType() types.GType {
	return xPasswordEntryBufferGLibType()
}

func PasswordEntryBufferNewFromInternalPtr(ptr uintptr) *PasswordEntryBuffer {
	cls := &PasswordEntryBuffer{}
	cls.Ptr = ptr
	return cls
}

var xNewPasswordEntryBuffer func() uintptr

// Creates a new `GtkEntryBuffer` using secure memory allocations.
func NewPasswordEntryBuffer() *PasswordEntryBuffer {
	var cls *PasswordEntryBuffer

	cret := xNewPasswordEntryBuffer()

	if cret == 0 {
		return nil
	}
	cls = &PasswordEntryBuffer{}
	cls.Ptr = cret
	return cls
}

func (c *PasswordEntryBuffer) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *PasswordEntryBuffer) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("GTK", "gtk4")
	core.SetSharedLibraries("GTK", []string{"libgtk-4.so.1"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("GTK") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xPasswordEntryBufferGLibType, libs, "gtk_password_entry_buffer_get_type")

	core.PuregoSafeRegister(&xNewPasswordEntryBuffer, libs, "gtk_password_entry_buffer_new")

}
