// Package ecal was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package ecal

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
	"github.com/jwijenbergh/puregotk/v4/icalglib"
)

// Period of time, can have explicit start/end times or start/duration instead.
// Use the functions below to work with it.
type ComponentPeriod struct {
	_ structs.HostLayout
}

var xComponentPeriodGLibType func() types.GType

func ComponentPeriodGLibType() types.GType {
	return xComponentPeriodGLibType()
}

func (x *ComponentPeriod) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xNewComponentPeriodDatetime func(*icalglib.Time, *icalglib.Time) *ComponentPeriod

// Creates a new #ECalComponentPeriod of kind %E_CAL_COMPONENT_PERIOD_DATETIME.
// The returned structure should be freed with e_cal_component_period_free(),
// when no longer needed.
func NewComponentPeriodDatetime(StartVar *icalglib.Time, EndVar *icalglib.Time) *ComponentPeriod {

	cret := xNewComponentPeriodDatetime(StartVar, EndVar)
	return cret
}

var xNewComponentPeriodDuration func(*icalglib.Time, *icalglib.Duration) *ComponentPeriod

// Creates a new #ECalComponentPeriod of kind %E_CAL_COMPONENT_PERIOD_DURATION.
// The returned structure should be freed with e_cal_component_period_free(),
// when no longer needed.
func NewComponentPeriodDuration(StartVar *icalglib.Time, DurationVar *icalglib.Duration) *ComponentPeriod {

	cret := xNewComponentPeriodDuration(StartVar, DurationVar)
	return cret
}

var xComponentPeriodCopy func(uintptr) *ComponentPeriod

func (x *ComponentPeriod) Copy() *ComponentPeriod {

	cret := xComponentPeriodCopy(x.GoPointer())
	return cret
}

var xComponentPeriodFree func(uintptr)

// Free the @period, previously allocated by e_cal_component_period_new_datetime(),
// e_cal_component_period_new_duration() or e_cal_component_period_copy().
func (x *ComponentPeriod) Free() {

	xComponentPeriodFree(x.GoPointer())

}

var xComponentPeriodGetDuration func(uintptr) *icalglib.Duration

// Returns the duration of the @period. This can be called only on @period
// objects of kind %E_CAL_COMPONENT_PERIOD_DURATION.
// The returned #ICalDuration object is owned by @period and should not
// be freed. It's valid until the @period is freed or its duration changed.
func (x *ComponentPeriod) GetDuration() *icalglib.Duration {

	cret := xComponentPeriodGetDuration(x.GoPointer())
	return cret
}

var xComponentPeriodGetEnd func(uintptr) *icalglib.Time

// Returns the end of the @period. This can be called only on @period
// objects of kind %E_CAL_COMPONENT_PERIOD_DATETIME. The end time can
// be a null-time, in which case the @period corresponds to a single
// date/date-time value, not to a period.
//
// The returned #ICalTime object is owned by @period and should not
// be freed. It's valid until the @period is freed or its end time changed.
func (x *ComponentPeriod) GetEnd() *icalglib.Time {

	cret := xComponentPeriodGetEnd(x.GoPointer())
	return cret
}

var xComponentPeriodGetKind func(uintptr) ComponentPeriodKind

// Returns kind of the @period, one of #ECalComponentPeriodKind. Depending
// on it either e_cal_component_period_get_end()/e_cal_component_period_set_end()
// or e_cal_component_period_get_duration()/e_cal_component_period_set_duration()
// can be used. The kind of an existing @period canbe changed with
// e_cal_component_period_set_datetime_full() and e_cal_component_period_set_duration_full().
func (x *ComponentPeriod) GetKind() ComponentPeriodKind {

	cret := xComponentPeriodGetKind(x.GoPointer())
	return cret
}

var xComponentPeriodGetStart func(uintptr) *icalglib.Time

// Returns the start of the @period. The returned #ICalTime object
// is owned by @period and should not be freed. It's valid until the @period
// is freed or its start time changed.
func (x *ComponentPeriod) GetStart() *icalglib.Time {

	cret := xComponentPeriodGetStart(x.GoPointer())
	return cret
}

var xComponentPeriodSetDatetimeFull func(uintptr, *icalglib.Time, *icalglib.Time)

// Set the kind of @period to be %E_CAL_COMPONENT_PERIOD_DATETIME
// and fills the content with @start and @end.
func (x *ComponentPeriod) SetDatetimeFull(StartVar *icalglib.Time, EndVar *icalglib.Time) {

	xComponentPeriodSetDatetimeFull(x.GoPointer(), StartVar, EndVar)

}

var xComponentPeriodSetDuration func(uintptr, *icalglib.Duration)

// Set the duration of the @period. This can be called only on @period
// objects of kind %E_CAL_COMPONENT_PERIOD_DURATION.
func (x *ComponentPeriod) SetDuration(DurationVar *icalglib.Duration) {

	xComponentPeriodSetDuration(x.GoPointer(), DurationVar)

}

var xComponentPeriodSetDurationFull func(uintptr, *icalglib.Time, *icalglib.Duration)

// Set the kind of @period to be %E_CAL_COMPONENT_PERIOD_DURATION
// and fills the content with @start and @duration.
func (x *ComponentPeriod) SetDurationFull(StartVar *icalglib.Time, DurationVar *icalglib.Duration) {

	xComponentPeriodSetDurationFull(x.GoPointer(), StartVar, DurationVar)

}

var xComponentPeriodSetEnd func(uintptr, *icalglib.Time)

// Set the end of the @period. This can be called only on @period
// objects of kind %E_CAL_COMPONENT_PERIOD_DATETIME.
func (x *ComponentPeriod) SetEnd(EndVar *icalglib.Time) {

	xComponentPeriodSetEnd(x.GoPointer(), EndVar)

}

var xComponentPeriodSetStart func(uintptr, *icalglib.Time)

// Set the @start of the @period. This can be called on any kind of the @period.
func (x *ComponentPeriod) SetStart(StartVar *icalglib.Time) {

	xComponentPeriodSetStart(x.GoPointer(), StartVar)

}

func init() {
	core.SetPackageName("ECAL", "libecal-2.0")
	core.SetSharedLibraries("ECAL", []string{"libecal-2.0.so.3"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("ECAL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xComponentPeriodGLibType, libs, "e_cal_component_period_get_type")

	core.PuregoSafeRegister(&xNewComponentPeriodDatetime, libs, "e_cal_component_period_new_datetime")
	core.PuregoSafeRegister(&xNewComponentPeriodDuration, libs, "e_cal_component_period_new_duration")

	core.PuregoSafeRegister(&xComponentPeriodCopy, libs, "e_cal_component_period_copy")
	core.PuregoSafeRegister(&xComponentPeriodFree, libs, "e_cal_component_period_free")
	core.PuregoSafeRegister(&xComponentPeriodGetDuration, libs, "e_cal_component_period_get_duration")
	core.PuregoSafeRegister(&xComponentPeriodGetEnd, libs, "e_cal_component_period_get_end")
	core.PuregoSafeRegister(&xComponentPeriodGetKind, libs, "e_cal_component_period_get_kind")
	core.PuregoSafeRegister(&xComponentPeriodGetStart, libs, "e_cal_component_period_get_start")
	core.PuregoSafeRegister(&xComponentPeriodSetDatetimeFull, libs, "e_cal_component_period_set_datetime_full")
	core.PuregoSafeRegister(&xComponentPeriodSetDuration, libs, "e_cal_component_period_set_duration")
	core.PuregoSafeRegister(&xComponentPeriodSetDurationFull, libs, "e_cal_component_period_set_duration_full")
	core.PuregoSafeRegister(&xComponentPeriodSetEnd, libs, "e_cal_component_period_set_end")
	core.PuregoSafeRegister(&xComponentPeriodSetStart, libs, "e_cal_component_period_set_start")

}
