// Package ecal was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package ecal

import "github.com/jwijenbergh/puregotk/v4/gobject/types"

type ComponentAlarmTriggerKind int

var xComponentAlarmTriggerKindGLibType func() types.GType

func ComponentAlarmTriggerKindGLibType() types.GType {
	return xComponentAlarmTriggerKindGLibType()
}

const (
	ECalComponentAlarmTriggerNoneValue ComponentAlarmTriggerKind = 0

	ECalComponentAlarmTriggerRelativeStartValue ComponentAlarmTriggerKind = 1

	ECalComponentAlarmTriggerRelativeEndValue ComponentAlarmTriggerKind = 2

	ECalComponentAlarmTriggerAbsoluteValue ComponentAlarmTriggerKind = 3
)
