// Package edataserver was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package edataserver

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
)

type FreeFormExpBuildSexpFunc func(string, string, string) string

type FreeFormExpSymbol struct {
	_ structs.HostLayout

	Names uintptr

	Hint uintptr

	BuildSexp FreeFormExpBuildSexpFunc
}

func (x *FreeFormExpSymbol) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xFreeFormExpToSexp func(string, *FreeFormExpSymbol) string

// Converts the @free_form_exp to an S-Expression using the S-Expression
// builders defined in the @symbols. The @symbols should have one symbol
// with an empty string as its name, which is used for words which do not
// have a symbol name prefix.
//
// The @symbols is a NULL-terminated array of known symbols. The NULL should
// be set for the symbol's name.
func FreeFormExpToSexp(FreeFormExpVar string, SymbolsVar *FreeFormExpSymbol) string {

	cret := xFreeFormExpToSexp(FreeFormExpVar, SymbolsVar)
	return cret
}

func init() {
	core.SetPackageName("EDATASERVER", "libedataserver-1.2")
	core.SetSharedLibraries("EDATASERVER", []string{"libcamel-1.2.so.66", "libedataserver-1.2.so.27"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("EDATASERVER") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xFreeFormExpToSexp, libs, "e_free_form_exp_to_sexp")

}
