// Package edataserver was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package edataserver

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gio"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

// Callback used to traverse response from the server, which is
// an array.
type GDataObjectCallback func(uintptr, uintptr, uintptr) bool

type GDataSessionClassGType struct {
	_ structs.HostLayout

	ParentClass SoupSessionClassGType

	Reserved [10]uintptr
}

func (x *GDataSessionClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type GDataSessionPrivate struct {
	_ structs.HostLayout
}

func (x *GDataSessionPrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// Holds status of a task.
type GDataTaskStatus int

const (

	// unknown status
	EGdataTaskStatusUnknownValue GDataTaskStatus = 0
	// the task needs action
	EGdataTaskStatusNeedsActionValue GDataTaskStatus = 1
	// the task is completed
	EGdataTaskStatusCompletedValue GDataTaskStatus = 2
)

var xGdataTaskAddCompleted func(uintptr, int64)

// Adds a Task:completed property @value into the @builder, which
// should have started an object member.
//
// When the @value is 0, then adds a NULL-object, to indicate
// removal of the property.
func GdataTaskAddCompleted(BuilderVar uintptr, ValueVar int64) {

	xGdataTaskAddCompleted(BuilderVar, ValueVar)

}

var xGdataTaskAddDue func(uintptr, int64)

// Adds a Task::due property @value into the @builder, which
// should have started an object member.
//
// When the @value is 0, then adds a NULL-object, to indicate
// removal of the property.
func GdataTaskAddDue(BuilderVar uintptr, ValueVar int64) {

	xGdataTaskAddDue(BuilderVar, ValueVar)

}

var xGdataTaskAddId func(uintptr, string)

// Adds a Task::id property @value into the @builder, which
// should have started an object member.
func GdataTaskAddId(BuilderVar uintptr, ValueVar string) {

	xGdataTaskAddId(BuilderVar, ValueVar)

}

var xGdataTaskAddNotes func(uintptr, string)

// Adds a Task::notes property @value into the @builder, which
// should have started an object member.
//
// When the @value is %NULL, then adds a NULL-object, to indicate removal
// of the property.
func GdataTaskAddNotes(BuilderVar uintptr, ValueVar string) {

	xGdataTaskAddNotes(BuilderVar, ValueVar)

}

var xGdataTaskAddStatus func(uintptr, GDataTaskStatus)

// Adds a Task::status property @value into the @builder, which
// should have started an object member.
//
// When the @value is %E_GDATA_TASK_STATUS_UNKNOWN, then adds a NULL-object,
// to indicate removal of the property.
func GdataTaskAddStatus(BuilderVar uintptr, ValueVar GDataTaskStatus) {

	xGdataTaskAddStatus(BuilderVar, ValueVar)

}

var xGdataTaskAddTitle func(uintptr, string)

// Adds a Task::title property @value into the @builder, which
// should have started an object member.
func GdataTaskAddTitle(BuilderVar uintptr, ValueVar string) {

	xGdataTaskAddTitle(BuilderVar, ValueVar)

}

var xGdataTaskGetCompleted func(uintptr) int64

// Returns Task::completed property, as Unix time.
func GdataTaskGetCompleted(TaskVar uintptr) int64 {

	cret := xGdataTaskGetCompleted(TaskVar)
	return cret
}

var xGdataTaskGetDeleted func(uintptr) bool

// Returns Task::deleted property, as Unix time.
func GdataTaskGetDeleted(TaskVar uintptr) bool {

	cret := xGdataTaskGetDeleted(TaskVar)
	return cret
}

var xGdataTaskGetDue func(uintptr) int64

// Returns Task::due property, as Unix time.
func GdataTaskGetDue(TaskVar uintptr) int64 {

	cret := xGdataTaskGetDue(TaskVar)
	return cret
}

var xGdataTaskGetEtag func(uintptr) string

// Returns Task::etag property.
func GdataTaskGetEtag(TaskVar uintptr) string {

	cret := xGdataTaskGetEtag(TaskVar)
	return cret
}

var xGdataTaskGetHidden func(uintptr) bool

// Returns Task::hidden property, as Unix time.
func GdataTaskGetHidden(TaskVar uintptr) bool {

	cret := xGdataTaskGetHidden(TaskVar)
	return cret
}

var xGdataTaskGetId func(uintptr) string

// Returns Task::id property.
func GdataTaskGetId(TaskVar uintptr) string {

	cret := xGdataTaskGetId(TaskVar)
	return cret
}

var xGdataTaskGetNotes func(uintptr) string

// Returns Task::notes property.
func GdataTaskGetNotes(TaskVar uintptr) string {

	cret := xGdataTaskGetNotes(TaskVar)
	return cret
}

var xGdataTaskGetParent func(uintptr) string

// Returns Task::parent property.
func GdataTaskGetParent(TaskVar uintptr) string {

	cret := xGdataTaskGetParent(TaskVar)
	return cret
}

var xGdataTaskGetPosition func(uintptr) string

// Returns Task::position property.
func GdataTaskGetPosition(TaskVar uintptr) string {

	cret := xGdataTaskGetPosition(TaskVar)
	return cret
}

var xGdataTaskGetSelfLink func(uintptr) string

// Returns Task::selfLink property.
func GdataTaskGetSelfLink(TaskVar uintptr) string {

	cret := xGdataTaskGetSelfLink(TaskVar)
	return cret
}

var xGdataTaskGetStatus func(uintptr) GDataTaskStatus

// Returns Task::status property.
func GdataTaskGetStatus(TaskVar uintptr) GDataTaskStatus {

	cret := xGdataTaskGetStatus(TaskVar)
	return cret
}

var xGdataTaskGetTitle func(uintptr) string

// Returns Task::title property.
func GdataTaskGetTitle(TaskVar uintptr) string {

	cret := xGdataTaskGetTitle(TaskVar)
	return cret
}

var xGdataTaskGetUpdated func(uintptr) int64

// Returns Task::updated property, as Unix time.
func GdataTaskGetUpdated(TaskVar uintptr) int64 {

	cret := xGdataTaskGetUpdated(TaskVar)
	return cret
}

var xGdataTasklistAddId func(uintptr, string)

// Adds a TaskList::id property @value into the @builder, which
// should have started an object member.
func GdataTasklistAddId(BuilderVar uintptr, ValueVar string) {

	xGdataTasklistAddId(BuilderVar, ValueVar)

}

var xGdataTasklistAddTitle func(uintptr, string)

// Adds a TaskList::title property @value into the @builder, which
// should have started an object member.
func GdataTasklistAddTitle(BuilderVar uintptr, ValueVar string) {

	xGdataTasklistAddTitle(BuilderVar, ValueVar)

}

var xGdataTasklistGetEtag func(uintptr) string

// Returns TaskList::etag property.
func GdataTasklistGetEtag(TasklistVar uintptr) string {

	cret := xGdataTasklistGetEtag(TasklistVar)
	return cret
}

var xGdataTasklistGetId func(uintptr) string

// Returns TaskList::id property.
func GdataTasklistGetId(TasklistVar uintptr) string {

	cret := xGdataTasklistGetId(TasklistVar)
	return cret
}

var xGdataTasklistGetSelfLink func(uintptr) string

// Returns TaskList::selfLink property.
func GdataTasklistGetSelfLink(TasklistVar uintptr) string {

	cret := xGdataTasklistGetSelfLink(TasklistVar)
	return cret
}

var xGdataTasklistGetTitle func(uintptr) string

// Returns TaskList::title property.
func GdataTasklistGetTitle(TasklistVar uintptr) string {

	cret := xGdataTasklistGetTitle(TasklistVar)
	return cret
}

var xGdataTasklistGetUpdated func(uintptr) int64

// Returns TaskList::updated property, as Unix time.
func GdataTasklistGetUpdated(TasklistVar uintptr) int64 {

	cret := xGdataTasklistGetUpdated(TasklistVar)
	return cret
}

// Contains only private data that should be read and manipulated using the
// functions below.
type GDataSession struct {
	SoupSession
}

var xGDataSessionGLibType func() types.GType

func GDataSessionGLibType() types.GType {
	return xGDataSessionGLibType()
}

func GDataSessionNewFromInternalPtr(ptr uintptr) *GDataSession {
	cls := &GDataSession{}
	cls.Ptr = ptr
	return cls
}

var xNewGDataSession func(uintptr) uintptr

// Creates a new #EGDataSession associated with the given @source.
func NewGDataSession(SourceVar *Source) *GDataSession {
	var cls *GDataSession

	cret := xNewGDataSession(SourceVar.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &GDataSession{}
	cls.Ptr = cret
	return cls
}

var xGDataSessionTasklistsDeleteSync func(uintptr, string, uintptr, **glib.Error) bool

// Deletes a task list @tasklist_id.
func (x *GDataSession) TasklistsDeleteSync(TasklistIdVar string, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xGDataSessionTasklistsDeleteSync(x.GoPointer(), TasklistIdVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xGDataSessionTasklistsGetSync func(uintptr, string, *uintptr, uintptr, **glib.Error) bool

// Gets a task list @tasklist_id and returns it as a #JsonObject,
// which should be freed with json_object_unref(), when no longer needed.
//
// There can be used e_gdata_tasklist_get_id(), e_gdata_tasklist_get_etag(),
// e_gdata_tasklist_get_title(), e_gdata_tasklist_get_self_link(),
// e_gdata_tasklist_get_updated() to read the properties of the task list.
func (x *GDataSession) TasklistsGetSync(TasklistIdVar string, OutTasklistVar *uintptr, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xGDataSessionTasklistsGetSync(x.GoPointer(), TasklistIdVar, OutTasklistVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xGDataSessionTasklistsInsertSync func(uintptr, string, *uintptr, uintptr, **glib.Error) bool

// Creates a new task list, titled @title. The @out_inserted_tasklist should
// be freed with json_object_unref(), when no longer needed.
func (x *GDataSession) TasklistsInsertSync(TitleVar string, OutInsertedTasklistVar *uintptr, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xGDataSessionTasklistsInsertSync(x.GoPointer(), TitleVar, OutInsertedTasklistVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xGDataSessionTasklistsListSync func(uintptr, *GDataQuery, uintptr, uintptr, uintptr, **glib.Error) bool

// Lists all configured task lists for the user, calling the @cb for each of them.
func (x *GDataSession) TasklistsListSync(QueryVar *GDataQuery, CbVar *GDataObjectCallback, UserDataVar uintptr, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xGDataSessionTasklistsListSync(x.GoPointer(), QueryVar, glib.NewCallback(CbVar), UserDataVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xGDataSessionTasklistsPatchSync func(uintptr, string, uintptr, *uintptr, uintptr, **glib.Error) bool

// Changes properties of a task list @tasklist_id.
//
// If not %NULL, free the @out_patched_tasklist with json_object_unref(),
// when no longer needed.
func (x *GDataSession) TasklistsPatchSync(TasklistIdVar string, TasklistPropertiesVar uintptr, OutPatchedTasklistVar *uintptr, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xGDataSessionTasklistsPatchSync(x.GoPointer(), TasklistIdVar, TasklistPropertiesVar, OutPatchedTasklistVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xGDataSessionTasklistsUpdateSync func(uintptr, string, uintptr, *uintptr, uintptr, **glib.Error) bool

// Updates a task list @tasklist_id with values from the @tasklist.
func (x *GDataSession) TasklistsUpdateSync(TasklistIdVar string, TasklistVar uintptr, OutUpdatedTasklistVar *uintptr, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xGDataSessionTasklistsUpdateSync(x.GoPointer(), TasklistIdVar, TasklistVar, OutUpdatedTasklistVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xGDataSessionTasksClearSync func(uintptr, string, uintptr, **glib.Error) bool

// Clears all completed tasks from the task list @tasklist_id. The affected tasks
// will be marked as 'hidden' and no longer be returned by default when retrieving
// all tasks for a task list.
func (x *GDataSession) TasksClearSync(TasklistIdVar string, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xGDataSessionTasksClearSync(x.GoPointer(), TasklistIdVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xGDataSessionTasksDeleteSync func(uintptr, string, string, uintptr, **glib.Error) bool

// Deletes a task @task_id from a task list @tasklist_id.
func (x *GDataSession) TasksDeleteSync(TasklistIdVar string, TaskIdVar string, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xGDataSessionTasksDeleteSync(x.GoPointer(), TasklistIdVar, TaskIdVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xGDataSessionTasksGetSync func(uintptr, string, string, *uintptr, uintptr, **glib.Error) bool

// Gets a task @task_id from a task list @tasklist_id and returns it as a #JsonObject,
// which should be freed with json_object_unref(), when no longer needed.
//
// There can be used e_gdata_task_get_id(), e_gdata_task_get_etag(),
// e_gdata_task_get_title() and other e_gdata_task_... functions
// to read the properties of the task.
func (x *GDataSession) TasksGetSync(TasklistIdVar string, TaskIdVar string, OutTaskVar *uintptr, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xGDataSessionTasksGetSync(x.GoPointer(), TasklistIdVar, TaskIdVar, OutTaskVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xGDataSessionTasksInsertSync func(uintptr, string, uintptr, string, string, *uintptr, uintptr, **glib.Error) bool

// Creates a new task @task in the task list @tasklist_id. The @out_inserted_task should
// be freed with json_object_unref(), when no longer needed.
func (x *GDataSession) TasksInsertSync(TasklistIdVar string, TaskVar uintptr, ParentTaskIdVar string, PreviousTaskIdVar string, OutInsertedTaskVar *uintptr, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xGDataSessionTasksInsertSync(x.GoPointer(), TasklistIdVar, TaskVar, ParentTaskIdVar, PreviousTaskIdVar, OutInsertedTaskVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xGDataSessionTasksListSync func(uintptr, string, *GDataQuery, uintptr, uintptr, uintptr, **glib.Error) bool

// Lists all tasks in the task list @tasklist_id, calling the @cb for each of them.
func (x *GDataSession) TasksListSync(TasklistIdVar string, QueryVar *GDataQuery, CbVar *GDataObjectCallback, UserDataVar uintptr, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xGDataSessionTasksListSync(x.GoPointer(), TasklistIdVar, QueryVar, glib.NewCallback(CbVar), UserDataVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xGDataSessionTasksMoveSync func(uintptr, string, string, string, string, uintptr, **glib.Error) bool

// Moves the specified task @task_id to another position in the task
// list @tasklist_id. This can include putting it as a child task under
// a new parent and/or move it to a different position among its sibling tasks.
func (x *GDataSession) TasksMoveSync(TasklistIdVar string, TaskIdVar string, ParentTaskIdVar string, PreviousTaskIdVar string, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xGDataSessionTasksMoveSync(x.GoPointer(), TasklistIdVar, TaskIdVar, ParentTaskIdVar, PreviousTaskIdVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xGDataSessionTasksPatchSync func(uintptr, string, string, uintptr, *uintptr, uintptr, **glib.Error) bool

// Changes properties @task_properties of a task @task_id in the task list @tasklist_id.
//
// If not %NULL, free the @out_patched_task with json_object_unref(),
// when no longer needed.
func (x *GDataSession) TasksPatchSync(TasklistIdVar string, TaskIdVar string, TaskPropertiesVar uintptr, OutPatchedTaskVar *uintptr, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xGDataSessionTasksPatchSync(x.GoPointer(), TasklistIdVar, TaskIdVar, TaskPropertiesVar, OutPatchedTaskVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xGDataSessionTasksUpdateSync func(uintptr, string, string, uintptr, *uintptr, uintptr, **glib.Error) bool

// Updates a task @task_id in a task list @tasklist_id to the values from the @task.
func (x *GDataSession) TasksUpdateSync(TasklistIdVar string, TaskIdVar string, TaskVar uintptr, OutUpdatedTaskVar *uintptr, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xGDataSessionTasksUpdateSync(x.GoPointer(), TasklistIdVar, TaskIdVar, TaskVar, OutUpdatedTaskVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

func (c *GDataSession) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *GDataSession) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("EDATASERVER", "libedataserver-1.2")
	core.SetSharedLibraries("EDATASERVER", []string{"libcamel-1.2.so.66", "libedataserver-1.2.so.27"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("EDATASERVER") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xGdataTaskAddCompleted, libs, "e_gdata_task_add_completed")
	core.PuregoSafeRegister(&xGdataTaskAddDue, libs, "e_gdata_task_add_due")
	core.PuregoSafeRegister(&xGdataTaskAddId, libs, "e_gdata_task_add_id")
	core.PuregoSafeRegister(&xGdataTaskAddNotes, libs, "e_gdata_task_add_notes")
	core.PuregoSafeRegister(&xGdataTaskAddStatus, libs, "e_gdata_task_add_status")
	core.PuregoSafeRegister(&xGdataTaskAddTitle, libs, "e_gdata_task_add_title")
	core.PuregoSafeRegister(&xGdataTaskGetCompleted, libs, "e_gdata_task_get_completed")
	core.PuregoSafeRegister(&xGdataTaskGetDeleted, libs, "e_gdata_task_get_deleted")
	core.PuregoSafeRegister(&xGdataTaskGetDue, libs, "e_gdata_task_get_due")
	core.PuregoSafeRegister(&xGdataTaskGetEtag, libs, "e_gdata_task_get_etag")
	core.PuregoSafeRegister(&xGdataTaskGetHidden, libs, "e_gdata_task_get_hidden")
	core.PuregoSafeRegister(&xGdataTaskGetId, libs, "e_gdata_task_get_id")
	core.PuregoSafeRegister(&xGdataTaskGetNotes, libs, "e_gdata_task_get_notes")
	core.PuregoSafeRegister(&xGdataTaskGetParent, libs, "e_gdata_task_get_parent")
	core.PuregoSafeRegister(&xGdataTaskGetPosition, libs, "e_gdata_task_get_position")
	core.PuregoSafeRegister(&xGdataTaskGetSelfLink, libs, "e_gdata_task_get_self_link")
	core.PuregoSafeRegister(&xGdataTaskGetStatus, libs, "e_gdata_task_get_status")
	core.PuregoSafeRegister(&xGdataTaskGetTitle, libs, "e_gdata_task_get_title")
	core.PuregoSafeRegister(&xGdataTaskGetUpdated, libs, "e_gdata_task_get_updated")
	core.PuregoSafeRegister(&xGdataTasklistAddId, libs, "e_gdata_tasklist_add_id")
	core.PuregoSafeRegister(&xGdataTasklistAddTitle, libs, "e_gdata_tasklist_add_title")
	core.PuregoSafeRegister(&xGdataTasklistGetEtag, libs, "e_gdata_tasklist_get_etag")
	core.PuregoSafeRegister(&xGdataTasklistGetId, libs, "e_gdata_tasklist_get_id")
	core.PuregoSafeRegister(&xGdataTasklistGetSelfLink, libs, "e_gdata_tasklist_get_self_link")
	core.PuregoSafeRegister(&xGdataTasklistGetTitle, libs, "e_gdata_tasklist_get_title")
	core.PuregoSafeRegister(&xGdataTasklistGetUpdated, libs, "e_gdata_tasklist_get_updated")

	core.PuregoSafeRegister(&xGDataSessionGLibType, libs, "e_gdata_session_get_type")

	core.PuregoSafeRegister(&xNewGDataSession, libs, "e_gdata_session_new")

	core.PuregoSafeRegister(&xGDataSessionTasklistsDeleteSync, libs, "e_gdata_session_tasklists_delete_sync")
	core.PuregoSafeRegister(&xGDataSessionTasklistsGetSync, libs, "e_gdata_session_tasklists_get_sync")
	core.PuregoSafeRegister(&xGDataSessionTasklistsInsertSync, libs, "e_gdata_session_tasklists_insert_sync")
	core.PuregoSafeRegister(&xGDataSessionTasklistsListSync, libs, "e_gdata_session_tasklists_list_sync")
	core.PuregoSafeRegister(&xGDataSessionTasklistsPatchSync, libs, "e_gdata_session_tasklists_patch_sync")
	core.PuregoSafeRegister(&xGDataSessionTasklistsUpdateSync, libs, "e_gdata_session_tasklists_update_sync")
	core.PuregoSafeRegister(&xGDataSessionTasksClearSync, libs, "e_gdata_session_tasks_clear_sync")
	core.PuregoSafeRegister(&xGDataSessionTasksDeleteSync, libs, "e_gdata_session_tasks_delete_sync")
	core.PuregoSafeRegister(&xGDataSessionTasksGetSync, libs, "e_gdata_session_tasks_get_sync")
	core.PuregoSafeRegister(&xGDataSessionTasksInsertSync, libs, "e_gdata_session_tasks_insert_sync")
	core.PuregoSafeRegister(&xGDataSessionTasksListSync, libs, "e_gdata_session_tasks_list_sync")
	core.PuregoSafeRegister(&xGDataSessionTasksMoveSync, libs, "e_gdata_session_tasks_move_sync")
	core.PuregoSafeRegister(&xGDataSessionTasksPatchSync, libs, "e_gdata_session_tasks_patch_sync")
	core.PuregoSafeRegister(&xGDataSessionTasksUpdateSync, libs, "e_gdata_session_tasks_update_sync")

}
