// Package edataserver was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package edataserver

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
)

type MemChunk struct {
	_ structs.HostLayout
}

func (x *MemChunk) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xMemchunkAlloc func(*MemChunk) uintptr

// Allocate a new atom size block of memory from an #EMemChunk.
// Free the returned atom with e_memchunk_free().
func MemchunkAlloc(MemchunkVar *MemChunk) uintptr {

	cret := xMemchunkAlloc(MemchunkVar)
	return cret
}

var xMemchunkAlloc0 func(*MemChunk) uintptr

// Allocate a new atom size block of memory from an #EMemChunk,
// and fill the memory with zeros.  Free the returned atom with
// e_memchunk_free().
func MemchunkAlloc0(MemchunkVar *MemChunk) uintptr {

	cret := xMemchunkAlloc0(MemchunkVar)
	return cret
}

var xMemchunkClean func(*MemChunk)

// Scan all empty blocks and check for blocks which can be free'd
// back to the system.
//
// This routine may take a while to run if there are many allocated
// memory blocks (if the total number of allocations is many times
// greater than atomcount).
func MemchunkClean(MemchunkVar *MemChunk) {

	xMemchunkClean(MemchunkVar)

}

var xMemchunkDestroy func(*MemChunk)

// Free the memchunk header, and all associated memory.
func MemchunkDestroy(MemchunkVar *MemChunk) {

	xMemchunkDestroy(MemchunkVar)

}

var xMemchunkEmpty func(*MemChunk)

// Clean out the memchunk buffers.  Marks all allocated memory as free blocks,
// but does not give it back to the system.  Can be used if the memchunk
// is to be used repeatedly.
func MemchunkEmpty(MemchunkVar *MemChunk) {

	xMemchunkEmpty(MemchunkVar)

}

var xMemchunkFree func(*MemChunk, uintptr)

// Free a single atom back to the free pool of atoms in the given
// memchunk.
func MemchunkFree(MemchunkVar *MemChunk, MemVar uintptr) {

	xMemchunkFree(MemchunkVar, MemVar)

}

var xMemchunkNew func(int, int) *MemChunk

// Create a new #EMemChunk header.  Memchunks are an efficient way to
// allocate and deallocate identical sized blocks of memory quickly, and
// space efficiently.
//
// e_memchunks are effectively the same as gmemchunks, only faster (much),
// and they use less memory overhead for housekeeping.
func MemchunkNew(AtomcountVar int, AtomsizeVar int) *MemChunk {

	cret := xMemchunkNew(AtomcountVar, AtomsizeVar)
	return cret
}

func init() {
	core.SetPackageName("EDATASERVER", "libedataserver-1.2")
	core.SetSharedLibraries("EDATASERVER", []string{"libcamel-1.2.so.66", "libedataserver-1.2.so.27"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("EDATASERVER") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xMemchunkAlloc, libs, "e_memchunk_alloc")
	core.PuregoSafeRegister(&xMemchunkAlloc0, libs, "e_memchunk_alloc0")
	core.PuregoSafeRegister(&xMemchunkClean, libs, "e_memchunk_clean")
	core.PuregoSafeRegister(&xMemchunkDestroy, libs, "e_memchunk_destroy")
	core.PuregoSafeRegister(&xMemchunkEmpty, libs, "e_memchunk_empty")
	core.PuregoSafeRegister(&xMemchunkFree, libs, "e_memchunk_free")
	core.PuregoSafeRegister(&xMemchunkNew, libs, "e_memchunk_new")

}
