// Package edataserver was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package edataserver

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/glib"
)

// Contains only private data that should be read and manipulated using the
// functions below.
type OperationPool struct {
	_ structs.HostLayout
}

func (x *OperationPool) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xOperationPoolFree func(uintptr)

// Frees previously created @pool.
func (x *OperationPool) Free() {

	xOperationPoolFree(x.GoPointer())

}

var xOperationPoolPush func(uintptr, uintptr)

// Pushes an operation to be processed.  @opdata is passed to the function
// provided in e_operation_pool_new().
func (x *OperationPool) Push(OpdataVar uintptr) {

	xOperationPoolPush(x.GoPointer(), OpdataVar)

}

var xOperationPoolReleaseOpid func(uintptr, uint32)

// Releases @opid previously reserved by e_operation_pool_reserve_opid().
func (x *OperationPool) ReleaseOpid(OpidVar uint32) {

	xOperationPoolReleaseOpid(x.GoPointer(), OpidVar)

}

var xOperationPoolReserveOpid func(uintptr) uint32

// Reserves new operation ID, which is returned. This operation ID may
// be released by e_operation_pool_release_opid() when the operation
// is finished.
func (x *OperationPool) ReserveOpid() uint32 {

	cret := xOperationPoolReserveOpid(x.GoPointer())
	return cret
}

var xOperationPoolNew func(uint, uintptr, uintptr) *OperationPool

func OperationPoolNew(MaxThreadsVar uint, ThreadFuncVar *glib.Func, UserDataVar uintptr) *OperationPool {

	cret := xOperationPoolNew(MaxThreadsVar, glib.NewCallback(ThreadFuncVar), UserDataVar)
	return cret
}

func init() {
	core.SetPackageName("EDATASERVER", "libedataserver-1.2")
	core.SetSharedLibraries("EDATASERVER", []string{"libcamel-1.2.so.66", "libedataserver-1.2.so.27"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("EDATASERVER") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xOperationPoolNew, libs, "e_operation_pool_new")

	core.PuregoSafeRegister(&xOperationPoolFree, libs, "e_operation_pool_free")
	core.PuregoSafeRegister(&xOperationPoolPush, libs, "e_operation_pool_push")
	core.PuregoSafeRegister(&xOperationPoolReleaseOpid, libs, "e_operation_pool_release_opid")
	core.PuregoSafeRegister(&xOperationPoolReserveOpid, libs, "e_operation_pool_reserve_opid")

}
