// Package edataserver was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package edataserver

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type SourceMailIdentityClassGType struct {
	_ structs.HostLayout

	ParentClass SourceExtensionClassGType
}

func (x *SourceMailIdentityClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type SourceMailIdentityPrivate struct {
	_ structs.HostLayout
}

func (x *SourceMailIdentityPrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

const (
	// Pass this extension name to e_source_get_extension() to access
	// #ESourceMailIdentity.  This is also used as a group name in key files.
	SOURCE_EXTENSION_MAIL_IDENTITY string = "Mail Identity"
)

// Contains only private data that should be read and manipulated using the
// functions below.
type SourceMailIdentity struct {
	SourceExtension
}

var xSourceMailIdentityGLibType func() types.GType

func SourceMailIdentityGLibType() types.GType {
	return xSourceMailIdentityGLibType()
}

func SourceMailIdentityNewFromInternalPtr(ptr uintptr) *SourceMailIdentity {
	cls := &SourceMailIdentity{}
	cls.Ptr = ptr
	return cls
}

var xSourceMailIdentityDupAddress func(uintptr) string

// Thread-safe variation of e_source_mail_identity_get_address().
// Use this function when accessing @extension from multiple threads.
//
// The returned string should be freed with g_free() when no longer needed.
func (x *SourceMailIdentity) DupAddress() string {

	cret := xSourceMailIdentityDupAddress(x.GoPointer())
	return cret
}

var xSourceMailIdentityDupAliases func(uintptr) string

// Thread-safe variation of e_source_mail_identity_get_aliases().
// Use this function when accessing @extension from multiple threads.
//
// The returned string should be freed with g_free() when no longer needed.
func (x *SourceMailIdentity) DupAliases() string {

	cret := xSourceMailIdentityDupAliases(x.GoPointer())
	return cret
}

var xSourceMailIdentityDupName func(uintptr) string

// Thread-safe variation of e_source_mail_identity_get_name().
// Use this function when accessing @extension from multiple threads.
//
// The returned string should be freed with g_free() when no longer needed.
func (x *SourceMailIdentity) DupName() string {

	cret := xSourceMailIdentityDupName(x.GoPointer())
	return cret
}

var xSourceMailIdentityDupOrganization func(uintptr) string

// Thread-safe variation of e_source_mail_identity_dup_organization().
// Use this function when accessing @extension from multiple threads.
//
// The returned string should be freed with g_free() when no longer needed.
func (x *SourceMailIdentity) DupOrganization() string {

	cret := xSourceMailIdentityDupOrganization(x.GoPointer())
	return cret
}

var xSourceMailIdentityDupReplyTo func(uintptr) string

// Thread-safe variation of e_source_mail_identity_get_reply_to().
// Use this function when accessing @extension from multiple threads.
//
// The returned string should be freed with g_free() when no longer needed.
func (x *SourceMailIdentity) DupReplyTo() string {

	cret := xSourceMailIdentityDupReplyTo(x.GoPointer())
	return cret
}

var xSourceMailIdentityDupSignatureUid func(uintptr) string

// Thread-safe variation of e_source_mail_identity_get_signature_uid().
// Use this function when accessing @extension from multiple threads.
//
// The returned string should be freed with g_free() when no longer needed.
func (x *SourceMailIdentity) DupSignatureUid() string {

	cret := xSourceMailIdentityDupSignatureUid(x.GoPointer())
	return cret
}

var xSourceMailIdentityGetAddress func(uintptr) string

// Returns the email address for this identity from which to send messages.
// This may be an empty string but will never be %NULL.
func (x *SourceMailIdentity) GetAddress() string {

	cret := xSourceMailIdentityGetAddress(x.GoPointer())
	return cret
}

var xSourceMailIdentityGetAliases func(uintptr) string

// Returns the email address aliases for this identity. These are comma-separated
// email addresses which may or may not contain also different name.
// This may be an empty string, but will never be %NULL.
// There can be used camel_address_decode() on a #CamelInternetAddress
// to decode the list of aliases.
func (x *SourceMailIdentity) GetAliases() string {

	cret := xSourceMailIdentityGetAliases(x.GoPointer())
	return cret
}

var xSourceMailIdentityGetAliasesAsHashTable func(uintptr) *glib.HashTable

// Returns a set aliases as a hash table with address as key and
// name as value of the hash table. The name can be sometimes
// empty or NULL, thus rather use g_hash_table_contains() when
// checking for particular address. The addresses are
// compared case insensitively. The same addresses with a different
// name are included only once, the last variant of it. Use
// e_source_mail_identity_get_aliases() if you need more fine-grained
// control on the list of aliases.
func (x *SourceMailIdentity) GetAliasesAsHashTable() *glib.HashTable {

	cret := xSourceMailIdentityGetAliasesAsHashTable(x.GoPointer())
	return cret
}

var xSourceMailIdentityGetName func(uintptr) string

// Returns the sender's name for this identity.
func (x *SourceMailIdentity) GetName() string {

	cret := xSourceMailIdentityGetName(x.GoPointer())
	return cret
}

var xSourceMailIdentityGetOrganization func(uintptr) string

// Returns the sender's organization for this identity.
func (x *SourceMailIdentity) GetOrganization() string {

	cret := xSourceMailIdentityGetOrganization(x.GoPointer())
	return cret
}

var xSourceMailIdentityGetReplyTo func(uintptr) string

// Returns the email address for this identity to which recipients should
// send replies.
func (x *SourceMailIdentity) GetReplyTo() string {

	cret := xSourceMailIdentityGetReplyTo(x.GoPointer())
	return cret
}

var xSourceMailIdentityGetSignatureUid func(uintptr) string

// Returns the #ESource:uid of an #ESource describing a mail signature.
//
// If the user does not want to use a signature for this identity, the
// convention is to set the #ESourceMailIdentity:signature-uid property
// to "none".
func (x *SourceMailIdentity) GetSignatureUid() string {

	cret := xSourceMailIdentityGetSignatureUid(x.GoPointer())
	return cret
}

var xSourceMailIdentitySetAddress func(uintptr, string)

// Sets the email address for this identity from which to send messages.
//
// The internal copy of @address is automatically stripped of leading and
// trailing whitespace.  If the resulting string is empty, %NULL is set
// instead.
func (x *SourceMailIdentity) SetAddress(AddressVar string) {

	xSourceMailIdentitySetAddress(x.GoPointer(), AddressVar)

}

var xSourceMailIdentitySetAliases func(uintptr, string)

// Sets the email address aliases for this identity. These are comma-separated
// email addresses which may or may not contain also different name.
//
// The internal copy of @aliases is automatically stripped of leading and
// trailing whitespace. If the resulting string is empty, %NULL is set
// instead.
func (x *SourceMailIdentity) SetAliases(AliasesVar string) {

	xSourceMailIdentitySetAliases(x.GoPointer(), AliasesVar)

}

var xSourceMailIdentitySetName func(uintptr, string)

// Sets the sender's name for this identity.
//
// The internal copy of @name is automatically stripped of leading and
// trailing whitespace.
func (x *SourceMailIdentity) SetName(NameVar string) {

	xSourceMailIdentitySetName(x.GoPointer(), NameVar)

}

var xSourceMailIdentitySetOrganization func(uintptr, string)

// Sets the sender's organization for this identity.
//
// The internal copy of @organization is automatically stripped of leading
// and trailing whitespace.  If the resulting string is empty, %NULL is set
// instead.
func (x *SourceMailIdentity) SetOrganization(OrganizationVar string) {

	xSourceMailIdentitySetOrganization(x.GoPointer(), OrganizationVar)

}

var xSourceMailIdentitySetReplyTo func(uintptr, string)

// Sets the email address for this identity to which recipients should
// send replies.
//
// The internal copy of @reply_to is automatically stripped of leading
// and trailing whitespace.  If the resulting string is empty, %NULL is
// set instead.
func (x *SourceMailIdentity) SetReplyTo(ReplyToVar string) {

	xSourceMailIdentitySetReplyTo(x.GoPointer(), ReplyToVar)

}

var xSourceMailIdentitySetSignatureUid func(uintptr, string)

// Sets the #ESource:uid of an #ESource describing a mail signature.
//
// If the user does not want to use a signature for this identity, the
// convention is to set the #ESourceMailIdentity:signature-uid property
// to "none".  In keeping with that convention, the property will be set
// to "none" if @signature_uid is %NULL or an empty string.
func (x *SourceMailIdentity) SetSignatureUid(SignatureUidVar string) {

	xSourceMailIdentitySetSignatureUid(x.GoPointer(), SignatureUidVar)

}

func (c *SourceMailIdentity) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *SourceMailIdentity) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// SetPropertyAddress sets the "address" property.
// Sender's email address
func (x *SourceMailIdentity) SetPropertyAddress(value string) {
	var v gobject.Value
	v.Init(gobject.TypeStringVal)
	v.SetString(value)
	x.SetProperty("address", &v)
}

// GetPropertyAddress gets the "address" property.
// Sender's email address
func (x *SourceMailIdentity) GetPropertyAddress() string {
	var v gobject.Value
	x.GetProperty("address", &v)
	return v.GetString()
}

// SetPropertyAliases sets the "aliases" property.
// Sender's email address aliases
func (x *SourceMailIdentity) SetPropertyAliases(value string) {
	var v gobject.Value
	v.Init(gobject.TypeStringVal)
	v.SetString(value)
	x.SetProperty("aliases", &v)
}

// GetPropertyAliases gets the "aliases" property.
// Sender's email address aliases
func (x *SourceMailIdentity) GetPropertyAliases() string {
	var v gobject.Value
	x.GetProperty("aliases", &v)
	return v.GetString()
}

// SetPropertyName sets the "name" property.
// Sender's name
func (x *SourceMailIdentity) SetPropertyName(value string) {
	var v gobject.Value
	v.Init(gobject.TypeStringVal)
	v.SetString(value)
	x.SetProperty("name", &v)
}

// GetPropertyName gets the "name" property.
// Sender's name
func (x *SourceMailIdentity) GetPropertyName() string {
	var v gobject.Value
	x.GetProperty("name", &v)
	return v.GetString()
}

// SetPropertyOrganization sets the "organization" property.
// Sender's organization
func (x *SourceMailIdentity) SetPropertyOrganization(value string) {
	var v gobject.Value
	v.Init(gobject.TypeStringVal)
	v.SetString(value)
	x.SetProperty("organization", &v)
}

// GetPropertyOrganization gets the "organization" property.
// Sender's organization
func (x *SourceMailIdentity) GetPropertyOrganization() string {
	var v gobject.Value
	x.GetProperty("organization", &v)
	return v.GetString()
}

// SetPropertyReplyTo sets the "reply-to" property.
// Sender's reply-to address
func (x *SourceMailIdentity) SetPropertyReplyTo(value string) {
	var v gobject.Value
	v.Init(gobject.TypeStringVal)
	v.SetString(value)
	x.SetProperty("reply-to", &v)
}

// GetPropertyReplyTo gets the "reply-to" property.
// Sender's reply-to address
func (x *SourceMailIdentity) GetPropertyReplyTo() string {
	var v gobject.Value
	x.GetProperty("reply-to", &v)
	return v.GetString()
}

// SetPropertySignatureUid sets the "signature-uid" property.
// ESource UID of the sender's signature
func (x *SourceMailIdentity) SetPropertySignatureUid(value string) {
	var v gobject.Value
	v.Init(gobject.TypeStringVal)
	v.SetString(value)
	x.SetProperty("signature-uid", &v)
}

// GetPropertySignatureUid gets the "signature-uid" property.
// ESource UID of the sender's signature
func (x *SourceMailIdentity) GetPropertySignatureUid() string {
	var v gobject.Value
	x.GetProperty("signature-uid", &v)
	return v.GetString()
}

func init() {
	core.SetPackageName("EDATASERVER", "libedataserver-1.2")
	core.SetSharedLibraries("EDATASERVER", []string{"libcamel-1.2.so.66", "libedataserver-1.2.so.27"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("EDATASERVER") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xSourceMailIdentityGLibType, libs, "e_source_mail_identity_get_type")

	core.PuregoSafeRegister(&xSourceMailIdentityDupAddress, libs, "e_source_mail_identity_dup_address")
	core.PuregoSafeRegister(&xSourceMailIdentityDupAliases, libs, "e_source_mail_identity_dup_aliases")
	core.PuregoSafeRegister(&xSourceMailIdentityDupName, libs, "e_source_mail_identity_dup_name")
	core.PuregoSafeRegister(&xSourceMailIdentityDupOrganization, libs, "e_source_mail_identity_dup_organization")
	core.PuregoSafeRegister(&xSourceMailIdentityDupReplyTo, libs, "e_source_mail_identity_dup_reply_to")
	core.PuregoSafeRegister(&xSourceMailIdentityDupSignatureUid, libs, "e_source_mail_identity_dup_signature_uid")
	core.PuregoSafeRegister(&xSourceMailIdentityGetAddress, libs, "e_source_mail_identity_get_address")
	core.PuregoSafeRegister(&xSourceMailIdentityGetAliases, libs, "e_source_mail_identity_get_aliases")
	core.PuregoSafeRegister(&xSourceMailIdentityGetAliasesAsHashTable, libs, "e_source_mail_identity_get_aliases_as_hash_table")
	core.PuregoSafeRegister(&xSourceMailIdentityGetName, libs, "e_source_mail_identity_get_name")
	core.PuregoSafeRegister(&xSourceMailIdentityGetOrganization, libs, "e_source_mail_identity_get_organization")
	core.PuregoSafeRegister(&xSourceMailIdentityGetReplyTo, libs, "e_source_mail_identity_get_reply_to")
	core.PuregoSafeRegister(&xSourceMailIdentityGetSignatureUid, libs, "e_source_mail_identity_get_signature_uid")
	core.PuregoSafeRegister(&xSourceMailIdentitySetAddress, libs, "e_source_mail_identity_set_address")
	core.PuregoSafeRegister(&xSourceMailIdentitySetAliases, libs, "e_source_mail_identity_set_aliases")
	core.PuregoSafeRegister(&xSourceMailIdentitySetName, libs, "e_source_mail_identity_set_name")
	core.PuregoSafeRegister(&xSourceMailIdentitySetOrganization, libs, "e_source_mail_identity_set_organization")
	core.PuregoSafeRegister(&xSourceMailIdentitySetReplyTo, libs, "e_source_mail_identity_set_reply_to")
	core.PuregoSafeRegister(&xSourceMailIdentitySetSignatureUid, libs, "e_source_mail_identity_set_signature_uid")

}
