// Package edataserver was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package edataserver

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/camel"
	"github.com/jwijenbergh/puregotk/v4/gio"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type SourceClassGType struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClassGType

	xChanged uintptr

	xCredentialsRequired uintptr

	xAuthenticate uintptr

	xRemoveSync uintptr

	xRemove uintptr

	xRemoveFinish uintptr

	xWriteSync uintptr

	xWrite uintptr

	xWriteFinish uintptr

	xRemoteCreateSync uintptr

	xRemoteCreate uintptr

	xRemoteCreateFinish uintptr

	xRemoteDeleteSync uintptr

	xRemoteDelete uintptr

	xRemoteDeleteFinish uintptr

	xGetOauth2AccessTokenSync uintptr

	xGetOauth2AccessToken uintptr

	xGetOauth2AccessTokenFinish uintptr

	xInvokeCredentialsRequiredImpl uintptr

	xInvokeAuthenticateImpl uintptr

	xUnsetLastCredentialsRequiredArgumentsImpl uintptr

	Reserved [6]uintptr
}

func (x *SourceClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// OverrideChanged sets the "changed" callback function.
func (x *SourceClassGType) OverrideChanged(cb func(*Source)) {
	if cb == nil {
		x.xChanged = 0
	} else {
		x.xChanged = purego.NewCallback(func(SourceVarp uintptr) {
			cb(SourceNewFromInternalPtr(SourceVarp))
		})
	}
}

// GetChanged gets the "changed" callback function.
func (x *SourceClassGType) GetChanged() func(*Source) {
	if x.xChanged == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr)
	purego.RegisterFunc(&rawCallback, x.xChanged)
	return func(SourceVar *Source) {
		rawCallback(SourceVar.GoPointer())
	}
}

// OverrideCredentialsRequired sets the "credentials_required" callback function.
func (x *SourceClassGType) OverrideCredentialsRequired(cb func(*Source, SourceCredentialsReason, string, gio.TlsCertificateFlags, *glib.Error)) {
	if cb == nil {
		x.xCredentialsRequired = 0
	} else {
		x.xCredentialsRequired = purego.NewCallback(func(SourceVarp uintptr, ReasonVarp SourceCredentialsReason, CertificatePemVarp string, CertificateErrorsVarp gio.TlsCertificateFlags, OpErrorVarp *glib.Error) {
			cb(SourceNewFromInternalPtr(SourceVarp), ReasonVarp, CertificatePemVarp, CertificateErrorsVarp, OpErrorVarp)
		})
	}
}

// GetCredentialsRequired gets the "credentials_required" callback function.
func (x *SourceClassGType) GetCredentialsRequired() func(*Source, SourceCredentialsReason, string, gio.TlsCertificateFlags, *glib.Error) {
	if x.xCredentialsRequired == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, ReasonVarp SourceCredentialsReason, CertificatePemVarp string, CertificateErrorsVarp gio.TlsCertificateFlags, OpErrorVarp *glib.Error)
	purego.RegisterFunc(&rawCallback, x.xCredentialsRequired)
	return func(SourceVar *Source, ReasonVar SourceCredentialsReason, CertificatePemVar string, CertificateErrorsVar gio.TlsCertificateFlags, OpErrorVar *glib.Error) {
		rawCallback(SourceVar.GoPointer(), ReasonVar, CertificatePemVar, CertificateErrorsVar, OpErrorVar)
	}
}

// OverrideAuthenticate sets the "authenticate" callback function.
func (x *SourceClassGType) OverrideAuthenticate(cb func(*Source, *NamedParameters)) {
	if cb == nil {
		x.xAuthenticate = 0
	} else {
		x.xAuthenticate = purego.NewCallback(func(SourceVarp uintptr, CredentialsVarp *NamedParameters) {
			cb(SourceNewFromInternalPtr(SourceVarp), CredentialsVarp)
		})
	}
}

// GetAuthenticate gets the "authenticate" callback function.
func (x *SourceClassGType) GetAuthenticate() func(*Source, *NamedParameters) {
	if x.xAuthenticate == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, CredentialsVarp *NamedParameters)
	purego.RegisterFunc(&rawCallback, x.xAuthenticate)
	return func(SourceVar *Source, CredentialsVar *NamedParameters) {
		rawCallback(SourceVar.GoPointer(), CredentialsVar)
	}
}

// OverrideRemoveSync sets the "remove_sync" callback function.
func (x *SourceClassGType) OverrideRemoveSync(cb func(*Source, *gio.Cancellable) bool) {
	if cb == nil {
		x.xRemoveSync = 0
	} else {
		x.xRemoveSync = purego.NewCallback(func(SourceVarp uintptr, CancellableVarp uintptr) bool {
			return cb(SourceNewFromInternalPtr(SourceVarp), gio.CancellableNewFromInternalPtr(CancellableVarp))
		})
	}
}

// GetRemoveSync gets the "remove_sync" callback function.
func (x *SourceClassGType) GetRemoveSync() func(*Source, *gio.Cancellable) bool {
	if x.xRemoveSync == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, CancellableVarp uintptr) bool
	purego.RegisterFunc(&rawCallback, x.xRemoveSync)
	return func(SourceVar *Source, CancellableVar *gio.Cancellable) bool {
		return rawCallback(SourceVar.GoPointer(), CancellableVar.GoPointer())
	}
}

// OverrideRemove sets the "remove" callback function.
func (x *SourceClassGType) OverrideRemove(cb func(*Source, *gio.Cancellable, *gio.AsyncReadyCallback, uintptr)) {
	if cb == nil {
		x.xRemove = 0
	} else {
		x.xRemove = purego.NewCallback(func(SourceVarp uintptr, CancellableVarp uintptr, CallbackVarp uintptr, UserDataVarp uintptr) {
			cb(SourceNewFromInternalPtr(SourceVarp), gio.CancellableNewFromInternalPtr(CancellableVarp), (*gio.AsyncReadyCallback)(unsafe.Pointer(CallbackVarp)), UserDataVarp)
		})
	}
}

// GetRemove gets the "remove" callback function.
func (x *SourceClassGType) GetRemove() func(*Source, *gio.Cancellable, *gio.AsyncReadyCallback, uintptr) {
	if x.xRemove == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, CancellableVarp uintptr, CallbackVarp uintptr, UserDataVarp uintptr)
	purego.RegisterFunc(&rawCallback, x.xRemove)
	return func(SourceVar *Source, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {
		rawCallback(SourceVar.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)
	}
}

// OverrideRemoveFinish sets the "remove_finish" callback function.
func (x *SourceClassGType) OverrideRemoveFinish(cb func(*Source, gio.AsyncResult) bool) {
	if cb == nil {
		x.xRemoveFinish = 0
	} else {
		x.xRemoveFinish = purego.NewCallback(func(SourceVarp uintptr, ResultVarp uintptr) bool {
			return cb(SourceNewFromInternalPtr(SourceVarp), &gio.AsyncResultBase{Ptr: ResultVarp})
		})
	}
}

// GetRemoveFinish gets the "remove_finish" callback function.
func (x *SourceClassGType) GetRemoveFinish() func(*Source, gio.AsyncResult) bool {
	if x.xRemoveFinish == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, ResultVarp uintptr) bool
	purego.RegisterFunc(&rawCallback, x.xRemoveFinish)
	return func(SourceVar *Source, ResultVar gio.AsyncResult) bool {
		return rawCallback(SourceVar.GoPointer(), ResultVar.GoPointer())
	}
}

// OverrideWriteSync sets the "write_sync" callback function.
func (x *SourceClassGType) OverrideWriteSync(cb func(*Source, *gio.Cancellable) bool) {
	if cb == nil {
		x.xWriteSync = 0
	} else {
		x.xWriteSync = purego.NewCallback(func(SourceVarp uintptr, CancellableVarp uintptr) bool {
			return cb(SourceNewFromInternalPtr(SourceVarp), gio.CancellableNewFromInternalPtr(CancellableVarp))
		})
	}
}

// GetWriteSync gets the "write_sync" callback function.
func (x *SourceClassGType) GetWriteSync() func(*Source, *gio.Cancellable) bool {
	if x.xWriteSync == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, CancellableVarp uintptr) bool
	purego.RegisterFunc(&rawCallback, x.xWriteSync)
	return func(SourceVar *Source, CancellableVar *gio.Cancellable) bool {
		return rawCallback(SourceVar.GoPointer(), CancellableVar.GoPointer())
	}
}

// OverrideWrite sets the "write" callback function.
func (x *SourceClassGType) OverrideWrite(cb func(*Source, *gio.Cancellable, *gio.AsyncReadyCallback, uintptr)) {
	if cb == nil {
		x.xWrite = 0
	} else {
		x.xWrite = purego.NewCallback(func(SourceVarp uintptr, CancellableVarp uintptr, CallbackVarp uintptr, UserDataVarp uintptr) {
			cb(SourceNewFromInternalPtr(SourceVarp), gio.CancellableNewFromInternalPtr(CancellableVarp), (*gio.AsyncReadyCallback)(unsafe.Pointer(CallbackVarp)), UserDataVarp)
		})
	}
}

// GetWrite gets the "write" callback function.
func (x *SourceClassGType) GetWrite() func(*Source, *gio.Cancellable, *gio.AsyncReadyCallback, uintptr) {
	if x.xWrite == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, CancellableVarp uintptr, CallbackVarp uintptr, UserDataVarp uintptr)
	purego.RegisterFunc(&rawCallback, x.xWrite)
	return func(SourceVar *Source, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {
		rawCallback(SourceVar.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)
	}
}

// OverrideWriteFinish sets the "write_finish" callback function.
func (x *SourceClassGType) OverrideWriteFinish(cb func(*Source, gio.AsyncResult) bool) {
	if cb == nil {
		x.xWriteFinish = 0
	} else {
		x.xWriteFinish = purego.NewCallback(func(SourceVarp uintptr, ResultVarp uintptr) bool {
			return cb(SourceNewFromInternalPtr(SourceVarp), &gio.AsyncResultBase{Ptr: ResultVarp})
		})
	}
}

// GetWriteFinish gets the "write_finish" callback function.
func (x *SourceClassGType) GetWriteFinish() func(*Source, gio.AsyncResult) bool {
	if x.xWriteFinish == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, ResultVarp uintptr) bool
	purego.RegisterFunc(&rawCallback, x.xWriteFinish)
	return func(SourceVar *Source, ResultVar gio.AsyncResult) bool {
		return rawCallback(SourceVar.GoPointer(), ResultVar.GoPointer())
	}
}

// OverrideRemoteCreateSync sets the "remote_create_sync" callback function.
func (x *SourceClassGType) OverrideRemoteCreateSync(cb func(*Source, *Source, *gio.Cancellable) bool) {
	if cb == nil {
		x.xRemoteCreateSync = 0
	} else {
		x.xRemoteCreateSync = purego.NewCallback(func(SourceVarp uintptr, ScratchSourceVarp uintptr, CancellableVarp uintptr) bool {
			return cb(SourceNewFromInternalPtr(SourceVarp), SourceNewFromInternalPtr(ScratchSourceVarp), gio.CancellableNewFromInternalPtr(CancellableVarp))
		})
	}
}

// GetRemoteCreateSync gets the "remote_create_sync" callback function.
func (x *SourceClassGType) GetRemoteCreateSync() func(*Source, *Source, *gio.Cancellable) bool {
	if x.xRemoteCreateSync == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, ScratchSourceVarp uintptr, CancellableVarp uintptr) bool
	purego.RegisterFunc(&rawCallback, x.xRemoteCreateSync)
	return func(SourceVar *Source, ScratchSourceVar *Source, CancellableVar *gio.Cancellable) bool {
		return rawCallback(SourceVar.GoPointer(), ScratchSourceVar.GoPointer(), CancellableVar.GoPointer())
	}
}

// OverrideRemoteCreate sets the "remote_create" callback function.
func (x *SourceClassGType) OverrideRemoteCreate(cb func(*Source, *Source, *gio.Cancellable, *gio.AsyncReadyCallback, uintptr)) {
	if cb == nil {
		x.xRemoteCreate = 0
	} else {
		x.xRemoteCreate = purego.NewCallback(func(SourceVarp uintptr, ScratchSourceVarp uintptr, CancellableVarp uintptr, CallbackVarp uintptr, UserDataVarp uintptr) {
			cb(SourceNewFromInternalPtr(SourceVarp), SourceNewFromInternalPtr(ScratchSourceVarp), gio.CancellableNewFromInternalPtr(CancellableVarp), (*gio.AsyncReadyCallback)(unsafe.Pointer(CallbackVarp)), UserDataVarp)
		})
	}
}

// GetRemoteCreate gets the "remote_create" callback function.
func (x *SourceClassGType) GetRemoteCreate() func(*Source, *Source, *gio.Cancellable, *gio.AsyncReadyCallback, uintptr) {
	if x.xRemoteCreate == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, ScratchSourceVarp uintptr, CancellableVarp uintptr, CallbackVarp uintptr, UserDataVarp uintptr)
	purego.RegisterFunc(&rawCallback, x.xRemoteCreate)
	return func(SourceVar *Source, ScratchSourceVar *Source, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {
		rawCallback(SourceVar.GoPointer(), ScratchSourceVar.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)
	}
}

// OverrideRemoteCreateFinish sets the "remote_create_finish" callback function.
func (x *SourceClassGType) OverrideRemoteCreateFinish(cb func(*Source, gio.AsyncResult) bool) {
	if cb == nil {
		x.xRemoteCreateFinish = 0
	} else {
		x.xRemoteCreateFinish = purego.NewCallback(func(SourceVarp uintptr, ResultVarp uintptr) bool {
			return cb(SourceNewFromInternalPtr(SourceVarp), &gio.AsyncResultBase{Ptr: ResultVarp})
		})
	}
}

// GetRemoteCreateFinish gets the "remote_create_finish" callback function.
func (x *SourceClassGType) GetRemoteCreateFinish() func(*Source, gio.AsyncResult) bool {
	if x.xRemoteCreateFinish == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, ResultVarp uintptr) bool
	purego.RegisterFunc(&rawCallback, x.xRemoteCreateFinish)
	return func(SourceVar *Source, ResultVar gio.AsyncResult) bool {
		return rawCallback(SourceVar.GoPointer(), ResultVar.GoPointer())
	}
}

// OverrideRemoteDeleteSync sets the "remote_delete_sync" callback function.
func (x *SourceClassGType) OverrideRemoteDeleteSync(cb func(*Source, *gio.Cancellable) bool) {
	if cb == nil {
		x.xRemoteDeleteSync = 0
	} else {
		x.xRemoteDeleteSync = purego.NewCallback(func(SourceVarp uintptr, CancellableVarp uintptr) bool {
			return cb(SourceNewFromInternalPtr(SourceVarp), gio.CancellableNewFromInternalPtr(CancellableVarp))
		})
	}
}

// GetRemoteDeleteSync gets the "remote_delete_sync" callback function.
func (x *SourceClassGType) GetRemoteDeleteSync() func(*Source, *gio.Cancellable) bool {
	if x.xRemoteDeleteSync == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, CancellableVarp uintptr) bool
	purego.RegisterFunc(&rawCallback, x.xRemoteDeleteSync)
	return func(SourceVar *Source, CancellableVar *gio.Cancellable) bool {
		return rawCallback(SourceVar.GoPointer(), CancellableVar.GoPointer())
	}
}

// OverrideRemoteDelete sets the "remote_delete" callback function.
func (x *SourceClassGType) OverrideRemoteDelete(cb func(*Source, *gio.Cancellable, *gio.AsyncReadyCallback, uintptr)) {
	if cb == nil {
		x.xRemoteDelete = 0
	} else {
		x.xRemoteDelete = purego.NewCallback(func(SourceVarp uintptr, CancellableVarp uintptr, CallbackVarp uintptr, UserDataVarp uintptr) {
			cb(SourceNewFromInternalPtr(SourceVarp), gio.CancellableNewFromInternalPtr(CancellableVarp), (*gio.AsyncReadyCallback)(unsafe.Pointer(CallbackVarp)), UserDataVarp)
		})
	}
}

// GetRemoteDelete gets the "remote_delete" callback function.
func (x *SourceClassGType) GetRemoteDelete() func(*Source, *gio.Cancellable, *gio.AsyncReadyCallback, uintptr) {
	if x.xRemoteDelete == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, CancellableVarp uintptr, CallbackVarp uintptr, UserDataVarp uintptr)
	purego.RegisterFunc(&rawCallback, x.xRemoteDelete)
	return func(SourceVar *Source, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {
		rawCallback(SourceVar.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)
	}
}

// OverrideRemoteDeleteFinish sets the "remote_delete_finish" callback function.
func (x *SourceClassGType) OverrideRemoteDeleteFinish(cb func(*Source, gio.AsyncResult) bool) {
	if cb == nil {
		x.xRemoteDeleteFinish = 0
	} else {
		x.xRemoteDeleteFinish = purego.NewCallback(func(SourceVarp uintptr, ResultVarp uintptr) bool {
			return cb(SourceNewFromInternalPtr(SourceVarp), &gio.AsyncResultBase{Ptr: ResultVarp})
		})
	}
}

// GetRemoteDeleteFinish gets the "remote_delete_finish" callback function.
func (x *SourceClassGType) GetRemoteDeleteFinish() func(*Source, gio.AsyncResult) bool {
	if x.xRemoteDeleteFinish == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, ResultVarp uintptr) bool
	purego.RegisterFunc(&rawCallback, x.xRemoteDeleteFinish)
	return func(SourceVar *Source, ResultVar gio.AsyncResult) bool {
		return rawCallback(SourceVar.GoPointer(), ResultVar.GoPointer())
	}
}

// OverrideGetOauth2AccessTokenSync sets the "get_oauth2_access_token_sync" callback function.
func (x *SourceClassGType) OverrideGetOauth2AccessTokenSync(cb func(*Source, *gio.Cancellable, *string, *int) bool) {
	if cb == nil {
		x.xGetOauth2AccessTokenSync = 0
	} else {
		x.xGetOauth2AccessTokenSync = purego.NewCallback(func(SourceVarp uintptr, CancellableVarp uintptr, OutAccessTokenVarp *string, OutExpiresInVarp *int) bool {
			return cb(SourceNewFromInternalPtr(SourceVarp), gio.CancellableNewFromInternalPtr(CancellableVarp), OutAccessTokenVarp, OutExpiresInVarp)
		})
	}
}

// GetGetOauth2AccessTokenSync gets the "get_oauth2_access_token_sync" callback function.
func (x *SourceClassGType) GetGetOauth2AccessTokenSync() func(*Source, *gio.Cancellable, *string, *int) bool {
	if x.xGetOauth2AccessTokenSync == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, CancellableVarp uintptr, OutAccessTokenVarp *string, OutExpiresInVarp *int) bool
	purego.RegisterFunc(&rawCallback, x.xGetOauth2AccessTokenSync)
	return func(SourceVar *Source, CancellableVar *gio.Cancellable, OutAccessTokenVar *string, OutExpiresInVar *int) bool {
		return rawCallback(SourceVar.GoPointer(), CancellableVar.GoPointer(), OutAccessTokenVar, OutExpiresInVar)
	}
}

// OverrideGetOauth2AccessToken sets the "get_oauth2_access_token" callback function.
func (x *SourceClassGType) OverrideGetOauth2AccessToken(cb func(*Source, *gio.Cancellable, *gio.AsyncReadyCallback, uintptr)) {
	if cb == nil {
		x.xGetOauth2AccessToken = 0
	} else {
		x.xGetOauth2AccessToken = purego.NewCallback(func(SourceVarp uintptr, CancellableVarp uintptr, CallbackVarp uintptr, UserDataVarp uintptr) {
			cb(SourceNewFromInternalPtr(SourceVarp), gio.CancellableNewFromInternalPtr(CancellableVarp), (*gio.AsyncReadyCallback)(unsafe.Pointer(CallbackVarp)), UserDataVarp)
		})
	}
}

// GetGetOauth2AccessToken gets the "get_oauth2_access_token" callback function.
func (x *SourceClassGType) GetGetOauth2AccessToken() func(*Source, *gio.Cancellable, *gio.AsyncReadyCallback, uintptr) {
	if x.xGetOauth2AccessToken == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, CancellableVarp uintptr, CallbackVarp uintptr, UserDataVarp uintptr)
	purego.RegisterFunc(&rawCallback, x.xGetOauth2AccessToken)
	return func(SourceVar *Source, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {
		rawCallback(SourceVar.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)
	}
}

// OverrideGetOauth2AccessTokenFinish sets the "get_oauth2_access_token_finish" callback function.
func (x *SourceClassGType) OverrideGetOauth2AccessTokenFinish(cb func(*Source, gio.AsyncResult, *string, *int) bool) {
	if cb == nil {
		x.xGetOauth2AccessTokenFinish = 0
	} else {
		x.xGetOauth2AccessTokenFinish = purego.NewCallback(func(SourceVarp uintptr, ResultVarp uintptr, OutAccessTokenVarp *string, OutExpiresInVarp *int) bool {
			return cb(SourceNewFromInternalPtr(SourceVarp), &gio.AsyncResultBase{Ptr: ResultVarp}, OutAccessTokenVarp, OutExpiresInVarp)
		})
	}
}

// GetGetOauth2AccessTokenFinish gets the "get_oauth2_access_token_finish" callback function.
func (x *SourceClassGType) GetGetOauth2AccessTokenFinish() func(*Source, gio.AsyncResult, *string, *int) bool {
	if x.xGetOauth2AccessTokenFinish == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, ResultVarp uintptr, OutAccessTokenVarp *string, OutExpiresInVarp *int) bool
	purego.RegisterFunc(&rawCallback, x.xGetOauth2AccessTokenFinish)
	return func(SourceVar *Source, ResultVar gio.AsyncResult, OutAccessTokenVar *string, OutExpiresInVar *int) bool {
		return rawCallback(SourceVar.GoPointer(), ResultVar.GoPointer(), OutAccessTokenVar, OutExpiresInVar)
	}
}

// OverrideInvokeCredentialsRequiredImpl sets the "invoke_credentials_required_impl" callback function.
func (x *SourceClassGType) OverrideInvokeCredentialsRequiredImpl(cb func(*Source, uintptr, string, string, string, string, string, *gio.Cancellable) bool) {
	if cb == nil {
		x.xInvokeCredentialsRequiredImpl = 0
	} else {
		x.xInvokeCredentialsRequiredImpl = purego.NewCallback(func(SourceVarp uintptr, DbusSourceVarp uintptr, ArgReasonVarp string, ArgCertificatePemVarp string, ArgCertificateErrorsVarp string, ArgDbusErrorNameVarp string, ArgDbusErrorMessageVarp string, CancellableVarp uintptr) bool {
			return cb(SourceNewFromInternalPtr(SourceVarp), DbusSourceVarp, ArgReasonVarp, ArgCertificatePemVarp, ArgCertificateErrorsVarp, ArgDbusErrorNameVarp, ArgDbusErrorMessageVarp, gio.CancellableNewFromInternalPtr(CancellableVarp))
		})
	}
}

// GetInvokeCredentialsRequiredImpl gets the "invoke_credentials_required_impl" callback function.
func (x *SourceClassGType) GetInvokeCredentialsRequiredImpl() func(*Source, uintptr, string, string, string, string, string, *gio.Cancellable) bool {
	if x.xInvokeCredentialsRequiredImpl == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, DbusSourceVarp uintptr, ArgReasonVarp string, ArgCertificatePemVarp string, ArgCertificateErrorsVarp string, ArgDbusErrorNameVarp string, ArgDbusErrorMessageVarp string, CancellableVarp uintptr) bool
	purego.RegisterFunc(&rawCallback, x.xInvokeCredentialsRequiredImpl)
	return func(SourceVar *Source, DbusSourceVar uintptr, ArgReasonVar string, ArgCertificatePemVar string, ArgCertificateErrorsVar string, ArgDbusErrorNameVar string, ArgDbusErrorMessageVar string, CancellableVar *gio.Cancellable) bool {
		return rawCallback(SourceVar.GoPointer(), DbusSourceVar, ArgReasonVar, ArgCertificatePemVar, ArgCertificateErrorsVar, ArgDbusErrorNameVar, ArgDbusErrorMessageVar, CancellableVar.GoPointer())
	}
}

// OverrideInvokeAuthenticateImpl sets the "invoke_authenticate_impl" callback function.
func (x *SourceClassGType) OverrideInvokeAuthenticateImpl(cb func(*Source, uintptr, string, *gio.Cancellable) bool) {
	if cb == nil {
		x.xInvokeAuthenticateImpl = 0
	} else {
		x.xInvokeAuthenticateImpl = purego.NewCallback(func(SourceVarp uintptr, DbusSourceVarp uintptr, ArgCredentialsVarp string, CancellableVarp uintptr) bool {
			return cb(SourceNewFromInternalPtr(SourceVarp), DbusSourceVarp, ArgCredentialsVarp, gio.CancellableNewFromInternalPtr(CancellableVarp))
		})
	}
}

// GetInvokeAuthenticateImpl gets the "invoke_authenticate_impl" callback function.
func (x *SourceClassGType) GetInvokeAuthenticateImpl() func(*Source, uintptr, string, *gio.Cancellable) bool {
	if x.xInvokeAuthenticateImpl == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, DbusSourceVarp uintptr, ArgCredentialsVarp string, CancellableVarp uintptr) bool
	purego.RegisterFunc(&rawCallback, x.xInvokeAuthenticateImpl)
	return func(SourceVar *Source, DbusSourceVar uintptr, ArgCredentialsVar string, CancellableVar *gio.Cancellable) bool {
		return rawCallback(SourceVar.GoPointer(), DbusSourceVar, ArgCredentialsVar, CancellableVar.GoPointer())
	}
}

// OverrideUnsetLastCredentialsRequiredArgumentsImpl sets the "unset_last_credentials_required_arguments_impl" callback function.
func (x *SourceClassGType) OverrideUnsetLastCredentialsRequiredArgumentsImpl(cb func(*Source, *gio.Cancellable) bool) {
	if cb == nil {
		x.xUnsetLastCredentialsRequiredArgumentsImpl = 0
	} else {
		x.xUnsetLastCredentialsRequiredArgumentsImpl = purego.NewCallback(func(SourceVarp uintptr, CancellableVarp uintptr) bool {
			return cb(SourceNewFromInternalPtr(SourceVarp), gio.CancellableNewFromInternalPtr(CancellableVarp))
		})
	}
}

// GetUnsetLastCredentialsRequiredArgumentsImpl gets the "unset_last_credentials_required_arguments_impl" callback function.
func (x *SourceClassGType) GetUnsetLastCredentialsRequiredArgumentsImpl() func(*Source, *gio.Cancellable) bool {
	if x.xUnsetLastCredentialsRequiredArgumentsImpl == 0 {
		return nil
	}
	var rawCallback func(SourceVarp uintptr, CancellableVarp uintptr) bool
	purego.RegisterFunc(&rawCallback, x.xUnsetLastCredentialsRequiredArgumentsImpl)
	return func(SourceVar *Source, CancellableVar *gio.Cancellable) bool {
		return rawCallback(SourceVar.GoPointer(), CancellableVar.GoPointer())
	}
}

type SourcePrivate struct {
	_ structs.HostLayout
}

func (x *SourcePrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

const (
	// A name of the named parameter used for passwords in credentials,
	// used to authenticate users with e_source_invoke_authenticate_sync()
	// and e_source_invoke_authenticate(). The named parameter is optional,
	// different authentication methods can use different names.
	SOURCE_CREDENTIAL_PASSWORD string = "password"
	// A name of the named parameter used for SSL/TLS trust in credentials,
	// used to authenticate users with e_source_invoke_authenticate_sync()
	// and e_source_invoke_authenticate(). The named parameter is optional.
	// Its value corresponds to current ESourceWebdav::ssl-trust property,
	// in case the ESource has that extension available. This is required
	// to have up-to-date data on the server side, when the client side
	// just saved the SSL trust change, which might not be propagated
	// into the server (factory) side quickly enough. The key is added into
	// the credentials in e_source_invoke_authenticate() automatically, if the
	// corresponding ESource contain a WebDAV extension and the key
	// is not part of the credentials already.
	SOURCE_CREDENTIAL_SSL_TRUST string = "ssl-trust"
	// A name of the named parameter used for usernames in credentials,
	// used to authenticate users with e_source_invoke_authenticate_sync()
	// and e_source_invoke_authenticate(). The named parameter is optional,
	// different authentication methods can use different names.
	SOURCE_CREDENTIAL_USERNAME string = "username"
	// Extends #GParamFlags to indicate the #GObject property is associated
	// with a key file value.  Use this flag when installing #GObject properties
	// in #ESourceExtension subclasses.
	SOURCE_PARAM_SETTING int = 1
)

// Contains only private data that should be read and manipulated using the
// functions below.
type Source struct {
	gobject.Object
}

var xSourceGLibType func() types.GType

func SourceGLibType() types.GType {
	return xSourceGLibType()
}

func SourceNewFromInternalPtr(ptr uintptr) *Source {
	cls := &Source{}
	cls.Ptr = ptr
	return cls
}

var xNewSource func(uintptr, *glib.MainContext, **glib.Error) uintptr

// Creates a new #ESource instance.
//
// The #ESource::changed signal will be emitted from @main_context if given,
// or else from the thread-default #GMainContext at the time this function is
// called.
//
// The only time the function should be called outside of #ESourceRegistry
// is to create a so-called "scratch" #ESource for editing in a Properties
// window or an account setup assistant.
//
// FIXME: Elaborate on scratch sources.
func NewSource(DbusObjectVar gio.DBusObject, MainContextVar *glib.MainContext) (*Source, error) {
	var cls *Source
	var cerr *glib.Error

	cret := xNewSource(DbusObjectVar.GoPointer(), MainContextVar, &cerr)

	if cret == 0 {
		return nil, cerr
	}
	cls = &Source{}
	cls.Ptr = cret
	if cerr == nil {
		return cls, nil
	}
	return cls, cerr

}

var xNewSourceWithUid func(string, *glib.MainContext, **glib.Error) uintptr

// Creates a new "scratch" #ESource with a predetermined unique identifier.
//
// The #ESource::changed signal will be emitted from @main_context if given,
// or else from the thread-default #GMainContext at the time this function is
// called.
func NewSourceWithUid(UidVar string, MainContextVar *glib.MainContext) (*Source, error) {
	var cls *Source
	var cerr *glib.Error

	cret := xNewSourceWithUid(UidVar, MainContextVar, &cerr)

	if cret == 0 {
		return nil, cerr
	}
	cls = &Source{}
	cls.Ptr = cret
	if cerr == nil {
		return cls, nil
	}
	return cls, cerr

}

var xSourceCamelConfigureService func(uintptr, uintptr)

// This function essentially glues together @source and @serivce so their
// configuration settings stay synchronized.  The glue itself is a shared
// #CamelSettings instance.
//
// Call this function immediately after creating a new #CamelService with
// camel_session_add_service().
func (x *Source) CamelConfigureService(ServiceVar *camel.Service) {

	xSourceCamelConfigureService(x.GoPointer(), ServiceVar.GoPointer())

}

var xSourceChanged func(uintptr)

// Emits the #ESource::changed signal from an idle callback in
// @source's #ESource:main-context.
//
// This function is primarily intended for use by #ESourceExtension
// when emitting a #GObject::notify signal on one of its properties.
func (x *Source) Changed() {

	xSourceChanged(x.GoPointer())

}

var xSourceCompareByDisplayName func(uintptr, uintptr) int

// Compares two #ESource instances by their display names.  Useful for
// ordering sources in a user interface.
func (x *Source) CompareByDisplayName(Source2Var *Source) int {

	cret := xSourceCompareByDisplayName(x.GoPointer(), Source2Var.GoPointer())
	return cret
}

var xSourceDeletePassword func(uintptr, uintptr, uintptr, uintptr)

// Asynchronously deletes the password for @source from either the default
// keyring or session keyring.  This operation does not rely on the registry
// service and therefore works for any #ESource -- registered or "scratch".
//
// When the operation is finished, @callback will be called.  You can then
// call e_source_delete_password_finish() to get the result of the operation.
func (x *Source) DeletePassword(CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xSourceDeletePassword(x.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)

}

var xSourceDeletePasswordFinish func(uintptr, uintptr, **glib.Error) bool

// Finishes the operation started with e_source_delete_password().
//
// Note the boolean return value indicates whether the delete operation
// itself completed successfully, not whether a password was found and
// deleted.  If no password was found, the function will still return
// %TRUE.  If an error occurs, the function sets @error and returns %FALSE.
func (x *Source) DeletePasswordFinish(ResultVar gio.AsyncResult) (bool, error) {
	var cerr *glib.Error

	cret := xSourceDeletePasswordFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceDeletePasswordSync func(uintptr, uintptr, **glib.Error) bool

// Deletes the password for @source from either the default keyring or
// session keyring.  This operation does not rely on the registry service
// and therefore works for any #ESource -- registered or "scratch".
//
// Note the boolean return value indicates whether the delete operation
// itself completed successfully, not whether a password was found and
// deleted.  If no password was found, the function will still return
// %TRUE.  If an error occurs, the function sets @error and returns %FALSE.
func (x *Source) DeletePasswordSync(CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xSourceDeletePasswordSync(x.GoPointer(), CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceDupDisplayName func(uintptr) string

// Thread-safe variation of e_source_get_display_name().
// Use this function when accessing @source from multiple threads.
//
// The returned string should be freed with g_free() when no longer needed.
func (x *Source) DupDisplayName() string {

	cret := xSourceDupDisplayName(x.GoPointer())
	return cret
}

var xSourceDupParent func(uintptr) string

// Thread-safe variation of e_source_get_parent().
// Use this function when accessing @source from multiple threads.
//
// The returned string should be freed with g_free() when no longer needed.
func (x *Source) DupParent() string {

	cret := xSourceDupParent(x.GoPointer())
	return cret
}

var xSourceDupSecretLabel func(uintptr) string

// Creates a label string based on @source's #ESource:display-name for use
// with #SecretItem.
func (x *Source) DupSecretLabel() string {

	cret := xSourceDupSecretLabel(x.GoPointer())
	return cret
}

var xSourceDupUid func(uintptr) string

// Thread-safe variation of e_source_get_uid().
// Use this function when accessing @source from multiple threads.
//
// The returned string should be freed with g_free() when no longer needed.
func (x *Source) DupUid() string {

	cret := xSourceDupUid(x.GoPointer())
	return cret
}

var xSourceEmitCredentialsRequired func(uintptr, SourceCredentialsReason, string, gio.TlsCertificateFlags, *glib.Error)

// Emits locally (in this process only) the ESource::credentials-required
// signal with given parameters. That's the difference with e_source_invoke_credentials_required(),
// which calls the signal globally, within each client.
func (x *Source) EmitCredentialsRequired(ReasonVar SourceCredentialsReason, CertificatePemVar string, CertificateErrorsVar gio.TlsCertificateFlags, OpErrorVar *glib.Error) {

	xSourceEmitCredentialsRequired(x.GoPointer(), ReasonVar, CertificatePemVar, CertificateErrorsVar, OpErrorVar)

}

var xSourceEqual func(uintptr, uintptr) bool

// Checks two #ESource instances for equality.  #ESource instances are
// equal if their unique identifier strings are equal.
func (x *Source) Equal(Source2Var *Source) bool {

	cret := xSourceEqual(x.GoPointer(), Source2Var.GoPointer())
	return cret
}

var xSourceGetConnectionStatus func(uintptr) SourceConnectionStatus

// Obtain current connection status of the @source.
func (x *Source) GetConnectionStatus() SourceConnectionStatus {

	cret := xSourceGetConnectionStatus(x.GoPointer())
	return cret
}

var xSourceGetDisplayName func(uintptr) string

// Returns the display name for @source.  Use the display name to
// represent the #ESource in a user interface.
func (x *Source) GetDisplayName() string {

	cret := xSourceGetDisplayName(x.GoPointer())
	return cret
}

var xSourceGetEnabled func(uintptr) bool

// Returns %TRUE if @source is enabled.
//
// An application should try to honor this setting if at all possible,
// even if it does not provide a way to change the setting through its
// user interface.  Disabled data sources should generally be hidden.
//
// &lt;note&gt;&lt;para&gt;
//
//	This function does not take into account @source's ancestors in the
//	#ESource hierarchy, each of which have their own enabled state.  If
//	any of @source's ancestors are disabled, then @source itself should
//	be treated as disabled.  Use e_source_registry_check_enabled() to
//	easily check for this.
//
// &lt;/para&gt;&lt;/note&gt;
func (x *Source) GetEnabled() bool {

	cret := xSourceGetEnabled(x.GoPointer())
	return cret
}

var xSourceGetExtension func(uintptr, string) uintptr

// Returns an instance of some #ESourceExtension subclass which registered
// itself under @extension_name.  If no such instance exists within @source,
// one will be created.  It is the caller's responsibility to know which
// subclass is being returned.
//
// If you just want to test for the existence of an extension within @source
// without creating it, use e_source_has_extension().
//
// Extension instances are owned by their #ESource and should not be
// referenced directly.  Instead, reference the #ESource instance and
// use this function to fetch the extension instance as needed.
func (x *Source) GetExtension(ExtensionNameVar string) *SourceExtension {
	var cls *SourceExtension

	cret := xSourceGetExtension(x.GoPointer(), ExtensionNameVar)

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &SourceExtension{}
	cls.Ptr = cret
	return cls
}

var xSourceGetLastCredentialsRequiredArguments func(uintptr, uintptr, uintptr, uintptr)

// Asynchronously calls the GetLastCredentialsRequiredArguments method
// on the server side, to get the last values used for the 'credentials-required'
// signal. See e_source_get_last_credentials_required_arguments_sync() for
// more information.
//
// When the operation is finished, @callback will be called. You can then
// call e_source_get_last_credentials_required_arguments_finish() to get
// the result of the operation.
func (x *Source) GetLastCredentialsRequiredArguments(CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xSourceGetLastCredentialsRequiredArguments(x.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)

}

var xSourceGetLastCredentialsRequiredArgumentsFinish func(uintptr, uintptr, *SourceCredentialsReason, *string, *gio.TlsCertificateFlags, **glib.Error, **glib.Error) bool

// Finishes the operation started with e_source_get_last_credentials_required_arguments().
// See e_source_get_last_credentials_required_arguments_sync() for more information
// about the output arguments.
//
// If an error occurs, the function sets @error and returns %FALSE.
func (x *Source) GetLastCredentialsRequiredArgumentsFinish(ResultVar gio.AsyncResult, OutReasonVar *SourceCredentialsReason, OutCertificatePemVar *string, OutCertificateErrorsVar *gio.TlsCertificateFlags, OutOpErrorVar **glib.Error) (bool, error) {
	var cerr *glib.Error

	cret := xSourceGetLastCredentialsRequiredArgumentsFinish(x.GoPointer(), ResultVar.GoPointer(), OutReasonVar, OutCertificatePemVar, OutCertificateErrorsVar, OutOpErrorVar, &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceGetLastCredentialsRequiredArgumentsSync func(uintptr, *SourceCredentialsReason, *string, *gio.TlsCertificateFlags, **glib.Error, uintptr, **glib.Error) bool

// Retrieves the last used arguments of the 'credentials-required' signal emission.
// If there was none emitted yet, or a corresponding 'authenitcate' had been emitted
// already, then the @out_reason is set to #E_SOURCE_CREDENTIALS_REASON_UNKNOWN
// and the value of other 'out' arguments is set to no values.
//
// If an error occurs, the function sets @error and returns %FALSE. The result gchar
// values should be freed with g_free() when no longer needed.
func (x *Source) GetLastCredentialsRequiredArgumentsSync(OutReasonVar *SourceCredentialsReason, OutCertificatePemVar *string, OutCertificateErrorsVar *gio.TlsCertificateFlags, OutOpErrorVar **glib.Error, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xSourceGetLastCredentialsRequiredArgumentsSync(x.GoPointer(), OutReasonVar, OutCertificatePemVar, OutCertificateErrorsVar, OutOpErrorVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceGetOauth2AccessToken func(uintptr, uintptr, uintptr, uintptr)

// Asynchronously obtains the OAuth 2.0 access token for @source along
// with its expiry in seconds from the current time (or 0 if unknown).
//
// When the operation is finished, @callback will be called.  You can then
// call e_source_get_oauth2_access_token_finish() to get the result of the
// operation.
func (x *Source) GetOauth2AccessToken(CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xSourceGetOauth2AccessToken(x.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)

}

var xSourceGetOauth2AccessTokenFinish func(uintptr, uintptr, *string, *int, **glib.Error) bool

// Finishes the operation started with e_source_get_oauth2_access_token().
//
// Free the returned access token with g_free() when finished with it.
// If an error occurred, the function will set @error and return %FALSE.
func (x *Source) GetOauth2AccessTokenFinish(ResultVar gio.AsyncResult, OutAccessTokenVar *string, OutExpiresInVar *int) (bool, error) {
	var cerr *glib.Error

	cret := xSourceGetOauth2AccessTokenFinish(x.GoPointer(), ResultVar.GoPointer(), OutAccessTokenVar, OutExpiresInVar, &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceGetOauth2AccessTokenSync func(uintptr, uintptr, *string, *int, **glib.Error) bool

// Obtains the OAuth 2.0 access token for @source along with its expiry
// in seconds from the current time (or 0 if unknown).
//
// Free the returned access token with g_free() when finished with it.
// If an error occurs, the function will set @error and return %FALSE.
func (x *Source) GetOauth2AccessTokenSync(CancellableVar *gio.Cancellable, OutAccessTokenVar *string, OutExpiresInVar *int) (bool, error) {
	var cerr *glib.Error

	cret := xSourceGetOauth2AccessTokenSync(x.GoPointer(), CancellableVar.GoPointer(), OutAccessTokenVar, OutExpiresInVar, &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceGetParent func(uintptr) string

// Returns the unique identifier string of the parent #ESource.
func (x *Source) GetParent() string {

	cret := xSourceGetParent(x.GoPointer())
	return cret
}

var xSourceGetRemoteCreatable func(uintptr) bool

// Returns whether new resources can be created on a remote server by
// calling e_source_remote_create() on @source.
//
// Generally this is only %TRUE if @source has an #ESourceCollection
// extension, which means there is an #ECollectionBackend in the D-Bus
// service that can handle create requests.  If @source does not have
// this capability, calls to e_source_remote_create() will fail.
func (x *Source) GetRemoteCreatable() bool {

	cret := xSourceGetRemoteCreatable(x.GoPointer())
	return cret
}

var xSourceGetRemoteDeletable func(uintptr) bool

// Returns whether the resource represented by @source can be deleted
// from a remote server by calling e_source_remote_delete().
//
// Generally this is only %TRUE if @source is a child of an #ESource
// which has an #ESourceCollection extension, which means there is an
// #ECollectionBackend in the D-Bus service that can handle delete
// requests.  If @source does not have this capability, calls to
// e_source_remote_delete() will fail.
func (x *Source) GetRemoteDeletable() bool {

	cret := xSourceGetRemoteDeletable(x.GoPointer())
	return cret
}

var xSourceGetRemovable func(uintptr) bool

// Returns whether the D-Bus service will allow @source to be removed.
// If @source is not writable, calls to e_source_remove() will fail.
func (x *Source) GetRemovable() bool {

	cret := xSourceGetRemovable(x.GoPointer())
	return cret
}

var xSourceGetUid func(uintptr) string

// Returns the unique identifier string for @source.
func (x *Source) GetUid() string {

	cret := xSourceGetUid(x.GoPointer())
	return cret
}

var xSourceGetWritable func(uintptr) bool

// Returns whether the D-Bus service will accept changes to @source.
// If @source is not writable, calls to e_source_write() will fail.
func (x *Source) GetWritable() bool {

	cret := xSourceGetWritable(x.GoPointer())
	return cret
}

var xSourceHasExtension func(uintptr, string) bool

// Checks whether @source has an #ESourceExtension with the given name.
func (x *Source) HasExtension(ExtensionNameVar string) bool {

	cret := xSourceHasExtension(x.GoPointer(), ExtensionNameVar)
	return cret
}

var xSourceHash func(uintptr) uint

// Generates a hash value for @source.  This function is intended for
// easily hashing an #ESource to add to a #GHashTable or similar data
// structure.
func (x *Source) Hash() uint {

	cret := xSourceHash(x.GoPointer())
	return cret
}

var xSourceInvokeAuthenticate func(uintptr, *NamedParameters, uintptr, uintptr, uintptr)

// Asynchronously calls the InvokeAuthenticate method on the server side,
// thus the backend knows what credentials to use to connect to its (possibly
// remote) data store.
//
// When the operation is finished, @callback will be called. You can then
// call e_source_invoke_authenticate_finish() to get the result of the operation.
func (x *Source) InvokeAuthenticate(CredentialsVar *NamedParameters, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xSourceInvokeAuthenticate(x.GoPointer(), CredentialsVar, CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)

}

var xSourceInvokeAuthenticateFinish func(uintptr, uintptr, **glib.Error) bool

// Finishes the operation started with e_source_invoke_authenticate().
//
// If an error occurs, the function sets @error and returns %FALSE.
func (x *Source) InvokeAuthenticateFinish(ResultVar gio.AsyncResult) (bool, error) {
	var cerr *glib.Error

	cret := xSourceInvokeAuthenticateFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceInvokeAuthenticateSync func(uintptr, *NamedParameters, uintptr, **glib.Error) bool

// Calls the InvokeAuthenticate method on the server side, thus the backend
// knows what credentials to use to connect to its (possibly remote) data store.
//
// If an error occurs, the function sets @error and returns %FALSE.
func (x *Source) InvokeAuthenticateSync(CredentialsVar *NamedParameters, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xSourceInvokeAuthenticateSync(x.GoPointer(), CredentialsVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceInvokeCredentialsRequired func(uintptr, SourceCredentialsReason, string, gio.TlsCertificateFlags, *glib.Error, uintptr, uintptr, uintptr)

// Asynchronously calls the InvokeCredentialsRequired method on the server side,
// to inform clients that credentials are required.
//
// When the operation is finished, @callback will be called. You can then
// call e_source_invoke_credentials_required_finish() to get the result of the operation.
func (x *Source) InvokeCredentialsRequired(ReasonVar SourceCredentialsReason, CertificatePemVar string, CertificateErrorsVar gio.TlsCertificateFlags, OpErrorVar *glib.Error, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xSourceInvokeCredentialsRequired(x.GoPointer(), ReasonVar, CertificatePemVar, CertificateErrorsVar, OpErrorVar, CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)

}

var xSourceInvokeCredentialsRequiredFinish func(uintptr, uintptr, **glib.Error) bool

// Finishes the operation started with e_source_invoke_credentials_required().
//
// If an error occurs, the function sets @error and returns %FALSE.
func (x *Source) InvokeCredentialsRequiredFinish(ResultVar gio.AsyncResult) (bool, error) {
	var cerr *glib.Error

	cret := xSourceInvokeCredentialsRequiredFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceInvokeCredentialsRequiredSync func(uintptr, SourceCredentialsReason, string, gio.TlsCertificateFlags, *glib.Error, uintptr, **glib.Error) bool

// Let's the client-side know that credentials are required. The @reason defines which
// parameters are used. The client passed the credentials with an e_source_invoke_authenticate()
// call.
//
// The %E_SOURCE_CREDENTIALS_REASON_REQUIRED is used for the first credentials prompt,
// when the client can return credentials as stored from the previous success login.
//
// The %E_SOURCE_CREDENTIALS_REASON_REJECTED is used when the previously used credentials
// had been rejected by the server. That usually means that the user should be asked
// to provide/correct the credentials.
//
// The %E_SOURCE_CREDENTIALS_REASON_SSL_FAILED is used when a secured connection failed
// due to some server-side certificate issues.
//
// The %E_SOURCE_CREDENTIALS_REASON_ERROR is used when the server returned an error.
// It is not possible to connect to it at the moment usually.
//
// If an error occurs, the function sets @error and returns %FALSE.
func (x *Source) InvokeCredentialsRequiredSync(ReasonVar SourceCredentialsReason, CertificatePemVar string, CertificateErrorsVar gio.TlsCertificateFlags, OpErrorVar *glib.Error, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xSourceInvokeCredentialsRequiredSync(x.GoPointer(), ReasonVar, CertificatePemVar, CertificateErrorsVar, OpErrorVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceLookupPassword func(uintptr, uintptr, uintptr, uintptr)

// Asynchronously looks up a password for @source.  Both the default and
// session keyrings are queried.  This operation does not rely on the
// registry service and therefore works for any #ESource -- registered
// or "scratch".
//
// When the operation is finished, @callback will be called.  You can then
// call e_source_lookup_password_finish() to get the result of the operation.
func (x *Source) LookupPassword(CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xSourceLookupPassword(x.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)

}

var xSourceLookupPasswordFinish func(uintptr, uintptr, *string, **glib.Error) bool

// Finishes the operation started with e_source_lookup_password().
//
// Note the boolean return value indicates whether the lookup operation
// itself completed successfully, not whether a password was found.  If
// no password was found, the function will set @out_password to %NULL
// but still return %TRUE.  If an error occurs, the function sets @error
// and returns %FALSE.
func (x *Source) LookupPasswordFinish(ResultVar gio.AsyncResult, OutPasswordVar *string) (bool, error) {
	var cerr *glib.Error

	cret := xSourceLookupPasswordFinish(x.GoPointer(), ResultVar.GoPointer(), OutPasswordVar, &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceLookupPasswordSync func(uintptr, uintptr, *string, **glib.Error) bool

// Looks up a password for @source.  Both the default and session keyrings
// are queried.  This operation does not rely on the registry service and
// therefore works for any #ESource -- registered or "scratch".
//
// Note the boolean return value indicates whether the lookup operation
// itself completed successfully, not whether a password was found.  If
// no password was found, the function will set @out_password to %NULL
// but still return %TRUE.  If an error occurs, the function sets @error
// and returns %FALSE.
func (x *Source) LookupPasswordSync(CancellableVar *gio.Cancellable, OutPasswordVar *string) (bool, error) {
	var cerr *glib.Error

	cret := xSourceLookupPasswordSync(x.GoPointer(), CancellableVar.GoPointer(), OutPasswordVar, &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceMailSignatureLoad func(uintptr, int, uintptr, uintptr, uintptr)

// Asynchronously loads a signature from the signature file for @source,
// which is given by e_source_mail_signature_get_file().
//
// If the signature file is executable, it will be executed and its output
// captured as the email signature content.  If the signature file is not
// executable, the email signature content is read directly from the file.
//
// When the operation is finished, @callback will be called.  You can
// then call e_source_mail_signature_load_finish() to get the result of
// the operation.
func (x *Source) MailSignatureLoad(IoPriorityVar int, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xSourceMailSignatureLoad(x.GoPointer(), IoPriorityVar, CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)

}

var xSourceMailSignatureLoadFinish func(uintptr, uintptr, *string, *uint, **glib.Error) bool

// Finishes an operation started with e_source_mail_signature_load().  The
// signature file contents are placed in @contents, and @length is set to
// the size of the @contents string.  The @contents string should be freed
// with g_free() when no longer needed.
func (x *Source) MailSignatureLoadFinish(ResultVar gio.AsyncResult, ContentsVar *string, LengthVar *uint) (bool, error) {
	var cerr *glib.Error

	cret := xSourceMailSignatureLoadFinish(x.GoPointer(), ResultVar.GoPointer(), ContentsVar, LengthVar, &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceMailSignatureLoadSync func(uintptr, *string, *uint, uintptr, **glib.Error) bool

// Loads a signature from the signature file for @source, which is
// given by e_source_mail_signature_get_file().  The signature contents
// are placed in @contents, and @length is set to the size of the @contents
// string.  The @contents string should be freed with g_free() when no
// longer needed.
//
// If the signature file is executable, it will be executed and its output
// captured as the email signature content.  If the signature file is not
// executable, the email signature content is read directly from the file.
func (x *Source) MailSignatureLoadSync(ContentsVar *string, LengthVar *uint, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xSourceMailSignatureLoadSync(x.GoPointer(), ContentsVar, LengthVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceMailSignatureReplace func(uintptr, string, uint, int, uintptr, uintptr, uintptr)

// Asynchrously replaces the signature file for @source with the given
// @contents of @length bytes.  The signature file for @source is given
// by e_source_mail_signature_get_file().
//
// When the operation is finished, @callback will be called.  You can
// then call e_source_mail_signature_replace_finish() to get the result
// of the operation.
func (x *Source) MailSignatureReplace(ContentsVar string, LengthVar uint, IoPriorityVar int, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xSourceMailSignatureReplace(x.GoPointer(), ContentsVar, LengthVar, IoPriorityVar, CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)

}

var xSourceMailSignatureReplaceFinish func(uintptr, uintptr, **glib.Error) bool

// Finishes an operation started with e_source_mail_signature_replace().
func (x *Source) MailSignatureReplaceFinish(ResultVar gio.AsyncResult) (bool, error) {
	var cerr *glib.Error

	cret := xSourceMailSignatureReplaceFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceMailSignatureReplaceSync func(uintptr, string, uint, uintptr, **glib.Error) bool

// Replaces the signature file for @source with the given @contents
// of @length bytes.  The signature file for @source is given by
// e_source_mail_signature_get_file().
func (x *Source) MailSignatureReplaceSync(ContentsVar string, LengthVar uint, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xSourceMailSignatureReplaceSync(x.GoPointer(), ContentsVar, LengthVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceMailSignatureSymlink func(uintptr, string, int, uintptr, uintptr, uintptr)

// Asynchronously replaces the signature file for @source with a symbolic
// link to @symlink_target, which should be an executable file that prints
// a mail signature to standard output.  The signature file for @source
// is given by e_source_mail_signature_get_file().
//
// When the operation is finished, @callback will be called.  You can
// then call e_source_mail_signature_symlink_finish() to get the result
// of the operation.
func (x *Source) MailSignatureSymlink(SymlinkTargetVar string, IoPriorityVar int, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xSourceMailSignatureSymlink(x.GoPointer(), SymlinkTargetVar, IoPriorityVar, CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)

}

var xSourceMailSignatureSymlinkFinish func(uintptr, uintptr, **glib.Error) bool

// Finishes an operation started with e_source_mail_signature_symlink().
func (x *Source) MailSignatureSymlinkFinish(ResultVar gio.AsyncResult) (bool, error) {
	var cerr *glib.Error

	cret := xSourceMailSignatureSymlinkFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceMailSignatureSymlinkSync func(uintptr, string, uintptr, **glib.Error) bool

// Replaces the signature file for @source with a symbolic link to
// @symlink_target, which should be an executable file that prints
// a mail signature to standard output.  The signature file for
// @source is given by e_source_mail_signature_get_file().
func (x *Source) MailSignatureSymlinkSync(SymlinkTargetVar string, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xSourceMailSignatureSymlinkSync(x.GoPointer(), SymlinkTargetVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceProxyLookup func(uintptr, string, uintptr, uintptr, uintptr)

// Asynchronously determines what proxy, if any, to use to connect to @uri.
// See e_source_proxy_lookup_sync() for more details.
//
// When the operation is finished, @callback will be called.  You can then
// call e_source_proxy_lookup_finish() to get the result of the operation.
func (x *Source) ProxyLookup(UriVar string, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xSourceProxyLookup(x.GoPointer(), UriVar, CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)

}

var xSourceProxyLookupFinish func(uintptr, uintptr, **glib.Error) []string

// Finishes the operation started with e_source_proxy_lookup().
//
// Free the returned proxy URIs with g_strfreev() when finished with them.
func (x *Source) ProxyLookupFinish(ResultVar gio.AsyncResult) ([]string, error) {
	var cerr *glib.Error

	cret := xSourceProxyLookupFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceProxyLookupSync func(uintptr, string, uintptr, **glib.Error) []string

// Looks into @source's #ESourceProxy extension to determine what proxy,
// if any, to use to connect to @uri.  The returned proxy URIs are of the
// same form described by g_proxy_resolver_lookup().
//
// The proxy extension's #ESourceProxy:method controls how proxy URIs are
// determined:
//
// When using @E_PROXY_METHOD_DEFAULT, the function will defer to the
// #GProxyResolver returned by g_proxy_resolver_get_default().
//
// When using @E_PROXY_METHOD_MANUAL, the function will configure a
// #GSimpleProxyResolver from the HTTP, HTTPS, FTP and SOCKS properties,
// as well as #ESourceProxy:ignore-hosts.
//
// When using @E_PROXY_METHOD_AUTO, the function will execute a proxy
// auto-config (PAC) file at #ESourceProxy:autoconfig-url.
//
// When using @E_PROXY_METHOD_NONE, the function will only return
// &lt;literal&gt;direct://&lt;/literal&gt;.
//
// If @source does not have an #ESourceProxy extension, the function sets
// @error to @G_IO_ERROR_NOT_SUPPORTED and returns %NULL.
//
// Free the returned proxy URIs with g_strfreev() when finished with them.
func (x *Source) ProxyLookupSync(UriVar string, CancellableVar *gio.Cancellable) ([]string, error) {
	var cerr *glib.Error

	cret := xSourceProxyLookupSync(x.GoPointer(), UriVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceRefDbusObject func(uintptr) uintptr

// Returns the #GDBusObject that was passed to e_source_new().
//
// The returned #GDBusObject is referenced for thread-safety and must be
// unreferenced with g_object_unref() when finished with it.
func (x *Source) RefDbusObject() *gio.DBusObjectBase {
	var cls *gio.DBusObjectBase

	cret := xSourceRefDbusObject(x.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &gio.DBusObjectBase{}
	cls.Ptr = cret
	return cls
}

var xSourceRefMainContext func(uintptr) *glib.MainContext

// Returns the #GMainContext on which event sources for @source are to
// be attached.
//
// The returned #GMainContext is referenced for thread-safety and must be
// unreferenced with g_main_context_unref() when finished with it.
func (x *Source) RefMainContext() *glib.MainContext {

	cret := xSourceRefMainContext(x.GoPointer())
	return cret
}

var xSourceRefreshAddTimeout func(uintptr, *glib.MainContext, uintptr, uintptr, uintptr) uint

// This is a simple way to schedule a periodic data source refresh.
//
// Adds a timeout #GSource to @context and handles all the bookkeeping
// if @source's refresh #ESourceRefresh:enabled state or its refresh
// #ESourceRefresh:interval-minutes value changes.  The @callback is
// expected to dispatch an asynchronous job to connect to and fetch
// updates from a remote server.
//
// The returned ID can be passed to e_source_refresh_remove_timeout() to
// remove the timeout from @context.  Note the ID is a private handle and
// cannot be passed to g_source_remove().
func (x *Source) RefreshAddTimeout(ContextVar *glib.MainContext, CallbackVar *SourceRefreshFunc, UserDataVar uintptr, NotifyVar *glib.DestroyNotify) uint {

	cret := xSourceRefreshAddTimeout(x.GoPointer(), ContextVar, glib.NewCallback(CallbackVar), UserDataVar, glib.NewCallbackNullable(NotifyVar))
	return cret
}

var xSourceRefreshForceTimeout func(uintptr)

// For all timeouts added with e_source_refresh_add_timeout(), invokes
// the #ESourceRefreshFunc callback immediately and then, if the refresh
// #ESourceRefresh:enabled state is TRUE, reschedules the timeout.
//
// This function is called automatically when the #ESource switches from
// disabled to enabled, but can also be useful when a network connection
// becomes available or when waking up from hibernation or suspend.
func (x *Source) RefreshForceTimeout() {

	xSourceRefreshForceTimeout(x.GoPointer())

}

var xSourceRefreshRemoveTimeout func(uintptr, uint) bool

// Removes a timeout #GSource added by e_source_refresh_add_timeout().
func (x *Source) RefreshRemoveTimeout(RefreshTimeoutIdVar uint) bool {

	cret := xSourceRefreshRemoveTimeout(x.GoPointer(), RefreshTimeoutIdVar)
	return cret
}

var xSourceRefreshRemoveTimeoutsByData func(uintptr, uintptr) uint

// Removes all timeout #GSource's added by e_source_refresh_add_timeout()
// whose callback data pointer matches @user_data.
func (x *Source) RefreshRemoveTimeoutsByData(UserDataVar uintptr) uint {

	cret := xSourceRefreshRemoveTimeoutsByData(x.GoPointer(), UserDataVar)
	return cret
}

var xSourceRemoteCreate func(uintptr, uintptr, uintptr, uintptr, uintptr)

// Asynchronously creates a new remote resource by picking out relevant
// details from @scratch_source.  The @scratch_source must be an #ESource
// with no #GDBusObject.  The @source must be #ESource:remote-creatable.
//
// The details required to create the resource vary by #ECollectionBackend,
// but in most cases the @scratch_source need only define the resource type
// (address book, calendar, etc.), a display name for the resource, and
// possibly a server-side path or ID for the resource.
//
// When the operation is finished, @callback will be called.  You can then
// call e_source_remote_create_finish() to get the result of the operation.
func (x *Source) RemoteCreate(ScratchSourceVar *Source, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xSourceRemoteCreate(x.GoPointer(), ScratchSourceVar.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)

}

var xSourceRemoteCreateFinish func(uintptr, uintptr, **glib.Error) bool

// Finishes the operation started with e_source_remote_create().  If
// an error occurred, the function will set @error and return %FALSE.
func (x *Source) RemoteCreateFinish(ResultVar gio.AsyncResult) (bool, error) {
	var cerr *glib.Error

	cret := xSourceRemoteCreateFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceRemoteCreateSync func(uintptr, uintptr, uintptr, **glib.Error) bool

// Creates a new remote resource by picking out relevant details from
// @scratch_source.  The @scratch_source must be an #ESource with no
// #GDBusObject.  The @source must be #ESource:remote-creatable.
//
// The details required to create the resource vary by #ECollectionBackend,
// but in most cases the @scratch_source need only define the resource type
// (address book, calendar, etc.), a display name for the resource, and
// possibly a server-side path or ID for the resource.
//
// If an error occurs, the function will set @error and return %FALSE.
func (x *Source) RemoteCreateSync(ScratchSourceVar *Source, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xSourceRemoteCreateSync(x.GoPointer(), ScratchSourceVar.GoPointer(), CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceRemoteDelete func(uintptr, uintptr, uintptr, uintptr)

// Asynchronously deletes the resource represented by @source from a remote
// server.  The @source must be #ESource:remote-deletable.  This will also
// delete the key file for @source and broadcast its removal to all clients,
// similar to e_source_remove().
//
// When the operation is finished, @callback will be called.  You can then
// call e_source_remote_delete_finish() to get the result of the operation.
func (x *Source) RemoteDelete(CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xSourceRemoteDelete(x.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)

}

var xSourceRemoteDeleteFinish func(uintptr, uintptr, **glib.Error) bool

// Finishes the operation started with e_source_remote_delete().  If
// an error occurred, the function will set @error and return %FALSE.
func (x *Source) RemoteDeleteFinish(ResultVar gio.AsyncResult) (bool, error) {
	var cerr *glib.Error

	cret := xSourceRemoteDeleteFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceRemoteDeleteSync func(uintptr, uintptr, **glib.Error) bool

// Deletes the resource represented by @source from a remote server.
// The @source must be #ESource:remote-deletable.  This will also delete
// the key file for @source and broadcast its removal to all clients,
// similar to e_source_remove_sync().
//
// If an error occurs, the function will set @error and return %FALSE.
func (x *Source) RemoteDeleteSync(CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xSourceRemoteDeleteSync(x.GoPointer(), CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceRemove func(uintptr, uintptr, uintptr, uintptr)

// Asynchronously requests the D-Bus service to delete the key files for
// @source and all of its descendants and broadcast their removal to all
// clients.  The @source must be #ESource:removable.
//
// When the operation is finished, @callback will be called.  You can then
// call e_source_remove_finish() to get the result of the operation.
func (x *Source) Remove(CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xSourceRemove(x.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)

}

var xSourceRemoveFinish func(uintptr, uintptr, **glib.Error) bool

// Finishes the operation started with e_source_remove().  If an
// error occurred, the function will set @error and return %FALSE.
func (x *Source) RemoveFinish(ResultVar gio.AsyncResult) (bool, error) {
	var cerr *glib.Error

	cret := xSourceRemoveFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceRemoveSync func(uintptr, uintptr, **glib.Error) bool

// Requests the D-Bus service to delete the key files for @source and all of
// its descendants and broadcast their removal to all clients.  The @source
// must be #ESource:removable.
//
// If an error occurs, the functon will set @error and return %FALSE.
func (x *Source) RemoveSync(CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xSourceRemoveSync(x.GoPointer(), CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceSetConnectionStatus func(uintptr, SourceConnectionStatus)

// Set's current connection status of the @source.
func (x *Source) SetConnectionStatus(ConnectionStatusVar SourceConnectionStatus) {

	xSourceSetConnectionStatus(x.GoPointer(), ConnectionStatusVar)

}

var xSourceSetDisplayName func(uintptr, string)

// Sets the display name for @source.  The @display_name argument must be a
// valid UTF-8 string.  Use the display name to represent the #ESource in a
// user interface.
//
// The internal copy of @display_name is automatically stripped of leading
// and trailing whitespace.
func (x *Source) SetDisplayName(DisplayNameVar string) {

	xSourceSetDisplayName(x.GoPointer(), DisplayNameVar)

}

var xSourceSetEnabled func(uintptr, bool)

// Enables or disables @source.
//
// An application should try to honor this setting if at all possible,
// even if it does not provide a way to change the setting through its
// user interface.  Disabled data sources should generally be hidden.
func (x *Source) SetEnabled(EnabledVar bool) {

	xSourceSetEnabled(x.GoPointer(), EnabledVar)

}

var xSourceSetParent func(uintptr, string)

// Identifies the parent of @source by its unique identifier string.
// This can only be set prior to adding @source to an #ESourceRegistry.
//
// The internal copy of #ESource:parent is automatically stripped of leading
// and trailing whitespace.  If the resulting string is empty, %NULL is set
// instead.
func (x *Source) SetParent(ParentVar string) {

	xSourceSetParent(x.GoPointer(), ParentVar)

}

var xSourceStorePassword func(uintptr, string, bool, uintptr, uintptr, uintptr)

// Asynchronously stores a password for @source.  This operation does
// not rely on the registry service and therefore works for any #ESource
// -- registered or "scratch".
//
// If @permanently is %TRUE, the password is stored in the default keyring.
// Otherwise the password is stored in the memory-only session keyring.  If
// an error occurs, the function sets @error and returns %FALSE.
//
// When the operation is finished, @callback will be called.  You can then
// call e_source_store_password_finish() to get the result of the operation.
func (x *Source) StorePassword(PasswordVar string, PermanentlyVar bool, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xSourceStorePassword(x.GoPointer(), PasswordVar, PermanentlyVar, CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)

}

var xSourceStorePasswordFinish func(uintptr, uintptr, **glib.Error) bool

// Finishes the operation started with e_source_store_password().
func (x *Source) StorePasswordFinish(ResultVar gio.AsyncResult) (bool, error) {
	var cerr *glib.Error

	cret := xSourceStorePasswordFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceStorePasswordSync func(uintptr, string, bool, uintptr, **glib.Error) bool

// Stores a password for @source.  This operation does not rely on the
// registry service and therefore works for any #ESource -- registered
// or "scratch".
//
// If @permanently is %TRUE, the password is stored in the default keyring.
// Otherwise the password is stored in the memory-only session keyring.  If
// an error occurs, the function sets @error and returns %FALSE.
func (x *Source) StorePasswordSync(PasswordVar string, PermanentlyVar bool, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xSourceStorePasswordSync(x.GoPointer(), PasswordVar, PermanentlyVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceToString func(uintptr, *uint) string

// Outputs the current contents of @source as a key file string.
// Free the returned string with g_free().
func (x *Source) ToString(LengthVar *uint) string {

	cret := xSourceToString(x.GoPointer(), LengthVar)
	return cret
}

var xSourceUnsetLastCredentialsRequiredArguments func(uintptr, uintptr, uintptr, uintptr)

// Asynchronously calls the UnsetLastCredentialsRequiredArguments method
// on the server side, to unset the last values used for the 'credentials-required'
// signal.
//
// When the operation is finished, @callback will be called. You can then
// call e_source_unset_last_credentials_required_arguments_finish() to get
// the result of the operation.
func (x *Source) UnsetLastCredentialsRequiredArguments(CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xSourceUnsetLastCredentialsRequiredArguments(x.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)

}

var xSourceUnsetLastCredentialsRequiredArgumentsFinish func(uintptr, uintptr, **glib.Error) bool

// Finishes the operation started with e_source_unset_last_credentials_required_arguments().
//
// If an error occurs, the function sets @error and returns %FALSE.
func (x *Source) UnsetLastCredentialsRequiredArgumentsFinish(ResultVar gio.AsyncResult) (bool, error) {
	var cerr *glib.Error

	cret := xSourceUnsetLastCredentialsRequiredArgumentsFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceUnsetLastCredentialsRequiredArgumentsSync func(uintptr, uintptr, **glib.Error) bool

// Unsets the last used arguments of the 'credentials-required' signal emission.
//
// If an error occurs, the function sets @error and returns %FALSE.
func (x *Source) UnsetLastCredentialsRequiredArgumentsSync(CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xSourceUnsetLastCredentialsRequiredArgumentsSync(x.GoPointer(), CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceWrite func(uintptr, uintptr, uintptr, uintptr)

// Asynchronously submits the current contents of @source to the D-Bus
// service to be written to disk and broadcast to other clients.  The
// @source must be #ESource:writable.
//
// When the operation is finished, @callback will be called.  You can then
// call e_source_write_finish() to get the result of the operation.
func (x *Source) Write(CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xSourceWrite(x.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)

}

var xSourceWriteFinish func(uintptr, uintptr, **glib.Error) bool

// Finishes the operation started with e_source_write().  If an
// error occurred, the function will set @error and return %FALSE.
func (x *Source) WriteFinish(ResultVar gio.AsyncResult) (bool, error) {
	var cerr *glib.Error

	cret := xSourceWriteFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceWriteSync func(uintptr, uintptr, **glib.Error) bool

// Submits the current contents of @source to the D-Bus service to be
// written to disk and broadcast to other clients.  The @source must
// be #ESource:writable.
//
// If an error occurs, the functon will set @error and return %FALSE.
func (x *Source) WriteSync(CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xSourceWriteSync(x.GoPointer(), CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

func (c *Source) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *Source) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// SetPropertyDbusObject sets the "dbus-object" property.
// The D-Bus object for the data source
func (x *Source) SetPropertyDbusObject(value uintptr) {
	var v gobject.Value
	v.Init(gobject.TypePointerVal)
	v.SetPointer(value)
	x.SetProperty("dbus-object", &v)
}

// GetPropertyDbusObject gets the "dbus-object" property.
// The D-Bus object for the data source
func (x *Source) GetPropertyDbusObject() uintptr {
	var v gobject.Value
	x.GetProperty("dbus-object", &v)
	return v.GetPointer()
}

// SetPropertyDisplayName sets the "display-name" property.
// The human-readable name of the data source
func (x *Source) SetPropertyDisplayName(value string) {
	var v gobject.Value
	v.Init(gobject.TypeStringVal)
	v.SetString(value)
	x.SetProperty("display-name", &v)
}

// GetPropertyDisplayName gets the "display-name" property.
// The human-readable name of the data source
func (x *Source) GetPropertyDisplayName() string {
	var v gobject.Value
	x.GetProperty("display-name", &v)
	return v.GetString()
}

// SetPropertyEnabled sets the "enabled" property.
// Whether the data source is enabled
func (x *Source) SetPropertyEnabled(value bool) {
	var v gobject.Value
	v.Init(gobject.TypeBooleanVal)
	v.SetBoolean(value)
	x.SetProperty("enabled", &v)
}

// GetPropertyEnabled gets the "enabled" property.
// Whether the data source is enabled
func (x *Source) GetPropertyEnabled() bool {
	var v gobject.Value
	x.GetProperty("enabled", &v)
	return v.GetBoolean()
}

// SetPropertyMainContext sets the "main-context" property.
// The main loop context on which to attach event sources
func (x *Source) SetPropertyMainContext(value uintptr) {
	var v gobject.Value
	v.Init(gobject.TypePointerVal)
	v.SetPointer(value)
	x.SetProperty("main-context", &v)
}

// GetPropertyMainContext gets the "main-context" property.
// The main loop context on which to attach event sources
func (x *Source) GetPropertyMainContext() uintptr {
	var v gobject.Value
	x.GetProperty("main-context", &v)
	return v.GetPointer()
}

// SetPropertyParent sets the "parent" property.
// The unique identity of the parent data source
func (x *Source) SetPropertyParent(value string) {
	var v gobject.Value
	v.Init(gobject.TypeStringVal)
	v.SetString(value)
	x.SetProperty("parent", &v)
}

// GetPropertyParent gets the "parent" property.
// The unique identity of the parent data source
func (x *Source) GetPropertyParent() string {
	var v gobject.Value
	x.GetProperty("parent", &v)
	return v.GetString()
}

// GetPropertyRemoteCreatable gets the "remote-creatable" property.
// Whether the data source can create remote resources
func (x *Source) GetPropertyRemoteCreatable() bool {
	var v gobject.Value
	x.GetProperty("remote-creatable", &v)
	return v.GetBoolean()
}

// GetPropertyRemoteDeletable gets the "remote-deletable" property.
// Whether the data source can delete remote resources
func (x *Source) GetPropertyRemoteDeletable() bool {
	var v gobject.Value
	x.GetProperty("remote-deletable", &v)
	return v.GetBoolean()
}

// GetPropertyRemovable gets the "removable" property.
// Whether the data source is removable
func (x *Source) GetPropertyRemovable() bool {
	var v gobject.Value
	x.GetProperty("removable", &v)
	return v.GetBoolean()
}

// SetPropertyUid sets the "uid" property.
// The unique identity of the data source
func (x *Source) SetPropertyUid(value string) {
	var v gobject.Value
	v.Init(gobject.TypeStringVal)
	v.SetString(value)
	x.SetProperty("uid", &v)
}

// GetPropertyUid gets the "uid" property.
// The unique identity of the data source
func (x *Source) GetPropertyUid() string {
	var v gobject.Value
	x.GetProperty("uid", &v)
	return v.GetString()
}

// GetPropertyWritable gets the "writable" property.
// Whether the data source is writable
func (x *Source) GetPropertyWritable() bool {
	var v gobject.Value
	x.GetProperty("writable", &v)
	return v.GetBoolean()
}

// Let's the backend know provided credentials to use to login
// to (possibly remote) data store.
func (x *Source) ConnectAuthenticate(cb *func(Source, uintptr)) uint32 {
	cbPtr := uintptr(unsafe.Pointer(cb))
	if cbRefPtr, ok := glib.GetCallback(cbPtr); ok {
		return gobject.SignalConnect(x.GoPointer(), "authenticate", cbRefPtr)
	}

	fcb := func(clsPtr uintptr, CredentialsVarp uintptr) {
		fa := Source{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa, CredentialsVarp)

	}
	cbRefPtr := purego.NewCallback(fcb)
	glib.SaveCallback(cbPtr, cbRefPtr)
	return gobject.SignalConnect(x.GoPointer(), "authenticate", cbRefPtr)
}

// The ::changed signal is emitted when a property in @source or
// one of its extension objects changes.  A common use for this
// signal is to notify a #GtkTreeModel containing data collected
// from #ESource&lt;!-- --&gt;s that it needs to update a row.
func (x *Source) ConnectChanged(cb *func(Source)) uint32 {
	cbPtr := uintptr(unsafe.Pointer(cb))
	if cbRefPtr, ok := glib.GetCallback(cbPtr); ok {
		return gobject.SignalConnect(x.GoPointer(), "changed", cbRefPtr)
	}

	fcb := func(clsPtr uintptr) {
		fa := Source{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)

	}
	cbRefPtr := purego.NewCallback(fcb)
	glib.SaveCallback(cbPtr, cbRefPtr)
	return gobject.SignalConnect(x.GoPointer(), "changed", cbRefPtr)
}

// The ::credentials-required signal is emitted when the @source
// requires credentials to connect to (possibly remote)
// data store. The credentials can be passed to the backend using
// e_source_invoke_authenticate() function.
func (x *Source) ConnectCredentialsRequired(cb *func(Source, SourceCredentialsReason, string, gio.TlsCertificateFlags, uintptr)) uint32 {
	cbPtr := uintptr(unsafe.Pointer(cb))
	if cbRefPtr, ok := glib.GetCallback(cbPtr); ok {
		return gobject.SignalConnect(x.GoPointer(), "credentials-required", cbRefPtr)
	}

	fcb := func(clsPtr uintptr, ReasonVarp SourceCredentialsReason, CertificatePemVarp string, CertificateErrorsVarp gio.TlsCertificateFlags, ErrorVarp uintptr) {
		fa := Source{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa, ReasonVarp, CertificatePemVarp, CertificateErrorsVarp, ErrorVarp)

	}
	cbRefPtr := purego.NewCallback(fcb)
	glib.SaveCallback(cbPtr, cbRefPtr)
	return gobject.SignalConnect(x.GoPointer(), "credentials-required", cbRefPtr)
}

// Initializes the object implementing the interface.
//
// This method is intended for language bindings. If writing in C,
// g_initable_new() should typically be used instead.
//
// The object must be initialized before any real use after initial
// construction, either with this function or g_async_initable_init_async().
//
// Implementations may also support cancellation. If @cancellable is not %NULL,
// then initialization can be cancelled by triggering the cancellable object
// from another thread. If the operation was cancelled, the error
// %G_IO_ERROR_CANCELLED will be returned. If @cancellable is not %NULL and
// the object doesn't support cancellable initialization the error
// %G_IO_ERROR_NOT_SUPPORTED will be returned.
//
// If the object is not initialized, or initialization returns with an
// error, then all operations on the object except g_object_ref() and
// g_object_unref() are considered to be invalid, and have undefined
// behaviour. See the [description][iface@Gio.Initable#description] for more details.
//
// Callers should not assume that a class which implements #GInitable can be
// initialized multiple times, unless the class explicitly documents itself as
// supporting this. Generally, a class’ implementation of init() can assume
// (and assert) that it will only be called once. Previously, this documentation
// recommended all #GInitable implementations should be idempotent; that
// recommendation was relaxed in GLib 2.54.
//
// If a class explicitly supports being initialized multiple times, it is
// recommended that the method is idempotent: multiple calls with the same
// arguments should return the same results. Only the first call initializes
// the object; further calls return the result of the first call.
//
// One reason why a class might need to support idempotent initialization is if
// it is designed to be used via the singleton pattern, with a
// #GObjectClass.constructor that sometimes returns an existing instance.
// In this pattern, a caller would expect to be able to call g_initable_init()
// on the result of g_object_new(), regardless of whether it is in fact a new
// instance.
func (x *Source) Init(CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := gio.XGInitableInit(x.GoPointer(), CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

// Checks if @resolver can be used on this system. (This is used
// internally; g_proxy_resolver_get_default() will only return a proxy
// resolver that returns %TRUE for this method.)
func (x *Source) IsSupported() bool {

	cret := gio.XGProxyResolverIsSupported(x.GoPointer())
	return cret
}

// Looks into the system proxy configuration to determine what proxy,
// if any, to use to connect to @uri. The returned proxy URIs are of
// the form `&lt;protocol&gt;://[user[:password]@]host[:port]` or
// `direct://`, where `&lt;protocol&gt;` could be http, rtsp, socks
// or other proxying protocol.
//
// If you don't know what network protocol is being used on the
// socket, you should use `none` as the URI protocol.
// In this case, the resolver might still return a generic proxy type
// (such as SOCKS), but would not return protocol-specific proxy types
// (such as http).
//
// `direct://` is used when no proxy is needed.
// Direct connection should not be attempted unless it is part of the
// returned array of proxies.
func (x *Source) Lookup(UriVar string, CancellableVar *gio.Cancellable) ([]string, error) {
	var cerr *glib.Error

	cret := gio.XGProxyResolverLookup(x.GoPointer(), UriVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

// Asynchronous lookup of proxy. See g_proxy_resolver_lookup() for more
// details.
func (x *Source) LookupAsync(UriVar string, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	gio.XGProxyResolverLookupAsync(x.GoPointer(), UriVar, CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)

}

// Call this function to obtain the array of proxy URIs when
// g_proxy_resolver_lookup_async() is complete. See
// g_proxy_resolver_lookup() for more details.
func (x *Source) LookupFinish(ResultVar gio.AsyncResult) ([]string, error) {
	var cerr *glib.Error

	cret := gio.XGProxyResolverLookupFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceParameterToKey func(string) string

// Converts a #GParamSpec name (e.g. "foo-bar" or "foo_bar")
// to "CamelCase" for use as a #GKeyFile key (e.g. "FooBar").
//
// This function is made public only to aid in account migration.
// Applications should not need to use this.
func SourceParameterToKey(ParamNameVar string) string {

	cret := xSourceParameterToKey(ParamNameVar)
	return cret
}

func init() {
	core.SetPackageName("EDATASERVER", "libedataserver-1.2")
	core.SetSharedLibraries("EDATASERVER", []string{"libcamel-1.2.so.66", "libedataserver-1.2.so.27"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("EDATASERVER") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xSourceGLibType, libs, "e_source_get_type")

	core.PuregoSafeRegister(&xNewSource, libs, "e_source_new")
	core.PuregoSafeRegister(&xNewSourceWithUid, libs, "e_source_new_with_uid")

	core.PuregoSafeRegister(&xSourceCamelConfigureService, libs, "e_source_camel_configure_service")
	core.PuregoSafeRegister(&xSourceChanged, libs, "e_source_changed")
	core.PuregoSafeRegister(&xSourceCompareByDisplayName, libs, "e_source_compare_by_display_name")
	core.PuregoSafeRegister(&xSourceDeletePassword, libs, "e_source_delete_password")
	core.PuregoSafeRegister(&xSourceDeletePasswordFinish, libs, "e_source_delete_password_finish")
	core.PuregoSafeRegister(&xSourceDeletePasswordSync, libs, "e_source_delete_password_sync")
	core.PuregoSafeRegister(&xSourceDupDisplayName, libs, "e_source_dup_display_name")
	core.PuregoSafeRegister(&xSourceDupParent, libs, "e_source_dup_parent")
	core.PuregoSafeRegister(&xSourceDupSecretLabel, libs, "e_source_dup_secret_label")
	core.PuregoSafeRegister(&xSourceDupUid, libs, "e_source_dup_uid")
	core.PuregoSafeRegister(&xSourceEmitCredentialsRequired, libs, "e_source_emit_credentials_required")
	core.PuregoSafeRegister(&xSourceEqual, libs, "e_source_equal")
	core.PuregoSafeRegister(&xSourceGetConnectionStatus, libs, "e_source_get_connection_status")
	core.PuregoSafeRegister(&xSourceGetDisplayName, libs, "e_source_get_display_name")
	core.PuregoSafeRegister(&xSourceGetEnabled, libs, "e_source_get_enabled")
	core.PuregoSafeRegister(&xSourceGetExtension, libs, "e_source_get_extension")
	core.PuregoSafeRegister(&xSourceGetLastCredentialsRequiredArguments, libs, "e_source_get_last_credentials_required_arguments")
	core.PuregoSafeRegister(&xSourceGetLastCredentialsRequiredArgumentsFinish, libs, "e_source_get_last_credentials_required_arguments_finish")
	core.PuregoSafeRegister(&xSourceGetLastCredentialsRequiredArgumentsSync, libs, "e_source_get_last_credentials_required_arguments_sync")
	core.PuregoSafeRegister(&xSourceGetOauth2AccessToken, libs, "e_source_get_oauth2_access_token")
	core.PuregoSafeRegister(&xSourceGetOauth2AccessTokenFinish, libs, "e_source_get_oauth2_access_token_finish")
	core.PuregoSafeRegister(&xSourceGetOauth2AccessTokenSync, libs, "e_source_get_oauth2_access_token_sync")
	core.PuregoSafeRegister(&xSourceGetParent, libs, "e_source_get_parent")
	core.PuregoSafeRegister(&xSourceGetRemoteCreatable, libs, "e_source_get_remote_creatable")
	core.PuregoSafeRegister(&xSourceGetRemoteDeletable, libs, "e_source_get_remote_deletable")
	core.PuregoSafeRegister(&xSourceGetRemovable, libs, "e_source_get_removable")
	core.PuregoSafeRegister(&xSourceGetUid, libs, "e_source_get_uid")
	core.PuregoSafeRegister(&xSourceGetWritable, libs, "e_source_get_writable")
	core.PuregoSafeRegister(&xSourceHasExtension, libs, "e_source_has_extension")
	core.PuregoSafeRegister(&xSourceHash, libs, "e_source_hash")
	core.PuregoSafeRegister(&xSourceInvokeAuthenticate, libs, "e_source_invoke_authenticate")
	core.PuregoSafeRegister(&xSourceInvokeAuthenticateFinish, libs, "e_source_invoke_authenticate_finish")
	core.PuregoSafeRegister(&xSourceInvokeAuthenticateSync, libs, "e_source_invoke_authenticate_sync")
	core.PuregoSafeRegister(&xSourceInvokeCredentialsRequired, libs, "e_source_invoke_credentials_required")
	core.PuregoSafeRegister(&xSourceInvokeCredentialsRequiredFinish, libs, "e_source_invoke_credentials_required_finish")
	core.PuregoSafeRegister(&xSourceInvokeCredentialsRequiredSync, libs, "e_source_invoke_credentials_required_sync")
	core.PuregoSafeRegister(&xSourceLookupPassword, libs, "e_source_lookup_password")
	core.PuregoSafeRegister(&xSourceLookupPasswordFinish, libs, "e_source_lookup_password_finish")
	core.PuregoSafeRegister(&xSourceLookupPasswordSync, libs, "e_source_lookup_password_sync")
	core.PuregoSafeRegister(&xSourceMailSignatureLoad, libs, "e_source_mail_signature_load")
	core.PuregoSafeRegister(&xSourceMailSignatureLoadFinish, libs, "e_source_mail_signature_load_finish")
	core.PuregoSafeRegister(&xSourceMailSignatureLoadSync, libs, "e_source_mail_signature_load_sync")
	core.PuregoSafeRegister(&xSourceMailSignatureReplace, libs, "e_source_mail_signature_replace")
	core.PuregoSafeRegister(&xSourceMailSignatureReplaceFinish, libs, "e_source_mail_signature_replace_finish")
	core.PuregoSafeRegister(&xSourceMailSignatureReplaceSync, libs, "e_source_mail_signature_replace_sync")
	core.PuregoSafeRegister(&xSourceMailSignatureSymlink, libs, "e_source_mail_signature_symlink")
	core.PuregoSafeRegister(&xSourceMailSignatureSymlinkFinish, libs, "e_source_mail_signature_symlink_finish")
	core.PuregoSafeRegister(&xSourceMailSignatureSymlinkSync, libs, "e_source_mail_signature_symlink_sync")
	core.PuregoSafeRegister(&xSourceProxyLookup, libs, "e_source_proxy_lookup")
	core.PuregoSafeRegister(&xSourceProxyLookupFinish, libs, "e_source_proxy_lookup_finish")
	core.PuregoSafeRegister(&xSourceProxyLookupSync, libs, "e_source_proxy_lookup_sync")
	core.PuregoSafeRegister(&xSourceRefDbusObject, libs, "e_source_ref_dbus_object")
	core.PuregoSafeRegister(&xSourceRefMainContext, libs, "e_source_ref_main_context")
	core.PuregoSafeRegister(&xSourceRefreshAddTimeout, libs, "e_source_refresh_add_timeout")
	core.PuregoSafeRegister(&xSourceRefreshForceTimeout, libs, "e_source_refresh_force_timeout")
	core.PuregoSafeRegister(&xSourceRefreshRemoveTimeout, libs, "e_source_refresh_remove_timeout")
	core.PuregoSafeRegister(&xSourceRefreshRemoveTimeoutsByData, libs, "e_source_refresh_remove_timeouts_by_data")
	core.PuregoSafeRegister(&xSourceRemoteCreate, libs, "e_source_remote_create")
	core.PuregoSafeRegister(&xSourceRemoteCreateFinish, libs, "e_source_remote_create_finish")
	core.PuregoSafeRegister(&xSourceRemoteCreateSync, libs, "e_source_remote_create_sync")
	core.PuregoSafeRegister(&xSourceRemoteDelete, libs, "e_source_remote_delete")
	core.PuregoSafeRegister(&xSourceRemoteDeleteFinish, libs, "e_source_remote_delete_finish")
	core.PuregoSafeRegister(&xSourceRemoteDeleteSync, libs, "e_source_remote_delete_sync")
	core.PuregoSafeRegister(&xSourceRemove, libs, "e_source_remove")
	core.PuregoSafeRegister(&xSourceRemoveFinish, libs, "e_source_remove_finish")
	core.PuregoSafeRegister(&xSourceRemoveSync, libs, "e_source_remove_sync")
	core.PuregoSafeRegister(&xSourceSetConnectionStatus, libs, "e_source_set_connection_status")
	core.PuregoSafeRegister(&xSourceSetDisplayName, libs, "e_source_set_display_name")
	core.PuregoSafeRegister(&xSourceSetEnabled, libs, "e_source_set_enabled")
	core.PuregoSafeRegister(&xSourceSetParent, libs, "e_source_set_parent")
	core.PuregoSafeRegister(&xSourceStorePassword, libs, "e_source_store_password")
	core.PuregoSafeRegister(&xSourceStorePasswordFinish, libs, "e_source_store_password_finish")
	core.PuregoSafeRegister(&xSourceStorePasswordSync, libs, "e_source_store_password_sync")
	core.PuregoSafeRegister(&xSourceToString, libs, "e_source_to_string")
	core.PuregoSafeRegister(&xSourceUnsetLastCredentialsRequiredArguments, libs, "e_source_unset_last_credentials_required_arguments")
	core.PuregoSafeRegister(&xSourceUnsetLastCredentialsRequiredArgumentsFinish, libs, "e_source_unset_last_credentials_required_arguments_finish")
	core.PuregoSafeRegister(&xSourceUnsetLastCredentialsRequiredArgumentsSync, libs, "e_source_unset_last_credentials_required_arguments_sync")
	core.PuregoSafeRegister(&xSourceWrite, libs, "e_source_write")
	core.PuregoSafeRegister(&xSourceWriteFinish, libs, "e_source_write_finish")
	core.PuregoSafeRegister(&xSourceWriteSync, libs, "e_source_write_sync")

	core.PuregoSafeRegister(&xSourceParameterToKey, libs, "e_source_parameter_to_key")

}
