// Package edataserver was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package edataserver

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type SourceCalendarClassGType struct {
	_ structs.HostLayout

	ParentClass SourceSelectableClassGType
}

func (x *SourceCalendarClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type SourceCalendarPrivate struct {
	_ structs.HostLayout
}

func (x *SourceCalendarPrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

const (
	// Pass this extension name to e_source_get_extension() to access
	// #ESourceCalendar.  This is also used as a group name in key files.
	SOURCE_EXTENSION_CALENDAR string = "Calendar"
)

// Contains only private data that should be read and manipulated using the
// functions below.
type SourceCalendar struct {
	SourceSelectable
}

var xSourceCalendarGLibType func() types.GType

func SourceCalendarGLibType() types.GType {
	return xSourceCalendarGLibType()
}

func SourceCalendarNewFromInternalPtr(ptr uintptr) *SourceCalendar {
	cls := &SourceCalendar{}
	cls.Ptr = ptr
	return cls
}

func (c *SourceCalendar) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *SourceCalendar) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}
