// Package edataserver was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package edataserver

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type SourceRevisionGuardsClassGType struct {
	_ structs.HostLayout

	ParentClass SourceExtensionClassGType
}

func (x *SourceRevisionGuardsClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type SourceRevisionGuardsPrivate struct {
	_ structs.HostLayout
}

func (x *SourceRevisionGuardsPrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

const (
	// Pass this extension name to e_source_get_extension() to access
	// #ESourceRevisionGuards.  This is also used as a group name in key files.
	SOURCE_EXTENSION_REVISION_GUARDS string = "Revision Guards"
)

// Contains only private data that should be read and manipulated using the
// functions below.
type SourceRevisionGuards struct {
	SourceExtension
}

var xSourceRevisionGuardsGLibType func() types.GType

func SourceRevisionGuardsGLibType() types.GType {
	return xSourceRevisionGuardsGLibType()
}

func SourceRevisionGuardsNewFromInternalPtr(ptr uintptr) *SourceRevisionGuards {
	cls := &SourceRevisionGuards{}
	cls.Ptr = ptr
	return cls
}

var xSourceRevisionGuardsGetEnabled func(uintptr) bool

// Checks whether revision guards for the given #ESource are enabled.
func (x *SourceRevisionGuards) GetEnabled() bool {

	cret := xSourceRevisionGuardsGetEnabled(x.GoPointer())
	return cret
}

var xSourceRevisionGuardsSetEnabled func(uintptr, bool)

// Enables or disables the revision guards for a given #ESource.
//
// Revision guards are disabled by default.
func (x *SourceRevisionGuards) SetEnabled(EnabledVar bool) {

	xSourceRevisionGuardsSetEnabled(x.GoPointer(), EnabledVar)

}

func (c *SourceRevisionGuards) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *SourceRevisionGuards) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// SetPropertyEnabled sets the "enabled" property.
// Whether to enable or disable the revision guards
func (x *SourceRevisionGuards) SetPropertyEnabled(value bool) {
	var v gobject.Value
	v.Init(gobject.TypeBooleanVal)
	v.SetBoolean(value)
	x.SetProperty("enabled", &v)
}

// GetPropertyEnabled gets the "enabled" property.
// Whether to enable or disable the revision guards
func (x *SourceRevisionGuards) GetPropertyEnabled() bool {
	var v gobject.Value
	x.GetProperty("enabled", &v)
	return v.GetBoolean()
}

func init() {
	core.SetPackageName("EDATASERVER", "libedataserver-1.2")
	core.SetSharedLibraries("EDATASERVER", []string{"libcamel-1.2.so.66", "libedataserver-1.2.so.27"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("EDATASERVER") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xSourceRevisionGuardsGLibType, libs, "e_source_revision_guards_get_type")

	core.PuregoSafeRegister(&xSourceRevisionGuardsGetEnabled, libs, "e_source_revision_guards_get_enabled")
	core.PuregoSafeRegister(&xSourceRevisionGuardsSetEnabled, libs, "e_source_revision_guards_set_enabled")

}
