// Package edataserver was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package edataserver

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type SourceRefreshFunc func(uintptr, uintptr)

type SourceRefreshClassGType struct {
	_ structs.HostLayout

	ParentClass SourceExtensionClassGType
}

func (x *SourceRefreshClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type SourceRefreshPrivate struct {
	_ structs.HostLayout
}

func (x *SourceRefreshPrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

const (
	// Pass this extension name to e_source_get_extension() to access
	// #ESourceRefresh.  This is also used as a group name in key files.
	SOURCE_EXTENSION_REFRESH string = "Refresh"
)

// Contains only private data that should be read and manipulated using the
// functions below.
type SourceRefresh struct {
	SourceExtension
}

var xSourceRefreshGLibType func() types.GType

func SourceRefreshGLibType() types.GType {
	return xSourceRefreshGLibType()
}

func SourceRefreshNewFromInternalPtr(ptr uintptr) *SourceRefresh {
	cls := &SourceRefresh{}
	cls.Ptr = ptr
	return cls
}

var xSourceRefreshGetEnabled func(uintptr) bool

// Returns whether to periodically fetch updates from a remote server.
//
// The refresh interval is determined by the #ESourceRefresh:interval-minutes
// property.
func (x *SourceRefresh) GetEnabled() bool {

	cret := xSourceRefreshGetEnabled(x.GoPointer())
	return cret
}

var xSourceRefreshGetEnabledOnMeteredNetwork func(uintptr) bool

// Returns whether can refresh content on metered network.
//
// The @extension itself doesn't use this option, it's up to
// the @extension user to determine what kind of connection is used
// and then decide whether refresh, or other expensive network
// operations, can be done.
func (x *SourceRefresh) GetEnabledOnMeteredNetwork() bool {

	cret := xSourceRefreshGetEnabledOnMeteredNetwork(x.GoPointer())
	return cret
}

var xSourceRefreshGetIntervalMinutes func(uintptr) uint

// Returns the interval for fetching updates from a remote server.
//
// Note this value is only effective when the #ESourceRefresh:enabled
// property is %TRUE.
func (x *SourceRefresh) GetIntervalMinutes() uint {

	cret := xSourceRefreshGetIntervalMinutes(x.GoPointer())
	return cret
}

var xSourceRefreshSetEnabled func(uintptr, bool)

// Sets whether to periodically fetch updates from a remote server.
//
// The refresh interval is determined by the #ESourceRefresh:interval-minutes
// property.
func (x *SourceRefresh) SetEnabled(EnabledVar bool) {

	xSourceRefreshSetEnabled(x.GoPointer(), EnabledVar)

}

var xSourceRefreshSetEnabledOnMeteredNetwork func(uintptr, bool)

// Sets whether can refresh content on metered network.
//
// See e_source_refresh_get_enabled_on_metered_network() for more information
// about what it means.
func (x *SourceRefresh) SetEnabledOnMeteredNetwork(EnabledVar bool) {

	xSourceRefreshSetEnabledOnMeteredNetwork(x.GoPointer(), EnabledVar)

}

var xSourceRefreshSetIntervalMinutes func(uintptr, uint)

// Sets the interval for fetching updates from a remote server.
//
// Note this value is only effective when the #ESourceRefresh:enabled
// property is %TRUE.
func (x *SourceRefresh) SetIntervalMinutes(IntervalMinutesVar uint) {

	xSourceRefreshSetIntervalMinutes(x.GoPointer(), IntervalMinutesVar)

}

func (c *SourceRefresh) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *SourceRefresh) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// SetPropertyEnabled sets the "enabled" property.
// Whether to periodically refresh
func (x *SourceRefresh) SetPropertyEnabled(value bool) {
	var v gobject.Value
	v.Init(gobject.TypeBooleanVal)
	v.SetBoolean(value)
	x.SetProperty("enabled", &v)
}

// GetPropertyEnabled gets the "enabled" property.
// Whether to periodically refresh
func (x *SourceRefresh) GetPropertyEnabled() bool {
	var v gobject.Value
	x.GetProperty("enabled", &v)
	return v.GetBoolean()
}

// SetPropertyEnabledOnMeteredNetwork sets the "enabled-on-metered-network" property.
// Whether to enable refresh on metered network
func (x *SourceRefresh) SetPropertyEnabledOnMeteredNetwork(value bool) {
	var v gobject.Value
	v.Init(gobject.TypeBooleanVal)
	v.SetBoolean(value)
	x.SetProperty("enabled-on-metered-network", &v)
}

// GetPropertyEnabledOnMeteredNetwork gets the "enabled-on-metered-network" property.
// Whether to enable refresh on metered network
func (x *SourceRefresh) GetPropertyEnabledOnMeteredNetwork() bool {
	var v gobject.Value
	x.GetProperty("enabled-on-metered-network", &v)
	return v.GetBoolean()
}

// SetPropertyIntervalMinutes sets the "interval-minutes" property.
// Refresh interval in minutes
func (x *SourceRefresh) SetPropertyIntervalMinutes(value uint) {
	var v gobject.Value
	v.Init(gobject.TypeUintVal)
	v.SetUint(value)
	x.SetProperty("interval-minutes", &v)
}

// GetPropertyIntervalMinutes gets the "interval-minutes" property.
// Refresh interval in minutes
func (x *SourceRefresh) GetPropertyIntervalMinutes() uint {
	var v gobject.Value
	x.GetProperty("interval-minutes", &v)
	return v.GetUint()
}

func init() {
	core.SetPackageName("EDATASERVER", "libedataserver-1.2")
	core.SetSharedLibraries("EDATASERVER", []string{"libcamel-1.2.so.66", "libedataserver-1.2.so.27"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("EDATASERVER") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xSourceRefreshGLibType, libs, "e_source_refresh_get_type")

	core.PuregoSafeRegister(&xSourceRefreshGetEnabled, libs, "e_source_refresh_get_enabled")
	core.PuregoSafeRegister(&xSourceRefreshGetEnabledOnMeteredNetwork, libs, "e_source_refresh_get_enabled_on_metered_network")
	core.PuregoSafeRegister(&xSourceRefreshGetIntervalMinutes, libs, "e_source_refresh_get_interval_minutes")
	core.PuregoSafeRegister(&xSourceRefreshSetEnabled, libs, "e_source_refresh_set_enabled")
	core.PuregoSafeRegister(&xSourceRefreshSetEnabledOnMeteredNetwork, libs, "e_source_refresh_set_enabled_on_metered_network")
	core.PuregoSafeRegister(&xSourceRefreshSetIntervalMinutes, libs, "e_source_refresh_set_interval_minutes")

}
