// Package edataserver was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package edataserver

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gio"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type SourceCredentialsProviderImplClassGType struct {
	_ structs.HostLayout

	ParentClass ExtensionClassGType

	xCanProcess uintptr

	xCanStore uintptr

	xCanPrompt uintptr

	xLookupSync uintptr

	xStoreSync uintptr

	xDeleteSync uintptr
}

func (x *SourceCredentialsProviderImplClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// OverrideCanProcess sets the "can_process" callback function.
func (x *SourceCredentialsProviderImplClassGType) OverrideCanProcess(cb func(*SourceCredentialsProviderImpl, *Source) bool) {
	if cb == nil {
		x.xCanProcess = 0
	} else {
		x.xCanProcess = purego.NewCallback(func(ProviderImplVarp uintptr, SourceVarp uintptr) bool {
			return cb(SourceCredentialsProviderImplNewFromInternalPtr(ProviderImplVarp), SourceNewFromInternalPtr(SourceVarp))
		})
	}
}

// GetCanProcess gets the "can_process" callback function.
func (x *SourceCredentialsProviderImplClassGType) GetCanProcess() func(*SourceCredentialsProviderImpl, *Source) bool {
	if x.xCanProcess == 0 {
		return nil
	}
	var rawCallback func(ProviderImplVarp uintptr, SourceVarp uintptr) bool
	purego.RegisterFunc(&rawCallback, x.xCanProcess)
	return func(ProviderImplVar *SourceCredentialsProviderImpl, SourceVar *Source) bool {
		return rawCallback(ProviderImplVar.GoPointer(), SourceVar.GoPointer())
	}
}

// OverrideCanStore sets the "can_store" callback function.
func (x *SourceCredentialsProviderImplClassGType) OverrideCanStore(cb func(*SourceCredentialsProviderImpl) bool) {
	if cb == nil {
		x.xCanStore = 0
	} else {
		x.xCanStore = purego.NewCallback(func(ProviderImplVarp uintptr) bool {
			return cb(SourceCredentialsProviderImplNewFromInternalPtr(ProviderImplVarp))
		})
	}
}

// GetCanStore gets the "can_store" callback function.
func (x *SourceCredentialsProviderImplClassGType) GetCanStore() func(*SourceCredentialsProviderImpl) bool {
	if x.xCanStore == 0 {
		return nil
	}
	var rawCallback func(ProviderImplVarp uintptr) bool
	purego.RegisterFunc(&rawCallback, x.xCanStore)
	return func(ProviderImplVar *SourceCredentialsProviderImpl) bool {
		return rawCallback(ProviderImplVar.GoPointer())
	}
}

// OverrideCanPrompt sets the "can_prompt" callback function.
func (x *SourceCredentialsProviderImplClassGType) OverrideCanPrompt(cb func(*SourceCredentialsProviderImpl) bool) {
	if cb == nil {
		x.xCanPrompt = 0
	} else {
		x.xCanPrompt = purego.NewCallback(func(ProviderImplVarp uintptr) bool {
			return cb(SourceCredentialsProviderImplNewFromInternalPtr(ProviderImplVarp))
		})
	}
}

// GetCanPrompt gets the "can_prompt" callback function.
func (x *SourceCredentialsProviderImplClassGType) GetCanPrompt() func(*SourceCredentialsProviderImpl) bool {
	if x.xCanPrompt == 0 {
		return nil
	}
	var rawCallback func(ProviderImplVarp uintptr) bool
	purego.RegisterFunc(&rawCallback, x.xCanPrompt)
	return func(ProviderImplVar *SourceCredentialsProviderImpl) bool {
		return rawCallback(ProviderImplVar.GoPointer())
	}
}

// OverrideLookupSync sets the "lookup_sync" callback function.
func (x *SourceCredentialsProviderImplClassGType) OverrideLookupSync(cb func(*SourceCredentialsProviderImpl, *Source, *gio.Cancellable, **NamedParameters) bool) {
	if cb == nil {
		x.xLookupSync = 0
	} else {
		x.xLookupSync = purego.NewCallback(func(ProviderImplVarp uintptr, SourceVarp uintptr, CancellableVarp uintptr, OutCredentialsVarp **NamedParameters) bool {
			return cb(SourceCredentialsProviderImplNewFromInternalPtr(ProviderImplVarp), SourceNewFromInternalPtr(SourceVarp), gio.CancellableNewFromInternalPtr(CancellableVarp), OutCredentialsVarp)
		})
	}
}

// GetLookupSync gets the "lookup_sync" callback function.
func (x *SourceCredentialsProviderImplClassGType) GetLookupSync() func(*SourceCredentialsProviderImpl, *Source, *gio.Cancellable, **NamedParameters) bool {
	if x.xLookupSync == 0 {
		return nil
	}
	var rawCallback func(ProviderImplVarp uintptr, SourceVarp uintptr, CancellableVarp uintptr, OutCredentialsVarp **NamedParameters) bool
	purego.RegisterFunc(&rawCallback, x.xLookupSync)
	return func(ProviderImplVar *SourceCredentialsProviderImpl, SourceVar *Source, CancellableVar *gio.Cancellable, OutCredentialsVar **NamedParameters) bool {
		return rawCallback(ProviderImplVar.GoPointer(), SourceVar.GoPointer(), CancellableVar.GoPointer(), OutCredentialsVar)
	}
}

// OverrideStoreSync sets the "store_sync" callback function.
func (x *SourceCredentialsProviderImplClassGType) OverrideStoreSync(cb func(*SourceCredentialsProviderImpl, *Source, *NamedParameters, bool, *gio.Cancellable) bool) {
	if cb == nil {
		x.xStoreSync = 0
	} else {
		x.xStoreSync = purego.NewCallback(func(ProviderImplVarp uintptr, SourceVarp uintptr, CredentialsVarp *NamedParameters, PermanentlyVarp bool, CancellableVarp uintptr) bool {
			return cb(SourceCredentialsProviderImplNewFromInternalPtr(ProviderImplVarp), SourceNewFromInternalPtr(SourceVarp), CredentialsVarp, PermanentlyVarp, gio.CancellableNewFromInternalPtr(CancellableVarp))
		})
	}
}

// GetStoreSync gets the "store_sync" callback function.
func (x *SourceCredentialsProviderImplClassGType) GetStoreSync() func(*SourceCredentialsProviderImpl, *Source, *NamedParameters, bool, *gio.Cancellable) bool {
	if x.xStoreSync == 0 {
		return nil
	}
	var rawCallback func(ProviderImplVarp uintptr, SourceVarp uintptr, CredentialsVarp *NamedParameters, PermanentlyVarp bool, CancellableVarp uintptr) bool
	purego.RegisterFunc(&rawCallback, x.xStoreSync)
	return func(ProviderImplVar *SourceCredentialsProviderImpl, SourceVar *Source, CredentialsVar *NamedParameters, PermanentlyVar bool, CancellableVar *gio.Cancellable) bool {
		return rawCallback(ProviderImplVar.GoPointer(), SourceVar.GoPointer(), CredentialsVar, PermanentlyVar, CancellableVar.GoPointer())
	}
}

// OverrideDeleteSync sets the "delete_sync" callback function.
func (x *SourceCredentialsProviderImplClassGType) OverrideDeleteSync(cb func(*SourceCredentialsProviderImpl, *Source, *gio.Cancellable) bool) {
	if cb == nil {
		x.xDeleteSync = 0
	} else {
		x.xDeleteSync = purego.NewCallback(func(ProviderImplVarp uintptr, SourceVarp uintptr, CancellableVarp uintptr) bool {
			return cb(SourceCredentialsProviderImplNewFromInternalPtr(ProviderImplVarp), SourceNewFromInternalPtr(SourceVarp), gio.CancellableNewFromInternalPtr(CancellableVarp))
		})
	}
}

// GetDeleteSync gets the "delete_sync" callback function.
func (x *SourceCredentialsProviderImplClassGType) GetDeleteSync() func(*SourceCredentialsProviderImpl, *Source, *gio.Cancellable) bool {
	if x.xDeleteSync == 0 {
		return nil
	}
	var rawCallback func(ProviderImplVarp uintptr, SourceVarp uintptr, CancellableVarp uintptr) bool
	purego.RegisterFunc(&rawCallback, x.xDeleteSync)
	return func(ProviderImplVar *SourceCredentialsProviderImpl, SourceVar *Source, CancellableVar *gio.Cancellable) bool {
		return rawCallback(ProviderImplVar.GoPointer(), SourceVar.GoPointer(), CancellableVar.GoPointer())
	}
}

type SourceCredentialsProviderImplPrivate struct {
	_ structs.HostLayout
}

func (x *SourceCredentialsProviderImplPrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// Credentials provider implementation base structure. The descendants
// implement the virtual methods. The descendants are automatically
// registered into an #ESourceCredentialsProvider.
type SourceCredentialsProviderImpl struct {
	Extension
}

var xSourceCredentialsProviderImplGLibType func() types.GType

func SourceCredentialsProviderImplGLibType() types.GType {
	return xSourceCredentialsProviderImplGLibType()
}

func SourceCredentialsProviderImplNewFromInternalPtr(ptr uintptr) *SourceCredentialsProviderImpl {
	cls := &SourceCredentialsProviderImpl{}
	cls.Ptr = ptr
	return cls
}

var xSourceCredentialsProviderImplCanProcess func(uintptr, uintptr) bool

// Returns whether the @provider_impl can process credentials for the @source.
func (x *SourceCredentialsProviderImpl) CanProcess(SourceVar *Source) bool {

	cret := xSourceCredentialsProviderImplCanProcess(x.GoPointer(), SourceVar.GoPointer())
	return cret
}

var xSourceCredentialsProviderImplCanPrompt func(uintptr) bool

// Returns whether credential prompt can be done for the @provider_impl.
func (x *SourceCredentialsProviderImpl) CanPrompt() bool {

	cret := xSourceCredentialsProviderImplCanPrompt(x.GoPointer())
	return cret
}

var xSourceCredentialsProviderImplCanStore func(uintptr) bool

// Returns whether the @provider_impl can store credentials.
func (x *SourceCredentialsProviderImpl) CanStore() bool {

	cret := xSourceCredentialsProviderImplCanStore(x.GoPointer())
	return cret
}

var xSourceCredentialsProviderImplDeleteSync func(uintptr, uintptr, uintptr, **glib.Error) bool

// Asks @provider_impl to delete any stored credentials for @source.
//
// Default implementation returns %FALSE and sets #G_IO_ERROR_NOT_SUPPORTED error.
//
// If an error occurs, the function sets @error and returns %FALSE.
func (x *SourceCredentialsProviderImpl) DeleteSync(SourceVar *Source, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xSourceCredentialsProviderImplDeleteSync(x.GoPointer(), SourceVar.GoPointer(), CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceCredentialsProviderImplGetProvider func(uintptr) uintptr

// Returns an #ESourceCredentialsProvider with which the @provider_impl is associated.
func (x *SourceCredentialsProviderImpl) GetProvider() uintptr {

	cret := xSourceCredentialsProviderImplGetProvider(x.GoPointer())
	return cret
}

var xSourceCredentialsProviderImplLookupSync func(uintptr, uintptr, uintptr, **NamedParameters, **glib.Error) bool

// Asks @provider_impl to lookup for stored credentials for @source.
// The @out_credentials is populated with them. If the result is not
// %NULL, then it should be freed with e_named_parameters_free() when
// no longer needed.
//
// Default implementation returns %FALSE and sets #G_IO_ERROR_NOT_SUPPORTED error.
//
// If an error occurs, the function sets @error and returns %FALSE.
func (x *SourceCredentialsProviderImpl) LookupSync(SourceVar *Source, CancellableVar *gio.Cancellable, OutCredentialsVar **NamedParameters) (bool, error) {
	var cerr *glib.Error

	cret := xSourceCredentialsProviderImplLookupSync(x.GoPointer(), SourceVar.GoPointer(), CancellableVar.GoPointer(), OutCredentialsVar, &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xSourceCredentialsProviderImplStoreSync func(uintptr, uintptr, *NamedParameters, bool, uintptr, **glib.Error) bool

// Asks @provider_impl to store @credentials for @source.
//
// Default implementation returns %FALSE and sets #G_IO_ERROR_NOT_SUPPORTED error.
//
// If an error occurs, the function sets @error and returns %FALSE.
func (x *SourceCredentialsProviderImpl) StoreSync(SourceVar *Source, CredentialsVar *NamedParameters, PermanentlyVar bool, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xSourceCredentialsProviderImplStoreSync(x.GoPointer(), SourceVar.GoPointer(), CredentialsVar, PermanentlyVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

func (c *SourceCredentialsProviderImpl) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *SourceCredentialsProviderImpl) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("EDATASERVER", "libedataserver-1.2")
	core.SetSharedLibraries("EDATASERVER", []string{"libcamel-1.2.so.66", "libedataserver-1.2.so.27"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("EDATASERVER") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xSourceCredentialsProviderImplGLibType, libs, "e_source_credentials_provider_impl_get_type")

	core.PuregoSafeRegister(&xSourceCredentialsProviderImplCanProcess, libs, "e_source_credentials_provider_impl_can_process")
	core.PuregoSafeRegister(&xSourceCredentialsProviderImplCanPrompt, libs, "e_source_credentials_provider_impl_can_prompt")
	core.PuregoSafeRegister(&xSourceCredentialsProviderImplCanStore, libs, "e_source_credentials_provider_impl_can_store")
	core.PuregoSafeRegister(&xSourceCredentialsProviderImplDeleteSync, libs, "e_source_credentials_provider_impl_delete_sync")
	core.PuregoSafeRegister(&xSourceCredentialsProviderImplGetProvider, libs, "e_source_credentials_provider_impl_get_provider")
	core.PuregoSafeRegister(&xSourceCredentialsProviderImplLookupSync, libs, "e_source_credentials_provider_impl_lookup_sync")
	core.PuregoSafeRegister(&xSourceCredentialsProviderImplStoreSync, libs, "e_source_credentials_provider_impl_store_sync")

}
