// Package edataserver was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package edataserver

import (
	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/soup"
)

var xSoupSslTrustConnect func(uintptr, uintptr)

// Sets up automatic SSL certificate trust handling for @soup_message using the trust
// data stored in @source's WebDAV extension. If @soup_message is about to be sent on
// an SSL connection with an invalid certificate, the code checks if the WebDAV
// extension already has a trust response for that certificate and verifies it
// with e_source_webdav_verify_ssl_trust(). If the verification fails, then
// the @soup_message send also fails.
//
// This works by connecting to the "network-event" signal on @soup_message and
// connecting to the "accept-certificate" signal on each #GTlsConnection for
// which @soup_message reports a #G_SOCKET_CLIENT_TLS_HANDSHAKING event. These
// handlers are torn down automatically when @soup_message is disposed. This process
// is not thread-safe; it is sufficient for safety if all use of @soup_message's
// session and the disposal of @soup_message occur in the same thread.
func SoupSslTrustConnect(SoupMessageVar *soup.Message, SourceVar *Source) {

	xSoupSslTrustConnect(SoupMessageVar.GoPointer(), SourceVar.GoPointer())

}

func init() {
	core.SetPackageName("EDATASERVER", "libedataserver-1.2")
	core.SetSharedLibraries("EDATASERVER", []string{"libcamel-1.2.so.66", "libedataserver-1.2.so.27"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("EDATASERVER") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xSoupSslTrustConnect, libs, "e_soup_ssl_trust_connect")

}
