// Package ebookcontacts was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package ebookcontacts

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type BookQuery struct {
	_ structs.HostLayout
}

var xBookQueryGLibType func() types.GType

func BookQueryGLibType() types.GType {
	return xBookQueryGLibType()
}

func (x *BookQuery) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xBookQueryAndv func(uintptr, ...interface{}) *BookQuery

// Creates a new #EBookQuery which is the logical AND of the queries specified.
// The new #EBookQuery takes ownership of the specified queries.
func (x *BookQuery) Andv(varArgs ...interface{}) *BookQuery {

	cret := xBookQueryAndv(x.GoPointer(), varArgs...)
	return cret
}

var xBookQueryCopy func(uintptr) *BookQuery

// Creates a copy of @q.
func (x *BookQuery) Copy() *BookQuery {

	cret := xBookQueryCopy(x.GoPointer())
	return cret
}

var xBookQueryNot func(uintptr, bool) *BookQuery

// Creates a new #EBookQuery which is the opposite of #q.
func (x *BookQuery) Not(UnrefVar bool) *BookQuery {

	cret := xBookQueryNot(x.GoPointer(), UnrefVar)
	return cret
}

var xBookQueryOrv func(uintptr, ...interface{}) *BookQuery

// Creates a new #EBookQuery which is the logical OR of the queries specified.
// The new #EBookQuery takes ownership of the specified queries.
func (x *BookQuery) Orv(varArgs ...interface{}) *BookQuery {

	cret := xBookQueryOrv(x.GoPointer(), varArgs...)
	return cret
}

var xBookQueryRef func(uintptr) *BookQuery

// Increment the reference count on @q.
func (x *BookQuery) Ref() *BookQuery {

	cret := xBookQueryRef(x.GoPointer())
	return cret
}

var xBookQueryToString func(uintptr) string

// Return the string representation of @q.
func (x *BookQuery) ToString() string {

	cret := xBookQueryToString(x.GoPointer())
	return cret
}

var xBookQueryUnref func(uintptr)

// Decrement the reference count on @q. When the reference count reaches 0, @q
// will be freed and any child queries will have e_book_query_unref() called.
func (x *BookQuery) Unref() {

	xBookQueryUnref(x.GoPointer())

}

// The kind of test a query created by e_book_query_field_test() shall perform.
//
// See also: e_phone_number_compare_strings().
type BookQueryTest int

const (

	// look for exact match of the supplied test value
	EBookQueryIsValue BookQueryTest = 0
	// check if a field contains the test value
	EBookQueryContainsValue BookQueryTest = 1
	// check if a field starts with the test value
	EBookQueryBeginsWithValue BookQueryTest = 2
	// check if a field ends with the test value
	EBookQueryEndsWithValue BookQueryTest = 3
	// check if a field matches with a value tested
	// using e_phone_number_compare_strings(), the match must be of strenth %E_PHONE_NUMBER_MATCH_EXACT
	// for this query to return any matches.
	EBookQueryEqualsPhoneNumberValue BookQueryTest = 4
	// check if a field matches with a value tested
	// using e_phone_number_compare_strings(), the match must be at least of strength %E_PHONE_NUMBER_MATCH_NATIONAL
	// for this query to return any matches.
	EBookQueryEqualsNationalPhoneNumberValue BookQueryTest = 5
	// check if a field matches with a value tested
	// using e_phone_number_compare_strings(), the match must be at least of strength %E_PHONE_NUMBER_MATCH_SHORT
	// for this query to return any matches.
	EBookQueryEqualsShortPhoneNumberValue BookQueryTest = 6
	// A regular expression query against contact data normalized with e_util_utf8_normalize(),
	// the normalized data is lower case with any accents removed.
	EBookQueryRegexNormalValue BookQueryTest = 7
	// A regular expression query against raw contact data, this is usually slower than
	// a %E_BOOK_QUERY_REGEX_NORMAL as it implies that #EVCard(s) must be parsed in order to get the raw data
	// for comparison.
	EBookQueryRegexRawValue BookQueryTest = 8
	// End marker for the #EBookQueryTest enumeration, not a valid query test.
	EBookQueryLastValue BookQueryTest = 9
)

var xBookQueryAnd func(int, **BookQuery, bool) *BookQuery

// Create a new #EBookQuery which is the logical AND of the queries in #qs.
func BookQueryAnd(NqsVar int, QsVar **BookQuery, UnrefVar bool) *BookQuery {

	cret := xBookQueryAnd(NqsVar, QsVar, UnrefVar)
	return cret
}

var xBookQueryAnyFieldContains func(string) *BookQuery

// Creates a new #EBookQuery which tests if any field contains @value.
func BookQueryAnyFieldContains(ValueVar string) *BookQuery {

	cret := xBookQueryAnyFieldContains(ValueVar)
	return cret
}

var xBookQueryFieldExists func(ContactField) *BookQuery

// Creates a new #EBookQuery which tests if the field @field exists.
func BookQueryFieldExists(FieldVar ContactField) *BookQuery {

	cret := xBookQueryFieldExists(FieldVar)
	return cret
}

var xBookQueryFieldTest func(ContactField, BookQueryTest, string) *BookQuery

// Creates a new #EBookQuery which tests @field for @value using the test @test.
func BookQueryFieldTest(FieldVar ContactField, TestVar BookQueryTest, ValueVar string) *BookQuery {

	cret := xBookQueryFieldTest(FieldVar, TestVar, ValueVar)
	return cret
}

var xBookQueryFromString func(string) *BookQuery

// Parse @query_string and return a new #EBookQuery representing it.
func BookQueryFromString(QueryStringVar string) *BookQuery {

	cret := xBookQueryFromString(QueryStringVar)
	return cret
}

var xBookQueryOr func(int, **BookQuery, bool) *BookQuery

// Creates a new #EBookQuery which is the logical OR of the queries in #qs.
func BookQueryOr(NqsVar int, QsVar **BookQuery, UnrefVar bool) *BookQuery {

	cret := xBookQueryOr(NqsVar, QsVar, UnrefVar)
	return cret
}

var xBookQueryVcardFieldExists func(string) *BookQuery

// Creates a new #EBookQuery which tests if the field @field exists. @field
// should be a vCard field name, such as #EVC_FN or #EVC_X_MSN.
func BookQueryVcardFieldExists(FieldVar string) *BookQuery {

	cret := xBookQueryVcardFieldExists(FieldVar)
	return cret
}

var xBookQueryVcardFieldTest func(string, BookQueryTest, string) *BookQuery

// Creates a new #EBookQuery which tests @field for @value using the test @test.
func BookQueryVcardFieldTest(FieldVar string, TestVar BookQueryTest, ValueVar string) *BookQuery {

	cret := xBookQueryVcardFieldTest(FieldVar, TestVar, ValueVar)
	return cret
}

func init() {
	core.SetPackageName("EBOOKCONTACTS", "libebook-contacts-1.2")
	core.SetSharedLibraries("EBOOKCONTACTS", []string{"libebook-contacts-1.2.so.4", "libedataserver-1.2.so.27"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("EBOOKCONTACTS") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xBookQueryAnd, libs, "e_book_query_and")
	core.PuregoSafeRegister(&xBookQueryAnyFieldContains, libs, "e_book_query_any_field_contains")
	core.PuregoSafeRegister(&xBookQueryFieldExists, libs, "e_book_query_field_exists")
	core.PuregoSafeRegister(&xBookQueryFieldTest, libs, "e_book_query_field_test")
	core.PuregoSafeRegister(&xBookQueryFromString, libs, "e_book_query_from_string")
	core.PuregoSafeRegister(&xBookQueryOr, libs, "e_book_query_or")
	core.PuregoSafeRegister(&xBookQueryVcardFieldExists, libs, "e_book_query_vcard_field_exists")
	core.PuregoSafeRegister(&xBookQueryVcardFieldTest, libs, "e_book_query_vcard_field_test")

	core.PuregoSafeRegister(&xBookQueryGLibType, libs, "e_book_query_get_type")

	core.PuregoSafeRegister(&xBookQueryAndv, libs, "e_book_query_andv")
	core.PuregoSafeRegister(&xBookQueryCopy, libs, "e_book_query_copy")
	core.PuregoSafeRegister(&xBookQueryNot, libs, "e_book_query_not")
	core.PuregoSafeRegister(&xBookQueryOrv, libs, "e_book_query_orv")
	core.PuregoSafeRegister(&xBookQueryRef, libs, "e_book_query_ref")
	core.PuregoSafeRegister(&xBookQueryToString, libs, "e_book_query_to_string")
	core.PuregoSafeRegister(&xBookQueryUnref, libs, "e_book_query_unref")

}
