// Package gio was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gio

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

// Class structure for #GTlsPassword.
type TlsPasswordClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass

	xGetValue uintptr

	xSetValue uintptr

	xGetDefaultWarning uintptr

	Padding [4]uintptr
}

func (x *TlsPasswordClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// OverrideGetValue sets the callback function.
// virtual method for g_tls_password_get_value()
func (x *TlsPasswordClass) OverrideGetValue(cb func(*TlsPassword, *uint) uintptr) {
	if cb == nil {
		x.xGetValue = 0
	} else {
		x.xGetValue = purego.NewCallback(func(PasswordVarp uintptr, LengthVarp uintptr) uintptr {
			return cb(TlsPasswordNewFromInternalPtr(PasswordVarp), (*uint)(unsafe.Pointer(LengthVarp)))
		})
	}
}

// GetGetValue gets the callback function.
// virtual method for g_tls_password_get_value()
func (x *TlsPasswordClass) GetGetValue() func(*TlsPassword, *uint) uintptr {
	if x.xGetValue == 0 {
		return nil
	}
	var rawCallback func(PasswordVarp uintptr, LengthVarp uintptr) uintptr
	purego.RegisterFunc(&rawCallback, x.xGetValue)
	return func(PasswordVar *TlsPassword, LengthVar *uint) uintptr {
		return rawCallback(PasswordVar.GoPointer(), uintptr(unsafe.Pointer(LengthVar)))
	}
}

// OverrideSetValue sets the callback function.
// virtual method for g_tls_password_set_value()
func (x *TlsPasswordClass) OverrideSetValue(cb func(*TlsPassword, []byte, int, *glib.DestroyNotify)) {
	if cb == nil {
		x.xSetValue = 0
	} else {
		x.xSetValue = purego.NewCallback(func(PasswordVarp uintptr, ValueVarp []byte, LengthVarp int, DestroyVarp uintptr) {
			cb(TlsPasswordNewFromInternalPtr(PasswordVarp), ValueVarp, LengthVarp, (*glib.DestroyNotify)(unsafe.Pointer(DestroyVarp)))
		})
	}
}

// GetSetValue gets the callback function.
// virtual method for g_tls_password_set_value()
func (x *TlsPasswordClass) GetSetValue() func(*TlsPassword, []byte, int, *glib.DestroyNotify) {
	if x.xSetValue == 0 {
		return nil
	}
	var rawCallback func(PasswordVarp uintptr, ValueVarp []byte, LengthVarp int, DestroyVarp uintptr)
	purego.RegisterFunc(&rawCallback, x.xSetValue)
	return func(PasswordVar *TlsPassword, ValueVar []byte, LengthVar int, DestroyVar *glib.DestroyNotify) {
		rawCallback(PasswordVar.GoPointer(), ValueVar, LengthVar, glib.NewCallbackNullable(DestroyVar))
	}
}

// OverrideGetDefaultWarning sets the callback function.
// virtual method for g_tls_password_get_warning() if no
//
//	value has been set using g_tls_password_set_warning()
func (x *TlsPasswordClass) OverrideGetDefaultWarning(cb func(*TlsPassword) string) {
	if cb == nil {
		x.xGetDefaultWarning = 0
	} else {
		x.xGetDefaultWarning = purego.NewCallback(func(PasswordVarp uintptr) string {
			return cb(TlsPasswordNewFromInternalPtr(PasswordVarp))
		})
	}
}

// GetGetDefaultWarning gets the callback function.
// virtual method for g_tls_password_get_warning() if no
//
//	value has been set using g_tls_password_set_warning()
func (x *TlsPasswordClass) GetGetDefaultWarning() func(*TlsPassword) string {
	if x.xGetDefaultWarning == 0 {
		return nil
	}
	var rawCallback func(PasswordVarp uintptr) string
	purego.RegisterFunc(&rawCallback, x.xGetDefaultWarning)
	return func(PasswordVar *TlsPassword) string {
		return rawCallback(PasswordVar.GoPointer())
	}
}

type TlsPasswordPrivate struct {
	_ structs.HostLayout
}

func (x *TlsPasswordPrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// An abstract interface representing a password used in TLS. Often used in
// user interaction such as unlocking a key storage token.
type TlsPassword struct {
	gobject.Object
}

var xTlsPasswordGLibType func() types.GType

func TlsPasswordGLibType() types.GType {
	return xTlsPasswordGLibType()
}

func TlsPasswordNewFromInternalPtr(ptr uintptr) *TlsPassword {
	cls := &TlsPassword{}
	cls.Ptr = ptr
	return cls
}

var xNewTlsPassword func(TlsPasswordFlags, string) uintptr

// Create a new #GTlsPassword object.
func NewTlsPassword(FlagsVar TlsPasswordFlags, DescriptionVar string) *TlsPassword {
	var cls *TlsPassword

	cret := xNewTlsPassword(FlagsVar, DescriptionVar)

	if cret == 0 {
		return nil
	}
	cls = &TlsPassword{}
	cls.Ptr = cret
	return cls
}

var xTlsPasswordGetDescription func(uintptr) string

// Get a description string about what the password will be used for.
func (x *TlsPassword) GetDescription() string {

	cret := xTlsPasswordGetDescription(x.GoPointer())
	return cret
}

var xTlsPasswordGetFlags func(uintptr) TlsPasswordFlags

// Get flags about the password.
func (x *TlsPassword) GetFlags() TlsPasswordFlags {

	cret := xTlsPasswordGetFlags(x.GoPointer())
	return cret
}

var xTlsPasswordGetValue func(uintptr, uintptr) uintptr

// Get the password value. If @length is not %NULL then it will be
// filled in with the length of the password value. (Note that the
// password value is not nul-terminated, so you can only pass %NULL
// for @length in contexts where you know the password will have a
// certain fixed length.)
func (x *TlsPassword) GetValue(LengthVar *uint) uintptr {

	cret := xTlsPasswordGetValue(x.GoPointer(), uintptr(unsafe.Pointer(LengthVar)))
	return cret
}

var xTlsPasswordGetWarning func(uintptr) string

// Get a user readable translated warning. Usually this warning is a
// representation of the password flags returned from
// g_tls_password_get_flags().
func (x *TlsPassword) GetWarning() string {

	cret := xTlsPasswordGetWarning(x.GoPointer())
	return cret
}

var xTlsPasswordSetDescription func(uintptr, string)

// Set a description string about what the password will be used for.
func (x *TlsPassword) SetDescription(DescriptionVar string) {

	xTlsPasswordSetDescription(x.GoPointer(), DescriptionVar)

}

var xTlsPasswordSetFlags func(uintptr, TlsPasswordFlags)

// Set flags about the password.
func (x *TlsPassword) SetFlags(FlagsVar TlsPasswordFlags) {

	xTlsPasswordSetFlags(x.GoPointer(), FlagsVar)

}

var xTlsPasswordSetValue func(uintptr, []byte, int)

// Set the value for this password. The @value will be copied by the password
// object.
//
// Specify the @length, for a non-nul-terminated password. Pass -1 as
// @length if using a nul-terminated password, and @length will be
// calculated automatically. (Note that the terminating nul is not
// considered part of the password in this case.)
func (x *TlsPassword) SetValue(ValueVar []byte, LengthVar int) {

	xTlsPasswordSetValue(x.GoPointer(), ValueVar, LengthVar)

}

var xTlsPasswordSetValueFull func(uintptr, []byte, int, uintptr)

// Provide the value for this password.
//
// The @value will be owned by the password object, and later freed using
// the @destroy function callback.
//
// Specify the @length, for a non-nul-terminated password. Pass -1 as
// @length if using a nul-terminated password, and @length will be
// calculated automatically. (Note that the terminating nul is not
// considered part of the password in this case.)
func (x *TlsPassword) SetValueFull(ValueVar []byte, LengthVar int, DestroyVar *glib.DestroyNotify) {

	xTlsPasswordSetValueFull(x.GoPointer(), ValueVar, LengthVar, glib.NewCallbackNullable(DestroyVar))

}

var xTlsPasswordSetWarning func(uintptr, string)

// Set a user readable translated warning. Usually this warning is a
// representation of the password flags returned from
// g_tls_password_get_flags().
func (x *TlsPassword) SetWarning(WarningVar string) {

	xTlsPasswordSetWarning(x.GoPointer(), WarningVar)

}

func (c *TlsPassword) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *TlsPassword) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("GIO", "gio-2.0")
	core.SetSharedLibraries("GIO", []string{"libgio-2.0.so.0"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("GIO") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xTlsPasswordGLibType, libs, "g_tls_password_get_type")

	core.PuregoSafeRegister(&xNewTlsPassword, libs, "g_tls_password_new")

	core.PuregoSafeRegister(&xTlsPasswordGetDescription, libs, "g_tls_password_get_description")
	core.PuregoSafeRegister(&xTlsPasswordGetFlags, libs, "g_tls_password_get_flags")
	core.PuregoSafeRegister(&xTlsPasswordGetValue, libs, "g_tls_password_get_value")
	core.PuregoSafeRegister(&xTlsPasswordGetWarning, libs, "g_tls_password_get_warning")
	core.PuregoSafeRegister(&xTlsPasswordSetDescription, libs, "g_tls_password_set_description")
	core.PuregoSafeRegister(&xTlsPasswordSetFlags, libs, "g_tls_password_set_flags")
	core.PuregoSafeRegister(&xTlsPasswordSetValue, libs, "g_tls_password_set_value")
	core.PuregoSafeRegister(&xTlsPasswordSetValueFull, libs, "g_tls_password_set_value_full")
	core.PuregoSafeRegister(&xTlsPasswordSetWarning, libs, "g_tls_password_set_warning")

}
