// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type ContentDisposition struct {
	_ structs.HostLayout

	Disposition uintptr

	Params uintptr

	Refcount uint32
}

var xContentDispositionGLibType func() types.GType

func ContentDispositionGLibType() types.GType {
	return xContentDispositionGLibType()
}

func (x *ContentDisposition) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xNewContentDisposition func() *ContentDisposition

func NewContentDisposition() *ContentDisposition {

	cret := xNewContentDisposition()
	return cret
}

var xContentDispositionFormat func(uintptr) string

func (x *ContentDisposition) Format() string {

	cret := xContentDispositionFormat(x.GoPointer())
	return cret
}

var xContentDispositionIsAttachment func(uintptr, *ContentType) bool

func (x *ContentDisposition) IsAttachment(ContentTypeVar *ContentType) bool {

	cret := xContentDispositionIsAttachment(x.GoPointer(), ContentTypeVar)
	return cret
}

var xContentDispositionIsAttachmentEx func(uintptr, *ContentType, *ContentType) bool

func (x *ContentDisposition) IsAttachmentEx(ContentTypeVar *ContentType, ParentContentTypeVar *ContentType) bool {

	cret := xContentDispositionIsAttachmentEx(x.GoPointer(), ContentTypeVar, ParentContentTypeVar)
	return cret
}

var xContentDispositionRef func(uintptr) *ContentDisposition

func (x *ContentDisposition) Ref() *ContentDisposition {

	cret := xContentDispositionRef(x.GoPointer())
	return cret
}

var xContentDispositionUnref func(uintptr)

func (x *ContentDisposition) Unref() {

	xContentDispositionUnref(x.GoPointer())

}

type ContentType struct {
	_ structs.HostLayout

	Type uintptr

	Subtype uintptr

	Params uintptr

	Refcount uint32
}

var xContentTypeGLibType func() types.GType

func ContentTypeGLibType() types.GType {
	return xContentTypeGLibType()
}

func (x *ContentType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xNewContentType func(string, string) *ContentType

// Create a new #CamelContentType.
func NewContentType(TypeVar string, SubtypeVar string) *ContentType {

	cret := xNewContentType(TypeVar, SubtypeVar)
	return cret
}

var xContentTypeDump func(uintptr)

func (x *ContentType) Dump() {

	xContentTypeDump(x.GoPointer())

}

var xContentTypeFormat func(uintptr) string

func (x *ContentType) Format() string {

	cret := xContentTypeFormat(x.GoPointer())
	return cret
}

var xContentTypeIs func(uintptr, string, string) bool

// The subtype of "*" will match any subtype.  If @ct is %NULL, then
// it will match the type "text/plain".
func (x *ContentType) Is(TypeVar string, SubtypeVar string) bool {

	cret := xContentTypeIs(x.GoPointer(), TypeVar, SubtypeVar)
	return cret
}

var xContentTypeParam func(uintptr, string) string

// Searches the params on s #CamelContentType for a param named @name
// and gets the value.
func (x *ContentType) Param(NameVar string) string {

	cret := xContentTypeParam(x.GoPointer(), NameVar)
	return cret
}

var xContentTypeRef func(uintptr) *ContentType

// Refs the content type.
func (x *ContentType) Ref() *ContentType {

	cret := xContentTypeRef(x.GoPointer())
	return cret
}

var xContentTypeSetParam func(uintptr, string, string)

// Set a parameter on @content_type.
func (x *ContentType) SetParam(NameVar string, ValueVar string) {

	xContentTypeSetParam(x.GoPointer(), NameVar, ValueVar)

}

var xContentTypeSimple func(uintptr) string

func (x *ContentType) Simple() string {

	cret := xContentTypeSimple(x.GoPointer())
	return cret
}

var xContentTypeUnref func(uintptr)

// Unrefs, and potentially frees, the content type.
func (x *ContentType) Unref() {

	xContentTypeUnref(x.GoPointer())

}

type HeaderAddress struct {
	_ structs.HostLayout

	Next uintptr

	Type HeaderAddressType

	Name uintptr

	Refcount uint32
}

var xHeaderAddressGLibType func() types.GType

func HeaderAddressGLibType() types.GType {
	return xHeaderAddressGLibType()
}

func (x *HeaderAddress) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xNewHeaderAddress func() *HeaderAddress

func NewHeaderAddress() *HeaderAddress {

	cret := xNewHeaderAddress()
	return cret
}

var xNewHeaderAddressGroup func(string) *HeaderAddress

func NewHeaderAddressGroup(NameVar string) *HeaderAddress {

	cret := xNewHeaderAddressGroup(NameVar)
	return cret
}

var xNewHeaderAddressName func(string, string) *HeaderAddress

func NewHeaderAddressName(NameVar string, AddrVar string) *HeaderAddress {

	cret := xNewHeaderAddressName(NameVar, AddrVar)
	return cret
}

var xHeaderAddressAddMember func(uintptr, *HeaderAddress)

func (x *HeaderAddress) AddMember(MemberVar *HeaderAddress) {

	xHeaderAddressAddMember(x.GoPointer(), MemberVar)

}

var xHeaderAddressRef func(uintptr) *HeaderAddress

func (x *HeaderAddress) Ref() *HeaderAddress {

	cret := xHeaderAddressRef(x.GoPointer())
	return cret
}

var xHeaderAddressSetAddr func(uintptr, string)

func (x *HeaderAddress) SetAddr(AddrVar string) {

	xHeaderAddressSetAddr(x.GoPointer(), AddrVar)

}

var xHeaderAddressSetMembers func(uintptr, []HeaderAddress)

// TODO: Document me.
func (x *HeaderAddress) SetMembers(GroupVar []HeaderAddress) {

	xHeaderAddressSetMembers(x.GoPointer(), GroupVar)

}

var xHeaderAddressSetName func(uintptr, string)

func (x *HeaderAddress) SetName(NameVar string) {

	xHeaderAddressSetName(x.GoPointer(), NameVar)

}

var xHeaderAddressUnref func(uintptr)

func (x *HeaderAddress) Unref() {

	xHeaderAddressUnref(x.GoPointer())

}

type HeaderParam struct {
	_ structs.HostLayout

	Next uintptr

	Name uintptr

	Value uintptr
}

func (x *HeaderParam) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

const (
	FOLD_MAX_SIZE int = 998

	FOLD_SIZE int = 77

	UUDECODE_STATE_MASK int = 196608
)

type UUDecodeState int

const (
	UudecodeStateInitValue UUDecodeState = 0

	UudecodeStateBeginValue UUDecodeState = 65536

	UudecodeStateEndValue UUDecodeState = 131072
)

type HeaderAddressType int

const (
	HeaderAddressNoneValue HeaderAddressType = 0

	HeaderAddressNameValue HeaderAddressType = 1

	HeaderAddressGroupValue HeaderAddressType = 2
)

var xContentDispositionDecode func(string) *ContentDisposition

func ContentDispositionDecode(InVar string) *ContentDisposition {

	cret := xContentDispositionDecode(InVar)
	return cret
}

var xContentTransferEncodingDecode func(string) string

func ContentTransferEncodingDecode(InVar string) string {

	cret := xContentTransferEncodingDecode(InVar)
	return cret
}

var xContentTypeDecode func(string) *ContentType

func ContentTypeDecode(InVar string) *ContentType {

	cret := xContentTypeDecode(InVar)
	return cret
}

var xHeaderAddressDecode func(string, string) *HeaderAddress

func HeaderAddressDecode(InVar string, CharsetVar string) *HeaderAddress {

	cret := xHeaderAddressDecode(InVar, CharsetVar)
	return cret
}

var xHeaderAddressFold func(string, uint) string

func HeaderAddressFold(InVar string, HeaderlenVar uint) string {

	cret := xHeaderAddressFold(InVar, HeaderlenVar)
	return cret
}

var xHeaderAddressListAppend func(uintptr, *HeaderAddress)

// TODO: Document me.
func HeaderAddressListAppend(AddrlistpVar uintptr, AddrVar *HeaderAddress) {

	xHeaderAddressListAppend(AddrlistpVar, AddrVar)

}

var xHeaderAddressListAppendList func(uintptr, uintptr)

// TODO: Document me.
func HeaderAddressListAppendList(AddrlistpVar uintptr, AddrsVar uintptr) {

	xHeaderAddressListAppendList(AddrlistpVar, AddrsVar)

}

var xHeaderAddressListClear func(uintptr)

// TODO: Document me.
func HeaderAddressListClear(AddrlistpVar uintptr) {

	xHeaderAddressListClear(AddrlistpVar)

}

var xHeaderAddressListEncode func([]HeaderAddress) string

// TODO: Document me.
func HeaderAddressListEncode(AddrlistVar []HeaderAddress) string {

	cret := xHeaderAddressListEncode(AddrlistVar)
	return cret
}

var xHeaderAddressListFormat func([]HeaderAddress) string

// TODO: Document me.
func HeaderAddressListFormat(AddrlistVar []HeaderAddress) string {

	cret := xHeaderAddressListFormat(AddrlistVar)
	return cret
}

var xHeaderContentidDecode func(string) string

// Extract a content-id from @in.
func HeaderContentidDecode(InVar string) string {

	cret := xHeaderContentidDecode(InVar)
	return cret
}

var xHeaderDecodeDate func(string, int) int

// Decodes the rfc822 date string and saves the GMT offset into
// @tz_offset if non-NULL.
func HeaderDecodeDate(StrVar string, TzOffsetVar int) int {

	cret := xHeaderDecodeDate(StrVar, TzOffsetVar)
	return cret
}

var xHeaderDecodeInt func(string) int

// Extracts an integer token from @in and updates the pointer to point
// to after the end of the integer token (sort of like strtol).
func HeaderDecodeInt(InVar string) int {

	cret := xHeaderDecodeInt(InVar)
	return cret
}

var xHeaderDecodeString func(string, string) string

// Decodes rfc2047 encoded-word tokens
func HeaderDecodeString(InVar string, DefaultCharsetVar string) string {

	cret := xHeaderDecodeString(InVar, DefaultCharsetVar)
	return cret
}

var xHeaderEncodePhrase func(byte) string

// Encodes a 'phrase' header according to the rules in rfc2047.
func HeaderEncodePhrase(InVar byte) string {

	cret := xHeaderEncodePhrase(InVar)
	return cret
}

var xHeaderEncodeString func(byte) string

// Encodes a 'text' header according to the rules of rfc2047.
func HeaderEncodeString(InVar byte) string {

	cret := xHeaderEncodeString(InVar)
	return cret
}

var xHeaderFold func(string, uint) string

func HeaderFold(InVar string, HeaderlenVar uint) string {

	cret := xHeaderFold(InVar, HeaderlenVar)
	return cret
}

var xHeaderFormatCtext func(string, string) string

// Decodes a header which contains rfc2047 encoded-word tokens that
// may or may not be within a comment.
func HeaderFormatCtext(InVar string, DefaultCharsetVar string) string {

	cret := xHeaderFormatCtext(InVar, DefaultCharsetVar)
	return cret
}

var xHeaderFormatDate func(int, int) string

// Allocates a string buffer containing the rfc822 formatted date
// string represented by @time and @tz_offset.
func HeaderFormatDate(DateVar int, TzOffsetVar int) string {

	cret := xHeaderFormatDate(DateVar, TzOffsetVar)
	return cret
}

var xHeaderLocationDecode func(string) string

func HeaderLocationDecode(InVar string) string {

	cret := xHeaderLocationDecode(InVar)
	return cret
}

var xHeaderMailboxDecode func(string, string) *HeaderAddress

func HeaderMailboxDecode(InVar string, CharsetVar string) *HeaderAddress {

	cret := xHeaderMailboxDecode(InVar, CharsetVar)
	return cret
}

var xHeaderMimeDecode func(string, int, int)

func HeaderMimeDecode(InVar string, MajVar int, MinVar int) {

	xHeaderMimeDecode(InVar, MajVar, MinVar)

}

var xHeaderMsgidDecode func(string) string

// Extract a message-id token from @in.
func HeaderMsgidDecode(InVar string) string {

	cret := xHeaderMsgidDecode(InVar)
	return cret
}

var xHeaderMsgidGenerate func(string) string

// Either the @domain is used, or the user's local hostname,
// in case it's %NULL or empty.
func HeaderMsgidGenerate(DomainVar string) string {

	cret := xHeaderMsgidGenerate(DomainVar)
	return cret
}

var xHeaderNewsgroupsDecode func(string) *glib.SList

func HeaderNewsgroupsDecode(InVar string) *glib.SList {

	cret := xHeaderNewsgroupsDecode(InVar)
	return cret
}

var xNewHeaderParam func(uintptr, string) string

// Searches @params for a param named @name and gets the value.
func NewHeaderParam(ParamsVar uintptr, NameVar string) string {

	cret := xNewHeaderParam(ParamsVar, NameVar)
	return cret
}

var xHeaderParamListDecode func(string) uintptr

func HeaderParamListDecode(InVar string) uintptr {

	cret := xHeaderParamListDecode(InVar)
	return cret
}

var xHeaderParamListFormat func(uintptr) string

func HeaderParamListFormat(ParamsVar uintptr) string {

	cret := xHeaderParamListFormat(ParamsVar)
	return cret
}

var xHeaderParamListFormatAppend func(*glib.String, uintptr)

func HeaderParamListFormatAppend(OutVar *glib.String, ParamsVar uintptr) {

	xHeaderParamListFormatAppend(OutVar, ParamsVar)

}

var xHeaderParamListFree func(uintptr)

// Free the list of params.
func HeaderParamListFree(ParamsVar uintptr) {

	xHeaderParamListFree(ParamsVar)

}

var xHeaderReferencesDecode func(string) *glib.SList

// Generate a list of references, from most recent up.
func HeaderReferencesDecode(InVar string) *glib.SList {

	cret := xHeaderReferencesDecode(InVar)
	return cret
}

var xHeaderSetParam func(uintptr, string, string) uintptr

// Set a parameter in the list.
func HeaderSetParam(ParamspVar uintptr, NameVar string, ValueVar string) uintptr {

	cret := xHeaderSetParam(ParamspVar, NameVar, ValueVar)
	return cret
}

var xHeaderTokenDecode func(string) string

// Gets the first token in the string according to the rules of
// rfc0822.
func HeaderTokenDecode(InVar string) string {

	cret := xHeaderTokenDecode(InVar)
	return cret
}

var xHeaderUnfold func(string) string

func HeaderUnfold(InVar string) string {

	cret := xHeaderUnfold(InVar)
	return cret
}

var xHeadersDupMailingList func(*NameValueArray) string

// Searches for a mailing list information among known headers and returns
// a newly allocated string with its value.
func HeadersDupMailingList(HeadersVar *NameValueArray) string {

	cret := xHeadersDupMailingList(HeadersVar)
	return cret
}

var xLocaltimeWithOffset func(int, uintptr, int)

// Converts the calendar time representation @tt to a broken-down
// time representation, stored in @tm, and provides the offset in
// seconds from UTC time, stored in @offset.
func LocaltimeWithOffset(TtVar int, TmVar uintptr, OffsetVar int) {

	xLocaltimeWithOffset(TtVar, TmVar, OffsetVar)

}

var xMktimeUtc func(uintptr) int

// Like mktime(3), but assumes UTC instead of local timezone.
func MktimeUtc(TmVar uintptr) int {

	cret := xMktimeUtc(TmVar)
	return cret
}

var xQuotedDecodeStep func([]byte, uint, []byte, int, []int) uint

// Decodes a block of quoted-printable encoded data. Performs a
// 'decode step' on a chunk of QP encoded data.
func QuotedDecodeStep(InVar []byte, LenVar uint, OutVar []byte, SavestateVar int, SavemeVar []int) uint {

	cret := xQuotedDecodeStep(InVar, LenVar, OutVar, SavestateVar, SavemeVar)
	return cret
}

var xQuotedEncodeClose func([]byte, uint, []byte, int, []int) uint

// Quoted-printable encodes a block of text. Call this when finished
// encoding data with camel_quoted_encode_step() to flush off
// the last little bit.
func QuotedEncodeClose(InVar []byte, LenVar uint, OutVar []byte, StateVar int, SaveVar []int) uint {

	cret := xQuotedEncodeClose(InVar, LenVar, OutVar, StateVar, SaveVar)
	return cret
}

var xQuotedEncodeStep func([]byte, uint, []byte, int, []int) uint

// Quoted-printable encodes a block of text. Performs an 'encode
// step', saves left-over state in state and save (initialise to -1 on
// first invocation).
func QuotedEncodeStep(InVar []byte, LenVar uint, OutVar []byte, StateVar int, SaveVar []int) uint {

	cret := xQuotedEncodeStep(InVar, LenVar, OutVar, StateVar, SaveVar)
	return cret
}

var xTransferEncodingFromString func(string) TransferEncoding

func TransferEncodingFromString(StringVar string) TransferEncoding {

	cret := xTransferEncodingFromString(StringVar)
	return cret
}

var xTransferEncodingToString func(TransferEncoding) string

func TransferEncodingToString(EncodingVar TransferEncoding) string {

	cret := xTransferEncodingToString(EncodingVar)
	return cret
}

var xUudecodeStep func([]byte, uint, []byte, int, []uint32) uint

// Uudecodes a chunk of data. Performs a 'decode step' on a chunk of
// uuencoded data. Assumes the "begin mode filename" line has
// been stripped off.
func UudecodeStep(InVar []byte, InlenVar uint, OutVar []byte, StateVar int, SaveVar []uint32) uint {

	cret := xUudecodeStep(InVar, InlenVar, OutVar, StateVar, SaveVar)
	return cret
}

var xUuencodeClose func([]byte, uint, []byte, [60]byte, int, []uint32) uint

// Uuencodes a chunk of data. Call this when finished encoding data
// with camel_uuencode_step() to flush off the last little bit.
func UuencodeClose(InVar []byte, LenVar uint, OutVar []byte, UubufVar [60]byte, StateVar int, SaveVar []uint32) uint {

	cret := xUuencodeClose(InVar, LenVar, OutVar, UubufVar, StateVar, SaveVar)
	return cret
}

var xUuencodeStep func([]byte, uint, []byte, [60]byte, int, []uint32) uint

// Uuencodes a chunk of data. Performs an 'encode step', only encodes
// blocks of 45 characters to the output at a time, saves left-over
// state in @uubuf, @state and @save (initialize to 0 on first
// invocation).
func UuencodeStep(InVar []byte, LenVar uint, OutVar []byte, UubufVar [60]byte, StateVar int, SaveVar []uint32) uint {

	cret := xUuencodeStep(InVar, LenVar, OutVar, UubufVar, StateVar, SaveVar)
	return cret
}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xContentDispositionDecode, libs, "camel_content_disposition_decode")
	core.PuregoSafeRegister(&xContentTransferEncodingDecode, libs, "camel_content_transfer_encoding_decode")
	core.PuregoSafeRegister(&xContentTypeDecode, libs, "camel_content_type_decode")
	core.PuregoSafeRegister(&xHeaderAddressDecode, libs, "camel_header_address_decode")
	core.PuregoSafeRegister(&xHeaderAddressFold, libs, "camel_header_address_fold")
	core.PuregoSafeRegister(&xHeaderAddressListAppend, libs, "camel_header_address_list_append")
	core.PuregoSafeRegister(&xHeaderAddressListAppendList, libs, "camel_header_address_list_append_list")
	core.PuregoSafeRegister(&xHeaderAddressListClear, libs, "camel_header_address_list_clear")
	core.PuregoSafeRegister(&xHeaderAddressListEncode, libs, "camel_header_address_list_encode")
	core.PuregoSafeRegister(&xHeaderAddressListFormat, libs, "camel_header_address_list_format")
	core.PuregoSafeRegister(&xHeaderContentidDecode, libs, "camel_header_contentid_decode")
	core.PuregoSafeRegister(&xHeaderDecodeDate, libs, "camel_header_decode_date")
	core.PuregoSafeRegister(&xHeaderDecodeInt, libs, "camel_header_decode_int")
	core.PuregoSafeRegister(&xHeaderDecodeString, libs, "camel_header_decode_string")
	core.PuregoSafeRegister(&xHeaderEncodePhrase, libs, "camel_header_encode_phrase")
	core.PuregoSafeRegister(&xHeaderEncodeString, libs, "camel_header_encode_string")
	core.PuregoSafeRegister(&xHeaderFold, libs, "camel_header_fold")
	core.PuregoSafeRegister(&xHeaderFormatCtext, libs, "camel_header_format_ctext")
	core.PuregoSafeRegister(&xHeaderFormatDate, libs, "camel_header_format_date")
	core.PuregoSafeRegister(&xHeaderLocationDecode, libs, "camel_header_location_decode")
	core.PuregoSafeRegister(&xHeaderMailboxDecode, libs, "camel_header_mailbox_decode")
	core.PuregoSafeRegister(&xHeaderMimeDecode, libs, "camel_header_mime_decode")
	core.PuregoSafeRegister(&xHeaderMsgidDecode, libs, "camel_header_msgid_decode")
	core.PuregoSafeRegister(&xHeaderMsgidGenerate, libs, "camel_header_msgid_generate")
	core.PuregoSafeRegister(&xHeaderNewsgroupsDecode, libs, "camel_header_newsgroups_decode")
	core.PuregoSafeRegister(&xNewHeaderParam, libs, "camel_header_param")
	core.PuregoSafeRegister(&xHeaderParamListDecode, libs, "camel_header_param_list_decode")
	core.PuregoSafeRegister(&xHeaderParamListFormat, libs, "camel_header_param_list_format")
	core.PuregoSafeRegister(&xHeaderParamListFormatAppend, libs, "camel_header_param_list_format_append")
	core.PuregoSafeRegister(&xHeaderParamListFree, libs, "camel_header_param_list_free")
	core.PuregoSafeRegister(&xHeaderReferencesDecode, libs, "camel_header_references_decode")
	core.PuregoSafeRegister(&xHeaderSetParam, libs, "camel_header_set_param")
	core.PuregoSafeRegister(&xHeaderTokenDecode, libs, "camel_header_token_decode")
	core.PuregoSafeRegister(&xHeaderUnfold, libs, "camel_header_unfold")
	core.PuregoSafeRegister(&xHeadersDupMailingList, libs, "camel_headers_dup_mailing_list")
	core.PuregoSafeRegister(&xLocaltimeWithOffset, libs, "camel_localtime_with_offset")
	core.PuregoSafeRegister(&xMktimeUtc, libs, "camel_mktime_utc")
	core.PuregoSafeRegister(&xQuotedDecodeStep, libs, "camel_quoted_decode_step")
	core.PuregoSafeRegister(&xQuotedEncodeClose, libs, "camel_quoted_encode_close")
	core.PuregoSafeRegister(&xQuotedEncodeStep, libs, "camel_quoted_encode_step")
	core.PuregoSafeRegister(&xTransferEncodingFromString, libs, "camel_transfer_encoding_from_string")
	core.PuregoSafeRegister(&xTransferEncodingToString, libs, "camel_transfer_encoding_to_string")
	core.PuregoSafeRegister(&xUudecodeStep, libs, "camel_uudecode_step")
	core.PuregoSafeRegister(&xUuencodeClose, libs, "camel_uuencode_close")
	core.PuregoSafeRegister(&xUuencodeStep, libs, "camel_uuencode_step")

	core.PuregoSafeRegister(&xContentDispositionGLibType, libs, "camel_content_disposition_get_type")

	core.PuregoSafeRegister(&xNewContentDisposition, libs, "camel_content_disposition_new")

	core.PuregoSafeRegister(&xContentDispositionFormat, libs, "camel_content_disposition_format")
	core.PuregoSafeRegister(&xContentDispositionIsAttachment, libs, "camel_content_disposition_is_attachment")
	core.PuregoSafeRegister(&xContentDispositionIsAttachmentEx, libs, "camel_content_disposition_is_attachment_ex")
	core.PuregoSafeRegister(&xContentDispositionRef, libs, "camel_content_disposition_ref")
	core.PuregoSafeRegister(&xContentDispositionUnref, libs, "camel_content_disposition_unref")

	core.PuregoSafeRegister(&xContentTypeGLibType, libs, "camel_content_type_get_type")

	core.PuregoSafeRegister(&xNewContentType, libs, "camel_content_type_new")

	core.PuregoSafeRegister(&xContentTypeDump, libs, "camel_content_type_dump")
	core.PuregoSafeRegister(&xContentTypeFormat, libs, "camel_content_type_format")
	core.PuregoSafeRegister(&xContentTypeIs, libs, "camel_content_type_is")
	core.PuregoSafeRegister(&xContentTypeParam, libs, "camel_content_type_param")
	core.PuregoSafeRegister(&xContentTypeRef, libs, "camel_content_type_ref")
	core.PuregoSafeRegister(&xContentTypeSetParam, libs, "camel_content_type_set_param")
	core.PuregoSafeRegister(&xContentTypeSimple, libs, "camel_content_type_simple")
	core.PuregoSafeRegister(&xContentTypeUnref, libs, "camel_content_type_unref")

	core.PuregoSafeRegister(&xHeaderAddressGLibType, libs, "camel_header_address_get_type")

	core.PuregoSafeRegister(&xNewHeaderAddress, libs, "camel_header_address_new")
	core.PuregoSafeRegister(&xNewHeaderAddressGroup, libs, "camel_header_address_new_group")
	core.PuregoSafeRegister(&xNewHeaderAddressName, libs, "camel_header_address_new_name")

	core.PuregoSafeRegister(&xHeaderAddressAddMember, libs, "camel_header_address_add_member")
	core.PuregoSafeRegister(&xHeaderAddressRef, libs, "camel_header_address_ref")
	core.PuregoSafeRegister(&xHeaderAddressSetAddr, libs, "camel_header_address_set_addr")
	core.PuregoSafeRegister(&xHeaderAddressSetMembers, libs, "camel_header_address_set_members")
	core.PuregoSafeRegister(&xHeaderAddressSetName, libs, "camel_header_address_set_name")
	core.PuregoSafeRegister(&xHeaderAddressUnref, libs, "camel_header_address_unref")

}
