// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type MimeFilterGZipClassGType struct {
	_ structs.HostLayout

	ParentClass MimeFilterClassGType

	Reserved [20]uintptr
}

func (x *MimeFilterGZipClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type MimeFilterGZipPrivate struct {
	_ structs.HostLayout
}

func (x *MimeFilterGZipPrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type MimeFilterGZip struct {
	MimeFilter
}

var xMimeFilterGZipGLibType func() types.GType

func MimeFilterGZipGLibType() types.GType {
	return xMimeFilterGZipGLibType()
}

func MimeFilterGZipNewFromInternalPtr(ptr uintptr) *MimeFilterGZip {
	cls := &MimeFilterGZip{}
	cls.Ptr = ptr
	return cls
}

var xNewMimeFilterGZip func(MimeFilterGZipMode, int) uintptr

// Creates a new gzip (or gunzip) filter.
func NewMimeFilterGZip(ModeVar MimeFilterGZipMode, LevelVar int) *MimeFilterGZip {
	var cls *MimeFilterGZip

	cret := xNewMimeFilterGZip(ModeVar, LevelVar)

	if cret == 0 {
		return nil
	}
	cls = &MimeFilterGZip{}
	cls.Ptr = cret
	return cls
}

func (c *MimeFilterGZip) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *MimeFilterGZip) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xMimeFilterGZipGLibType, libs, "camel_mime_filter_gzip_get_type")

	core.PuregoSafeRegister(&xNewMimeFilterGZip, libs, "camel_mime_filter_gzip_new")

}
