// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gio"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type VeeFolderClassGType struct {
	_ structs.HostLayout

	ParentClass FolderClassGType

	Reserved [20]uintptr
}

func (x *VeeFolderClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type VeeFolderPrivate struct {
	_ structs.HostLayout
}

func (x *VeeFolderPrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type VeeFolder struct {
	Folder
}

var xVeeFolderGLibType func() types.GType

func VeeFolderGLibType() types.GType {
	return xVeeFolderGLibType()
}

func VeeFolderNewFromInternalPtr(ptr uintptr) *VeeFolder {
	cls := &VeeFolder{}
	cls.Ptr = ptr
	return cls
}

var xNewVeeFolder func(uintptr, string, uint32) uintptr

func NewVeeFolder(ParentStoreVar *Store, FullVar string, FlagsVar uint32) *VeeFolder {
	var cls *VeeFolder

	cret := xNewVeeFolder(ParentStoreVar.GoPointer(), FullVar, FlagsVar)

	if cret == 0 {
		return nil
	}
	cls = &VeeFolder{}
	cls.Ptr = cret
	return cls
}

var xVeeFolderAddFolderSync func(uintptr, uintptr, VeeFolderOpFlags, uintptr, **glib.Error) bool

// Adds @subfolder as a source folder to @vfolder.
func (x *VeeFolder) AddFolderSync(SubfolderVar *Folder, OpFlagsVar VeeFolderOpFlags, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xVeeFolderAddFolderSync(x.GoPointer(), SubfolderVar.GoPointer(), OpFlagsVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xVeeFolderConstruct func(uintptr, uint32)

// Initializes internal structures of the @vf. This is meant to be
// called by the descendants of #CamelVeeFolder.
func (x *VeeFolder) Construct(FlagsVar uint32) {

	xVeeFolderConstruct(x.GoPointer(), FlagsVar)

}

var xVeeFolderDupFolders func(uintptr) uintptr

// Returns a #GPtrArray of all folders of this @vfolder, which
// are used to populate it. These are in no particular order.
//
// Free the returned array with g_ptr_array_unref(), when no longer needed.
func (x *VeeFolder) DupFolders() uintptr {

	cret := xVeeFolderDupFolders(x.GoPointer())
	return cret
}

var xVeeFolderDupVeeUidFolder func(uintptr, string) uintptr

func (x *VeeFolder) DupVeeUidFolder(VeeMessageUidVar string) *Folder {
	var cls *Folder

	cret := xVeeFolderDupVeeUidFolder(x.GoPointer(), VeeMessageUidVar)

	if cret == 0 {
		return nil
	}
	cls = &Folder{}
	cls.Ptr = cret
	return cls
}

var xVeeFolderGetAutoUpdate func(uintptr) bool

func (x *VeeFolder) GetAutoUpdate() bool {

	cret := xVeeFolderGetAutoUpdate(x.GoPointer())
	return cret
}

var xVeeFolderGetExpression func(uintptr) string

func (x *VeeFolder) GetExpression() string {

	cret := xVeeFolderGetExpression(x.GoPointer())
	return cret
}

var xVeeFolderGetFlags func(uintptr) uint32

func (x *VeeFolder) GetFlags() uint32 {

	cret := xVeeFolderGetFlags(x.GoPointer())
	return cret
}

var xVeeFolderGetLocation func(uintptr, uintptr, *string) uintptr

// Find the real folder (and message info UID) for the given @vinfo.
// When the @realuid is not %NULL and it's set, then use g_free() to
// free it, when no longer needed.
func (x *VeeFolder) GetLocation(VinfoVar *VeeMessageInfo, RealuidVar *string) *Folder {
	var cls *Folder

	cret := xVeeFolderGetLocation(x.GoPointer(), VinfoVar.GoPointer(), RealuidVar)

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &Folder{}
	cls.Ptr = cret
	return cls
}

var xVeeFolderRemoveFolderSync func(uintptr, uintptr, VeeFolderOpFlags, uintptr, **glib.Error) bool

// Removed the source folder, @subfolder, from the virtual folder, @vfolder.
func (x *VeeFolder) RemoveFolderSync(SubfolderVar *Folder, OpFlagsVar VeeFolderOpFlags, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xVeeFolderRemoveFolderSync(x.GoPointer(), SubfolderVar.GoPointer(), OpFlagsVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xVeeFolderSetAutoUpdate func(uintptr, bool)

// Sets whether the @vfolder can automatically update when of its
// subfolders changes.
func (x *VeeFolder) SetAutoUpdate(AutoUpdateVar bool) {

	xVeeFolderSetAutoUpdate(x.GoPointer(), AutoUpdateVar)

}

var xVeeFolderSetExpressionSync func(uintptr, string, VeeFolderOpFlags, uintptr, **glib.Error) bool

// Sets an SExp expression to be used for this @vfolder
// and updates its content. The expression is not changed
// when the call fails.
func (x *VeeFolder) SetExpressionSync(ExpressionVar string, OpFlagsVar VeeFolderOpFlags, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xVeeFolderSetExpressionSync(x.GoPointer(), ExpressionVar, OpFlagsVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xVeeFolderSetFoldersSync func(uintptr, uintptr, VeeFolderOpFlags, uintptr, **glib.Error) bool

// Set the whole list of folder sources on a search folder.
func (x *VeeFolder) SetFoldersSync(FoldersVar uintptr, OpFlagsVar VeeFolderOpFlags, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := xVeeFolderSetFoldersSync(x.GoPointer(), FoldersVar, OpFlagsVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

func (c *VeeFolder) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *VeeFolder) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// SetPropertyAutoUpdate sets the "auto-update" property.
// Automatically update on change in source folders
func (x *VeeFolder) SetPropertyAutoUpdate(value bool) {
	var v gobject.Value
	v.Init(gobject.TypeBooleanVal)
	v.SetBoolean(value)
	x.SetProperty("auto-update", &v)
}

// GetPropertyAutoUpdate gets the "auto-update" property.
// Automatically update on change in source folders
func (x *VeeFolder) GetPropertyAutoUpdate() bool {
	var v gobject.Value
	x.GetProperty("auto-update", &v)
	return v.GetBoolean()
}

func (x *VeeFolder) ConnectVeeSetupChanged(cb *func(VeeFolder)) uint32 {
	cbPtr := uintptr(unsafe.Pointer(cb))
	if cbRefPtr, ok := glib.GetCallback(cbPtr); ok {
		return gobject.SignalConnect(x.GoPointer(), "vee-setup-changed", cbRefPtr)
	}

	fcb := func(clsPtr uintptr) {
		fa := VeeFolder{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)

	}
	cbRefPtr := purego.NewCallback(fcb)
	glib.SaveCallback(cbPtr, cbRefPtr)
	return gobject.SignalConnect(x.GoPointer(), "vee-setup-changed", cbRefPtr)
}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xVeeFolderGLibType, libs, "camel_vee_folder_get_type")

	core.PuregoSafeRegister(&xNewVeeFolder, libs, "camel_vee_folder_new")

	core.PuregoSafeRegister(&xVeeFolderAddFolderSync, libs, "camel_vee_folder_add_folder_sync")
	core.PuregoSafeRegister(&xVeeFolderConstruct, libs, "camel_vee_folder_construct")
	core.PuregoSafeRegister(&xVeeFolderDupFolders, libs, "camel_vee_folder_dup_folders")
	core.PuregoSafeRegister(&xVeeFolderDupVeeUidFolder, libs, "camel_vee_folder_dup_vee_uid_folder")
	core.PuregoSafeRegister(&xVeeFolderGetAutoUpdate, libs, "camel_vee_folder_get_auto_update")
	core.PuregoSafeRegister(&xVeeFolderGetExpression, libs, "camel_vee_folder_get_expression")
	core.PuregoSafeRegister(&xVeeFolderGetFlags, libs, "camel_vee_folder_get_flags")
	core.PuregoSafeRegister(&xVeeFolderGetLocation, libs, "camel_vee_folder_get_location")
	core.PuregoSafeRegister(&xVeeFolderRemoveFolderSync, libs, "camel_vee_folder_remove_folder_sync")
	core.PuregoSafeRegister(&xVeeFolderSetAutoUpdate, libs, "camel_vee_folder_set_auto_update")
	core.PuregoSafeRegister(&xVeeFolderSetExpressionSync, libs, "camel_vee_folder_set_expression_sync")
	core.PuregoSafeRegister(&xVeeFolderSetFoldersSync, libs, "camel_vee_folder_set_folders_sync")

}
