// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type NNTPAddressClassGType struct {
	_ structs.HostLayout

	ParentClass AddressClassGType

	Reserved [20]uintptr
}

func (x *NNTPAddressClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type NNTPAddressPrivate struct {
	_ structs.HostLayout
}

func (x *NNTPAddressPrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type NNTPAddress struct {
	Address
}

var xNNTPAddressGLibType func() types.GType

func NNTPAddressGLibType() types.GType {
	return xNNTPAddressGLibType()
}

func NNTPAddressNewFromInternalPtr(ptr uintptr) *NNTPAddress {
	cls := &NNTPAddress{}
	cls.Ptr = ptr
	return cls
}

var xNewNNTPAddress func() uintptr

// Create a new CamelNNTPAddress object.
func NewNNTPAddress() *NNTPAddress {
	var cls *NNTPAddress

	cret := xNewNNTPAddress()

	if cret == 0 {
		return nil
	}
	cls = &NNTPAddress{}
	cls.Ptr = cret
	return cls
}

var xNNTPAddressAdd func(uintptr, string) int

// Add a new nntp address to the address object.  Duplicates are not added twice.
func (x *NNTPAddress) Add(NameVar string) int {

	cret := xNNTPAddressAdd(x.GoPointer(), NameVar)
	return cret
}

var xNNTPAddressGet func(uintptr, int, string) bool

// Get the address at @index.
func (x *NNTPAddress) Get(IndexVar int, NamepVar string) bool {

	cret := xNNTPAddressGet(x.GoPointer(), IndexVar, NamepVar)
	return cret
}

func (c *NNTPAddress) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *NNTPAddress) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xNNTPAddressGLibType, libs, "camel_nntp_address_get_type")

	core.PuregoSafeRegister(&xNewNNTPAddress, libs, "camel_nntp_address_new")

	core.PuregoSafeRegister(&xNNTPAddressAdd, libs, "camel_nntp_address_add")
	core.PuregoSafeRegister(&xNNTPAddressGet, libs, "camel_nntp_address_get")

}
