// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gio"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

// A callback called for each found file in the cache, used
// by camel_data_cache_foreach_remove(). The @filename corresponds
// to the result of camel_data_cache_get_filename().
type DataCacheRemoveFunc func(uintptr, string, uintptr) bool

type DataCacheClassGType struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClassGType

	Reserved [20]uintptr
}

func (x *DataCacheClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type DataCachePrivate struct {
	_ structs.HostLayout
}

func (x *DataCachePrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type DataCache struct {
	gobject.Object
}

var xDataCacheGLibType func() types.GType

func DataCacheGLibType() types.GType {
	return xDataCacheGLibType()
}

func DataCacheNewFromInternalPtr(ptr uintptr) *DataCache {
	cls := &DataCache{}
	cls.Ptr = ptr
	return cls
}

var xNewDataCache func(string, **glib.Error) uintptr

// Create a new data cache.
func NewDataCache(PathVar string) (*DataCache, error) {
	var cls *DataCache
	var cerr *glib.Error

	cret := xNewDataCache(PathVar, &cerr)

	if cret == 0 {
		return nil, cerr
	}
	cls = &DataCache{}
	cls.Ptr = cret
	if cerr == nil {
		return cls, nil
	}
	return cls, cerr

}

var xDataCacheAdd func(uintptr, string, string, **glib.Error) uintptr

// Add a new item to the cache, returning a #GIOStream to the new item.
//
// The key and the path combine to form a unique key used to store the item.
//
// Potentially, expiry processing will be performed while this call is
// executing.
//
// The returned #GIOStream is referenced for thread-safety and must be
// unreferenced with g_object_unref() when finished with it.
func (x *DataCache) Add(PathVar string, KeyVar string) (*gio.IOStream, error) {
	var cls *gio.IOStream
	var cerr *glib.Error

	cret := xDataCacheAdd(x.GoPointer(), PathVar, KeyVar, &cerr)

	if cret == 0 {
		return nil, cerr
	}
	cls = &gio.IOStream{}
	cls.Ptr = cret
	if cerr == nil {
		return cls, nil
	}
	return cls, cerr

}

var xDataCacheClear func(uintptr, string)

// Clear cache's content in @path.
func (x *DataCache) Clear(PathVar string) {

	xDataCacheClear(x.GoPointer(), PathVar)

}

var xDataCacheForeachRemove func(uintptr, string, uintptr, uintptr)

// Traverses the @cdc sub-cache identified by @path and calls @func for each found file.
// If the @func returns %TRUE, then the file is removed, if %FALSE, it's kept in the cache.
func (x *DataCache) ForeachRemove(PathVar string, FuncVar *DataCacheRemoveFunc, UserDataVar uintptr) {

	xDataCacheForeachRemove(x.GoPointer(), PathVar, glib.NewCallback(FuncVar), UserDataVar)

}

var xDataCacheGet func(uintptr, string, string, **glib.Error) uintptr

// Lookup an item in the cache.  If the item exists, a #GIOStream is returned
// for the item.  The stream may be shared by multiple callers, so ensure the
// stream is in a valid state through external locking.
//
// The returned #GIOStream is referenced for thread-safety and must be
// unreferenced with g_object_unref() when finished with it.
func (x *DataCache) Get(PathVar string, KeyVar string) (*gio.IOStream, error) {
	var cls *gio.IOStream
	var cerr *glib.Error

	cret := xDataCacheGet(x.GoPointer(), PathVar, KeyVar, &cerr)

	if cret == 0 {
		return nil, cerr
	}
	cls = &gio.IOStream{}
	cls.Ptr = cret
	if cerr == nil {
		return cls, nil
	}
	return cls, cerr

}

var xDataCacheGetExpireEnabled func(uintptr) bool

// Gets whether expire of cache data is enabled.
//
// This is a complementary property for camel_data_cache_set_expire_age()
// and camel_data_cache_set_expire_access(), which allows to disable expiry
// without touching the two values. Having expire enabled, but not have set
// any of the two times, still behaves like not having expiry enabled.
func (x *DataCache) GetExpireEnabled() bool {

	cret := xDataCacheGetExpireEnabled(x.GoPointer())
	return cret
}

var xDataCacheGetFilename func(uintptr, string, string) string

// Lookup the filename for an item in the cache
func (x *DataCache) GetFilename(PathVar string, KeyVar string) string {

	cret := xDataCacheGetFilename(x.GoPointer(), PathVar, KeyVar)
	return cret
}

var xDataCacheGetPath func(uintptr) string

// Returns the path to the data cache.
func (x *DataCache) GetPath() string {

	cret := xDataCacheGetPath(x.GoPointer())
	return cret
}

var xDataCacheRemove func(uintptr, string, string, **glib.Error) int

// Remove/expire a cache item.
func (x *DataCache) Remove(PathVar string, KeyVar string) (int, error) {
	var cerr *glib.Error

	cret := xDataCacheRemove(x.GoPointer(), PathVar, KeyVar, &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xDataCacheSetExpireAccess func(uintptr, int)

// Set the cache expiration policy for access times.
//
// Items in the cache which haven't been accessed for @when
// seconds may be expired at any time.  Items are expired in a lazy
// manner, so it is indeterminate when the items will
// physically be removed.
//
// Note you can set both an age and an access limit.  The
// age acts as a hard limit on cache entries.
func (x *DataCache) SetExpireAccess(WhenVar int) {

	xDataCacheSetExpireAccess(x.GoPointer(), WhenVar)

}

var xDataCacheSetExpireAge func(uintptr, int)

// Set the cache expiration policy for aged entries.
//
// Items in the cache older than @when seconds may be
// flushed at any time.  Items are expired in a lazy
// manner, so it is indeterminate when the items will
// physically be removed.
//
// Note you can set both an age and an access limit.  The
// age acts as a hard limit on cache entries.
func (x *DataCache) SetExpireAge(WhenVar int) {

	xDataCacheSetExpireAge(x.GoPointer(), WhenVar)

}

var xDataCacheSetExpireEnabled func(uintptr, bool)

// Sets whether expire of cache data is enabled.
//
// This is a complementary property for camel_data_cache_set_expire_age()
// and camel_data_cache_set_expire_access(), which allows to disable expiry
// without touching the two values. Having expire enabled, but not have set
// any of the two times, still behaves like not having expiry enabled.
func (x *DataCache) SetExpireEnabled(ExpireEnabledVar bool) {

	xDataCacheSetExpireEnabled(x.GoPointer(), ExpireEnabledVar)

}

var xDataCacheSetPath func(uintptr, string)

// Sets the path to the data cache.
func (x *DataCache) SetPath(PathVar string) {

	xDataCacheSetPath(x.GoPointer(), PathVar)

}

func (c *DataCache) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *DataCache) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// SetPropertyExpireEnabled sets the "expire-enabled" property.
// Expire Enabled
func (x *DataCache) SetPropertyExpireEnabled(value bool) {
	var v gobject.Value
	v.Init(gobject.TypeBooleanVal)
	v.SetBoolean(value)
	x.SetProperty("expire-enabled", &v)
}

// GetPropertyExpireEnabled gets the "expire-enabled" property.
// Expire Enabled
func (x *DataCache) GetPropertyExpireEnabled() bool {
	var v gobject.Value
	x.GetProperty("expire-enabled", &v)
	return v.GetBoolean()
}

// SetPropertyPath sets the "path" property.
// Path
func (x *DataCache) SetPropertyPath(value string) {
	var v gobject.Value
	v.Init(gobject.TypeStringVal)
	v.SetString(value)
	x.SetProperty("path", &v)
}

// GetPropertyPath gets the "path" property.
// Path
func (x *DataCache) GetPropertyPath() string {
	var v gobject.Value
	x.GetProperty("path", &v)
	return v.GetString()
}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xDataCacheGLibType, libs, "camel_data_cache_get_type")

	core.PuregoSafeRegister(&xNewDataCache, libs, "camel_data_cache_new")

	core.PuregoSafeRegister(&xDataCacheAdd, libs, "camel_data_cache_add")
	core.PuregoSafeRegister(&xDataCacheClear, libs, "camel_data_cache_clear")
	core.PuregoSafeRegister(&xDataCacheForeachRemove, libs, "camel_data_cache_foreach_remove")
	core.PuregoSafeRegister(&xDataCacheGet, libs, "camel_data_cache_get")
	core.PuregoSafeRegister(&xDataCacheGetExpireEnabled, libs, "camel_data_cache_get_expire_enabled")
	core.PuregoSafeRegister(&xDataCacheGetFilename, libs, "camel_data_cache_get_filename")
	core.PuregoSafeRegister(&xDataCacheGetPath, libs, "camel_data_cache_get_path")
	core.PuregoSafeRegister(&xDataCacheRemove, libs, "camel_data_cache_remove")
	core.PuregoSafeRegister(&xDataCacheSetExpireAccess, libs, "camel_data_cache_set_expire_access")
	core.PuregoSafeRegister(&xDataCacheSetExpireAge, libs, "camel_data_cache_set_expire_age")
	core.PuregoSafeRegister(&xDataCacheSetExpireEnabled, libs, "camel_data_cache_set_expire_enabled")
	core.PuregoSafeRegister(&xDataCacheSetPath, libs, "camel_data_cache_set_path")

}
