// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gio"
	"github.com/jwijenbergh/puregotk/v4/gobject"
)

// Contains only private data that should be read and manipulated using the
// functions below.
type AsyncClosure struct {
	_ structs.HostLayout
}

func (x *AsyncClosure) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xAsyncClosureFree func(uintptr)

// Frees the @closure and the resources it holds.
func (x *AsyncClosure) Free() {

	xAsyncClosureFree(x.GoPointer())

}

var xAsyncClosureWait func(uintptr) uintptr

// Call this function immediately after starting an asynchronous operation.
// The function waits for the asynchronous operation to complete and returns
// its #GAsyncResult to be passed to the operation's "finish" function.
//
// This function can be called repeatedly on the same #CamelAsyncClosure to
// easily string together multiple asynchronous operations.
func (x *AsyncClosure) Wait() *gio.AsyncResultBase {
	var cls *gio.AsyncResultBase

	cret := xAsyncClosureWait(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &gio.AsyncResultBase{}
	cls.Ptr = cret
	return cls
}

var xAsyncClosureCallback func(uintptr, uintptr, uintptr)

// Pass this function as the #GAsyncReadyCallback argument of an asynchronous
// function, and the #CamelAsyncClosure as the data argument.
//
// This causes camel_async_closure_wait() to terminate and return @result.
func AsyncClosureCallback(SourceObjectVar *gobject.Object, ResultVar gio.AsyncResult, ClosureVar uintptr) {

	xAsyncClosureCallback(SourceObjectVar.GoPointer(), ResultVar.GoPointer(), ClosureVar)

}

var xAsyncClosureNew func() *AsyncClosure

// Creates a new #CamelAsyncClosure for use with asynchronous functions.
func AsyncClosureNew() *AsyncClosure {

	cret := xAsyncClosureNew()
	return cret
}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xAsyncClosureCallback, libs, "camel_async_closure_callback")
	core.PuregoSafeRegister(&xAsyncClosureNew, libs, "camel_async_closure_new")

	core.PuregoSafeRegister(&xAsyncClosureFree, libs, "camel_async_closure_free")
	core.PuregoSafeRegister(&xAsyncClosureWait, libs, "camel_async_closure_wait")

}
