// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
)

var xHostnameUtilsHostIsInDomain func(string, string) bool

// Check whether the hostname @host is equal to or a subdomain of @domain.
// Both @host and @domain are UTF-8 strings and can be IDNs (which will be
// punycode-encoded for comparison).
func HostnameUtilsHostIsInDomain(HostVar string, DomainVar string) bool {

	cret := xHostnameUtilsHostIsInDomain(HostVar, DomainVar)
	return cret
}

var xHostnameUtilsRequiresAscii func(string) bool

// Check whether the @hostname requires conversion to ASCII. That can
// be when a character in it can look like an ASCII character, even
// it being a Unicode letter. This can be used to display host names
// in a way of invulnerable to IDN homograph attacks.
func HostnameUtilsRequiresAscii(HostnameVar string) bool {

	cret := xHostnameUtilsRequiresAscii(HostnameVar)
	return cret
}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xHostnameUtilsHostIsInDomain, libs, "camel_hostname_utils_host_is_in_domain")
	core.PuregoSafeRegister(&xHostnameUtilsRequiresAscii, libs, "camel_hostname_utils_requires_ascii")

}
