// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
)

type Msg struct {
	_ structs.HostLayout

	ReplyPort *MsgPort

	Flags int32
}

func (x *Msg) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xMsgOrtReply func(uintptr)

func (x *Msg) OrtReply() {

	xMsgOrtReply(x.GoPointer())

}

type MsgPort struct {
	_ structs.HostLayout
}

func (x *MsgPort) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xMsgportDestroy func(*MsgPort)

func MsgportDestroy(MsgportVar *MsgPort) {

	xMsgportDestroy(MsgportVar)

}

var xMsgportFd func(*MsgPort) int

func MsgportFd(MsgportVar *MsgPort) int {

	cret := xMsgportFd(MsgportVar)
	return cret
}

var xMsgportNew func() *MsgPort

func MsgportNew() *MsgPort {

	cret := xMsgportNew()
	return cret
}

var xMsgportPop func(*MsgPort) *Msg

func MsgportPop(MsgportVar *MsgPort) *Msg {

	cret := xMsgportPop(MsgportVar)
	return cret
}

var xMsgportPrfd func(*MsgPort) uintptr

func MsgportPrfd(MsgportVar *MsgPort) uintptr {

	cret := xMsgportPrfd(MsgportVar)
	return cret
}

var xMsgportPush func(*MsgPort, *Msg)

func MsgportPush(MsgportVar *MsgPort, MsgVar *Msg) {

	xMsgportPush(MsgportVar, MsgVar)

}

var xMsgportReply func(*Msg)

func MsgportReply(MsgVar *Msg) {

	xMsgportReply(MsgVar)

}

var xMsgportTimeoutPop func(*MsgPort, uint64) *Msg

func MsgportTimeoutPop(MsgportVar *MsgPort, TimeoutVar uint64) *Msg {

	cret := xMsgportTimeoutPop(MsgportVar, TimeoutVar)
	return cret
}

var xMsgportTryPop func(*MsgPort) *Msg

func MsgportTryPop(MsgportVar *MsgPort) *Msg {

	cret := xMsgportTryPop(MsgportVar)
	return cret
}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xMsgportDestroy, libs, "camel_msgport_destroy")
	core.PuregoSafeRegister(&xMsgportFd, libs, "camel_msgport_fd")
	core.PuregoSafeRegister(&xMsgportNew, libs, "camel_msgport_new")
	core.PuregoSafeRegister(&xMsgportPop, libs, "camel_msgport_pop")
	core.PuregoSafeRegister(&xMsgportPrfd, libs, "camel_msgport_prfd")
	core.PuregoSafeRegister(&xMsgportPush, libs, "camel_msgport_push")
	core.PuregoSafeRegister(&xMsgportReply, libs, "camel_msgport_reply")
	core.PuregoSafeRegister(&xMsgportTimeoutPop, libs, "camel_msgport_timeout_pop")
	core.PuregoSafeRegister(&xMsgportTryPop, libs, "camel_msgport_try_pop")

	core.PuregoSafeRegister(&xMsgOrtReply, libs, "camel_msgport_reply")

}
