// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type NamedFlags struct {
	_ structs.HostLayout
}

var xNamedFlagsGLibType func() types.GType

func NamedFlagsGLibType() types.GType {
	return xNamedFlagsGLibType()
}

func (x *NamedFlags) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xNewNamedFlags func() *NamedFlags

// Creates a new #CamelNamedFlags.
func NewNamedFlags() *NamedFlags {

	cret := xNewNamedFlags()
	return cret
}

var xNewNamedFlagsSized func(uint) *NamedFlags

// Created a new #CamelNamedFlags, which has reserved @reserve_size
// elements. This value doesn't influence the camel_named_flags_get_length(),
// which returns zero on the array returned from this function.
func NewNamedFlagsSized(ReserveSizeVar uint) *NamedFlags {

	cret := xNewNamedFlagsSized(ReserveSizeVar)
	return cret
}

var xNamedFlagsClear func(uintptr)

// Removes all the elements of the array.
func (x *NamedFlags) Clear() {

	xNamedFlagsClear(x.GoPointer())

}

var xNamedFlagsContains func(uintptr, string) bool

func (x *NamedFlags) Contains(NameVar string) bool {

	cret := xNamedFlagsContains(x.GoPointer(), NameVar)
	return cret
}

var xNamedFlagsCopy func(uintptr) *NamedFlags

// Creates a copy of the @named_flags and returns it.
func (x *NamedFlags) Copy() *NamedFlags {

	cret := xNamedFlagsCopy(x.GoPointer())
	return cret
}

var xNamedFlagsEqual func(uintptr, *NamedFlags) bool

// Compares content of the two #CamelNamedFlags and returns whether
// they equal. Note this is an expensive operation for large sets.
func (x *NamedFlags) Equal(NamedFlagsBVar *NamedFlags) bool {

	cret := xNamedFlagsEqual(x.GoPointer(), NamedFlagsBVar)
	return cret
}

var xNamedFlagsFree func(uintptr)

// Frees memory associated iwth the @named_flags. Does nothing,
// if @named_flags is %NULL.
func (x *NamedFlags) Free() {

	xNamedFlagsFree(x.GoPointer())

}

var xNamedFlagsGet func(uintptr, uint) string

func (x *NamedFlags) Get(IndexVar uint) string {

	cret := xNamedFlagsGet(x.GoPointer(), IndexVar)
	return cret
}

var xNamedFlagsGetLength func(uintptr) uint

func (x *NamedFlags) GetLength() uint {

	cret := xNamedFlagsGetLength(x.GoPointer())
	return cret
}

var xNamedFlagsInsert func(uintptr, string) bool

// Inserts a flag named @name into the @named_flags, if it is not included
// already (comparing case sensitively), or does nothing otherwise.
func (x *NamedFlags) Insert(NameVar string) bool {

	cret := xNamedFlagsInsert(x.GoPointer(), NameVar)
	return cret
}

var xNamedFlagsRemove func(uintptr, string) bool

// Removes a flag named @name from the @named_flags.
func (x *NamedFlags) Remove(NameVar string) bool {

	cret := xNamedFlagsRemove(x.GoPointer(), NameVar)
	return cret
}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xNamedFlagsGLibType, libs, "camel_named_flags_get_type")

	core.PuregoSafeRegister(&xNewNamedFlags, libs, "camel_named_flags_new")
	core.PuregoSafeRegister(&xNewNamedFlagsSized, libs, "camel_named_flags_new_sized")

	core.PuregoSafeRegister(&xNamedFlagsClear, libs, "camel_named_flags_clear")
	core.PuregoSafeRegister(&xNamedFlagsContains, libs, "camel_named_flags_contains")
	core.PuregoSafeRegister(&xNamedFlagsCopy, libs, "camel_named_flags_copy")
	core.PuregoSafeRegister(&xNamedFlagsEqual, libs, "camel_named_flags_equal")
	core.PuregoSafeRegister(&xNamedFlagsFree, libs, "camel_named_flags_free")
	core.PuregoSafeRegister(&xNamedFlagsGet, libs, "camel_named_flags_get")
	core.PuregoSafeRegister(&xNamedFlagsGetLength, libs, "camel_named_flags_get_length")
	core.PuregoSafeRegister(&xNamedFlagsInsert, libs, "camel_named_flags_insert")
	core.PuregoSafeRegister(&xNamedFlagsRemove, libs, "camel_named_flags_remove")

}
