// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type MimeFilterYencClassGType struct {
	_ structs.HostLayout

	ParentClass MimeFilterClassGType

	Reserved [20]uintptr
}

func (x *MimeFilterYencClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type MimeFilterYencPrivate struct {
	_ structs.HostLayout
}

func (x *MimeFilterYencPrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

const (
	MIME_YDECODE_STATE_BEGIN int = 4096

	MIME_YDECODE_STATE_DECODE int = 16384

	MIME_YDECODE_STATE_END int = 32768

	MIME_YDECODE_STATE_EOLN int = 256

	MIME_YDECODE_STATE_ESCAPE int = 512

	MIME_YDECODE_STATE_INIT int = 0

	MIME_YDECODE_STATE_PART int = 8192

	MIME_YENCODE_CRC_INIT int = -1

	MIME_YENCODE_STATE_INIT int = 0
)

var xYdecodeStep func([]byte, uint, *[]byte, *int, *uint32, *uint32) uint

// Performs a 'decode step' on a chunk of yEncoded data of length
// @inlen pointed to by @in and writes to @out. Assumes the =ybegin
// and =ypart lines have already been stripped off.
//
// To get the crc32 value of the part, use #CAMEL_MIME_YENCODE_CRC_FINAL
// (@pcrc). If there are more parts, you should reuse @crc without
// re-initializing. Once all parts have been decoded, you may get the
// combined crc32 value of all the parts using #CAMEL_MIME_YENCODE_CRC_FINAL
// (@crc).
func YdecodeStep(InVar []byte, InlenVar uint, OutVar *[]byte, StateVar *int, PcrcVar *uint32, CrcVar *uint32) uint {

	cret := xYdecodeStep(InVar, InlenVar, OutVar, StateVar, PcrcVar, CrcVar)
	return cret
}

var xYencodeClose func([]byte, uint, *[]byte, *int, *uint32, *uint32) uint

// Call this function when finished encoding data with
// camel_yencode_step() to flush off the remaining state.
//
// #CAMEL_MIME_YENCODE_CRC_FINAL (@pcrc) will give you the crc32 of the
// encoded "part". If there are more "parts" to encode, you should
// re-use @crc when encoding the next "parts" and then use
// #CAMEL_MIME_YENCODE_CRC_FINAL (@crc) to get the combined crc32 value of
// all the parts.
func YencodeClose(InVar []byte, InlenVar uint, OutVar *[]byte, StateVar *int, PcrcVar *uint32, CrcVar *uint32) uint {

	cret := xYencodeClose(InVar, InlenVar, OutVar, StateVar, PcrcVar, CrcVar)
	return cret
}

var xYencodeStep func([]byte, uint, *[]byte, *int, *uint32, *uint32) uint

// Performs an yEncode 'encode step' on a chunk of raw data of length
// @inlen pointed to by @in and writes to @out.
//
// @state should be initialized to #CAMEL_MIME_YENCODE_STATE_INIT before
// beginning making the first call to this function. Subsequent calls
// should reuse @state.
//
// Along the same lines, @pcrc and @crc should be initialized to
// #CAMEL_MIME_YENCODE_CRC_INIT before using.
func YencodeStep(InVar []byte, InlenVar uint, OutVar *[]byte, StateVar *int, PcrcVar *uint32, CrcVar *uint32) uint {

	cret := xYencodeStep(InVar, InlenVar, OutVar, StateVar, PcrcVar, CrcVar)
	return cret
}

type MimeFilterYenc struct {
	MimeFilter
}

var xMimeFilterYencGLibType func() types.GType

func MimeFilterYencGLibType() types.GType {
	return xMimeFilterYencGLibType()
}

func MimeFilterYencNewFromInternalPtr(ptr uintptr) *MimeFilterYenc {
	cls := &MimeFilterYenc{}
	cls.Ptr = ptr
	return cls
}

var xNewMimeFilterYenc func(MimeFilterYencDirection) uintptr

// Create a new #CamelMimeFilterYenc filter object.
func NewMimeFilterYenc(DirectionVar MimeFilterYencDirection) *MimeFilterYenc {
	var cls *MimeFilterYenc

	cret := xNewMimeFilterYenc(DirectionVar)

	if cret == 0 {
		return nil
	}
	cls = &MimeFilterYenc{}
	cls.Ptr = cret
	return cls
}

var xMimeFilterYencGetCrc func(uintptr) uint32

// Get the computed crc or (#guint32) -1 on fail.
func (x *MimeFilterYenc) GetCrc() uint32 {

	cret := xMimeFilterYencGetCrc(x.GoPointer())
	return cret
}

var xMimeFilterYencGetPcrc func(uintptr) uint32

// Get the computed part crc or (#guint32) -1 on fail.
func (x *MimeFilterYenc) GetPcrc() uint32 {

	cret := xMimeFilterYencGetPcrc(x.GoPointer())
	return cret
}

var xMimeFilterYencSetCrc func(uintptr, uint32)

// Sets the current crc32 value on the yEnc filter @yenc to @crc.
func (x *MimeFilterYenc) SetCrc(CrcVar uint32) {

	xMimeFilterYencSetCrc(x.GoPointer(), CrcVar)

}

var xMimeFilterYencSetState func(uintptr, int)

// Sets the current state of the yencoder/ydecoder
func (x *MimeFilterYenc) SetState(StateVar int) {

	xMimeFilterYencSetState(x.GoPointer(), StateVar)

}

func (c *MimeFilterYenc) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *MimeFilterYenc) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xYdecodeStep, libs, "camel_ydecode_step")
	core.PuregoSafeRegister(&xYencodeClose, libs, "camel_yencode_close")
	core.PuregoSafeRegister(&xYencodeStep, libs, "camel_yencode_step")

	core.PuregoSafeRegister(&xMimeFilterYencGLibType, libs, "camel_mime_filter_yenc_get_type")

	core.PuregoSafeRegister(&xNewMimeFilterYenc, libs, "camel_mime_filter_yenc_new")

	core.PuregoSafeRegister(&xMimeFilterYencGetCrc, libs, "camel_mime_filter_yenc_get_crc")
	core.PuregoSafeRegister(&xMimeFilterYencGetPcrc, libs, "camel_mime_filter_yenc_get_pcrc")
	core.PuregoSafeRegister(&xMimeFilterYencSetCrc, libs, "camel_mime_filter_yenc_set_crc")
	core.PuregoSafeRegister(&xMimeFilterYencSetState, libs, "camel_mime_filter_yenc_set_state")

}
