// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type WeakRefGroup struct {
	_ structs.HostLayout
}

var xWeakRefGroupGLibType func() types.GType

func WeakRefGroupGLibType() types.GType {
	return xWeakRefGroupGLibType()
}

func (x *WeakRefGroup) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xNewWeakRefGroup func() *WeakRefGroup

func NewWeakRefGroup() *WeakRefGroup {

	cret := xNewWeakRefGroup()
	return cret
}

var xWeakRefGroupGet func(uintptr) uintptr

func (x *WeakRefGroup) Get() uintptr {

	cret := xWeakRefGroupGet(x.GoPointer())
	return cret
}

var xWeakRefGroupRef func(uintptr) *WeakRefGroup

// Increases a reference count of the @group.
func (x *WeakRefGroup) Ref() *WeakRefGroup {

	cret := xWeakRefGroupRef(x.GoPointer())
	return cret
}

var xWeakRefGroupSet func(uintptr, uintptr)

// Sets the @object as the object help by this @group. If
// the @object is %NULL, then unsets any previously set.
func (x *WeakRefGroup) Set(ObjectVar uintptr) {

	xWeakRefGroupSet(x.GoPointer(), ObjectVar)

}

var xWeakRefGroupUnref func(uintptr)

// Decreases a reference count of the @group. The @group is
// freed when the reference count reaches zero.
func (x *WeakRefGroup) Unref() {

	xWeakRefGroupUnref(x.GoPointer())

}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xWeakRefGroupGLibType, libs, "camel_weak_ref_group_get_type")

	core.PuregoSafeRegister(&xNewWeakRefGroup, libs, "camel_weak_ref_group_new")

	core.PuregoSafeRegister(&xWeakRefGroupGet, libs, "camel_weak_ref_group_get")
	core.PuregoSafeRegister(&xWeakRefGroupRef, libs, "camel_weak_ref_group_ref")
	core.PuregoSafeRegister(&xWeakRefGroupSet, libs, "camel_weak_ref_group_set")
	core.PuregoSafeRegister(&xWeakRefGroupUnref, libs, "camel_weak_ref_group_unref")

}
