// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type SaslXOAuth2GoogleClassGType struct {
	_ structs.HostLayout

	ParentClass SaslXOAuth2ClassGType
}

func (x *SaslXOAuth2GoogleClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type SaslXOAuth2GooglePrivate struct {
	_ structs.HostLayout
}

func (x *SaslXOAuth2GooglePrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type SaslXOAuth2Google struct {
	SaslXOAuth2
}

var xSaslXOAuth2GoogleGLibType func() types.GType

func SaslXOAuth2GoogleGLibType() types.GType {
	return xSaslXOAuth2GoogleGLibType()
}

func SaslXOAuth2GoogleNewFromInternalPtr(ptr uintptr) *SaslXOAuth2Google {
	cls := &SaslXOAuth2Google{}
	cls.Ptr = ptr
	return cls
}

func (c *SaslXOAuth2Google) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *SaslXOAuth2Google) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}
