// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gio"
	"github.com/jwijenbergh/puregotk/v4/glib"
)

const (
	AI_CANONNAME int = 2

	AI_NUMERICHOST int = 4

	EAI_ADDRFAMILY int = -9

	EAI_AGAIN int = -3

	EAI_BADFLAGS int = -1

	EAI_FAIL int = -4

	EAI_FAMILY int = -6

	EAI_MEMORY int = -10

	EAI_NODATA int = -5

	EAI_NONAME int = -2

	EAI_OVERFLOW int = -12

	EAI_SERVICE int = -8

	EAI_SOCKTYPE int = -7

	EAI_SYSTEM int = -11

	NI_DGRAM int = 16

	NI_NAMEREQD int = 8

	NI_NOFQDN int = 4

	NI_NUMERICHOST int = 1

	NI_NUMERICSERV int = 2
)

var xFreeaddrinfo func(uintptr)

// Frees a structure returned with camel_getaddrinfo(). It does
// nothing when the @host is %NULL.
func Freeaddrinfo(HostVar uintptr) {

	xFreeaddrinfo(HostVar)

}

var xGetaddrinfo func(string, string, uintptr, uintptr, **glib.Error) uintptr

// Resolves a host @name and returns an information about its address.
func Getaddrinfo(NameVar string, ServiceVar string, HintsVar uintptr, CancellableVar *gio.Cancellable) (uintptr, error) {
	var cerr *glib.Error

	cret := xGetaddrinfo(NameVar, ServiceVar, HintsVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xHostIdnaToAscii func(string) string

// Converts IDN (Internationalized Domain Name) into ASCII representation.
// If there's a failure or the @host has only ASCII letters, then a copy
// of @host is returned.
func HostIdnaToAscii(HostVar string) string {

	cret := xHostIdnaToAscii(HostVar)
	return cret
}

var xUtilsSanitizeAsciiDomainInAddress func(string, bool) string

// Checks whether the domain in the @email_address requires
// conversion to ASCII and if it does it also converts it.
// When the @do_format is %TRUE, the output string is formatted
// for display, otherwise it's encoded for use in the message
// headers. A %NULL is returned when no conversion was needed.
func UtilsSanitizeAsciiDomainInAddress(EmailAddressVar string, DoFormatVar bool) string {

	cret := xUtilsSanitizeAsciiDomainInAddress(EmailAddressVar, DoFormatVar)
	return cret
}

var xUtilsSanitizeAsciiDomainInUrl func(*URL) bool

// Checks whether the host name of the @url requires conversion
// to ASCII and converts it, if needed.
func UtilsSanitizeAsciiDomainInUrl(UrlVar *URL) bool {

	cret := xUtilsSanitizeAsciiDomainInUrl(UrlVar)
	return cret
}

var xUtilsSanitizeAsciiDomainInUrlStr func(string) string

// Checks whether the host name of the @url_str requires conversion
// to ASCII and converts it if needed. Returns %NULL, when no conversion
// was required.
func UtilsSanitizeAsciiDomainInUrlStr(UrlStrVar string) string {

	cret := xUtilsSanitizeAsciiDomainInUrlStr(UrlStrVar)
	return cret
}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xFreeaddrinfo, libs, "camel_freeaddrinfo")
	core.PuregoSafeRegister(&xGetaddrinfo, libs, "camel_getaddrinfo")
	core.PuregoSafeRegister(&xHostIdnaToAscii, libs, "camel_host_idna_to_ascii")
	core.PuregoSafeRegister(&xUtilsSanitizeAsciiDomainInAddress, libs, "camel_utils_sanitize_ascii_domain_in_address")
	core.PuregoSafeRegister(&xUtilsSanitizeAsciiDomainInUrl, libs, "camel_utils_sanitize_ascii_domain_in_url")
	core.PuregoSafeRegister(&xUtilsSanitizeAsciiDomainInUrlStr, libs, "camel_utils_sanitize_ascii_domain_in_url_str")

}
