// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/glib"
)

var xMovemail func(string, string, **glib.Error) int

// This copies an mbox file from a shared directory with multiple
// readers and writers into a private (presumably Camel-controlled)
// directory. Dot locking is used on the source file (but not the
// destination).
func Movemail(SourceVar string, DestVar string) (int, error) {
	var cerr *glib.Error

	cret := xMovemail(SourceVar, DestVar, &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xMovemail, libs, "camel_movemail")

}
