// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
)

type Charset struct {
	_ structs.HostLayout

	Mask uint32

	Level int32
}

func (x *Charset) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xCharsetBestName func(uintptr) string

func (x *Charset) BestName() string {

	cret := xCharsetBestName(x.GoPointer())
	return cret
}

var xCharsetInit func(uintptr)

func (x *Charset) Init() {

	xCharsetInit(x.GoPointer())

}

var xCharsetStep func(uintptr, []byte, int)

// Processes more input text with the @cc.
func (x *Charset) Step(InVar []byte, LenVar int) {

	xCharsetStep(x.GoPointer(), InVar, LenVar)

}

var xCharsetBest func([]byte, int) string

// Finds the minimum charset for this string NULL means US-ASCII.
func CharsetBest(InVar []byte, LenVar int) string {

	cret := xCharsetBest(InVar, LenVar)
	return cret
}

var xCharsetIsoToWindows func(string) string

func CharsetIsoToWindows(IsocharsetVar string) string {

	cret := xCharsetIsoToWindows(IsocharsetVar)
	return cret
}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xCharsetBest, libs, "camel_charset_best")
	core.PuregoSafeRegister(&xCharsetIsoToWindows, libs, "camel_charset_iso_to_windows")

	core.PuregoSafeRegister(&xCharsetBestName, libs, "camel_charset_best_name")
	core.PuregoSafeRegister(&xCharsetInit, libs, "camel_charset_init")
	core.PuregoSafeRegister(&xCharsetStep, libs, "camel_charset_step")

}
