// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type MultipartEncryptedClassGType struct {
	_ structs.HostLayout

	ParentClass MultipartClassGType

	Reserved [20]uintptr
}

func (x *MultipartEncryptedClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type MultipartEncryptedPrivate struct {
	_ structs.HostLayout
}

func (x *MultipartEncryptedPrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type MultipartEncrypted struct {
	Multipart
}

var xMultipartEncryptedGLibType func() types.GType

func MultipartEncryptedGLibType() types.GType {
	return xMultipartEncryptedGLibType()
}

func MultipartEncryptedNewFromInternalPtr(ptr uintptr) *MultipartEncrypted {
	cls := &MultipartEncrypted{}
	cls.Ptr = ptr
	return cls
}

var xNewMultipartEncrypted func() uintptr

// Create a new #CamelMultipartEncrypted object.
//
// A MultipartEncrypted should be used to store and create parts of
// type "multipart/encrypted".
func NewMultipartEncrypted() *MultipartEncrypted {
	var cls *MultipartEncrypted

	cret := xNewMultipartEncrypted()

	if cret == 0 {
		return nil
	}
	cls = &MultipartEncrypted{}
	cls.Ptr = cret
	return cls
}

func (c *MultipartEncrypted) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *MultipartEncrypted) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xMultipartEncryptedGLibType, libs, "camel_multipart_encrypted_get_type")

	core.PuregoSafeRegister(&xNewMultipartEncrypted, libs, "camel_multipart_encrypted_new")

}
