// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gio"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type NetworkServiceInterfaceGType struct {
	_ structs.HostLayout

	ParentInterface uintptr

	xGetServiceName uintptr

	xGetDefaultPort uintptr

	xConnectSync uintptr

	xNewConnectable uintptr

	Reserved [20]uintptr
}

func (x *NetworkServiceInterfaceGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// OverrideGetServiceName sets the "get_service_name" callback function.
func (x *NetworkServiceInterfaceGType) OverrideGetServiceName(cb func(NetworkService, NetworkSecurityMethod) string) {
	if cb == nil {
		x.xGetServiceName = 0
	} else {
		x.xGetServiceName = purego.NewCallback(func(ServiceVarp uintptr, MethodVarp NetworkSecurityMethod) string {
			return cb(&NetworkServiceBase{Ptr: ServiceVarp}, MethodVarp)
		})
	}
}

// GetGetServiceName gets the "get_service_name" callback function.
func (x *NetworkServiceInterfaceGType) GetGetServiceName() func(NetworkService, NetworkSecurityMethod) string {
	if x.xGetServiceName == 0 {
		return nil
	}
	var rawCallback func(ServiceVarp uintptr, MethodVarp NetworkSecurityMethod) string
	purego.RegisterFunc(&rawCallback, x.xGetServiceName)
	return func(ServiceVar NetworkService, MethodVar NetworkSecurityMethod) string {
		return rawCallback(ServiceVar.GoPointer(), MethodVar)
	}
}

// OverrideGetDefaultPort sets the "get_default_port" callback function.
func (x *NetworkServiceInterfaceGType) OverrideGetDefaultPort(cb func(NetworkService, NetworkSecurityMethod) uint16) {
	if cb == nil {
		x.xGetDefaultPort = 0
	} else {
		x.xGetDefaultPort = purego.NewCallback(func(ServiceVarp uintptr, MethodVarp NetworkSecurityMethod) uint16 {
			return cb(&NetworkServiceBase{Ptr: ServiceVarp}, MethodVarp)
		})
	}
}

// GetGetDefaultPort gets the "get_default_port" callback function.
func (x *NetworkServiceInterfaceGType) GetGetDefaultPort() func(NetworkService, NetworkSecurityMethod) uint16 {
	if x.xGetDefaultPort == 0 {
		return nil
	}
	var rawCallback func(ServiceVarp uintptr, MethodVarp NetworkSecurityMethod) uint16
	purego.RegisterFunc(&rawCallback, x.xGetDefaultPort)
	return func(ServiceVar NetworkService, MethodVar NetworkSecurityMethod) uint16 {
		return rawCallback(ServiceVar.GoPointer(), MethodVar)
	}
}

// OverrideConnectSync sets the "connect_sync" callback function.
func (x *NetworkServiceInterfaceGType) OverrideConnectSync(cb func(NetworkService, *gio.Cancellable) *gio.IOStream) {
	if cb == nil {
		x.xConnectSync = 0
	} else {
		x.xConnectSync = purego.NewCallback(func(ServiceVarp uintptr, CancellableVarp uintptr) uintptr {
			ret := cb(&NetworkServiceBase{Ptr: ServiceVarp}, gio.CancellableNewFromInternalPtr(CancellableVarp))
			if ret == nil {
				return 0
			}
			return ret.GoPointer()
		})
	}
}

// GetConnectSync gets the "connect_sync" callback function.
func (x *NetworkServiceInterfaceGType) GetConnectSync() func(NetworkService, *gio.Cancellable) *gio.IOStream {
	if x.xConnectSync == 0 {
		return nil
	}
	var rawCallback func(ServiceVarp uintptr, CancellableVarp uintptr) uintptr
	purego.RegisterFunc(&rawCallback, x.xConnectSync)
	return func(ServiceVar NetworkService, CancellableVar *gio.Cancellable) *gio.IOStream {
		rawRet := rawCallback(ServiceVar.GoPointer(), CancellableVar.GoPointer())
		if rawRet == 0 {
			return nil
		}
		ret := &gio.IOStream{}
		ret.Ptr = rawRet
		return ret
	}
}

// OverrideNewConnectable sets the "new_connectable" callback function.
func (x *NetworkServiceInterfaceGType) OverrideNewConnectable(cb func(NetworkService) *gio.SocketConnectableBase) {
	if cb == nil {
		x.xNewConnectable = 0
	} else {
		x.xNewConnectable = purego.NewCallback(func(ServiceVarp uintptr) uintptr {
			ret := cb(&NetworkServiceBase{Ptr: ServiceVarp})
			if ret == nil {
				return 0
			}
			return ret.GoPointer()
		})
	}
}

// GetNewConnectable gets the "new_connectable" callback function.
func (x *NetworkServiceInterfaceGType) GetNewConnectable() func(NetworkService) *gio.SocketConnectableBase {
	if x.xNewConnectable == 0 {
		return nil
	}
	var rawCallback func(ServiceVarp uintptr) uintptr
	purego.RegisterFunc(&rawCallback, x.xNewConnectable)
	return func(ServiceVar NetworkService) *gio.SocketConnectableBase {
		rawRet := rawCallback(ServiceVar.GoPointer())
		if rawRet == 0 {
			return nil
		}
		ret := &gio.SocketConnectableBase{}
		ret.Ptr = rawRet
		return ret
	}
}

type NetworkService interface {
	GoPointer() uintptr
	SetGoPointer(uintptr)
	CanReach(CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr)
	CanReachFinish(ResultVar gio.AsyncResult) (bool, error)
	CanReachSync(CancellableVar *gio.Cancellable) (bool, error)
	ConnectSync(CancellableVar *gio.Cancellable) (*gio.IOStream, error)
	GetDefaultPort(MethodVar NetworkSecurityMethod) uint16
	GetHostReachable() bool
	GetServiceName(MethodVar NetworkSecurityMethod) string
	RefConnectable() *gio.SocketConnectableBase
	SetConnectable(ConnectableVar gio.SocketConnectable)
	Starttls(BaseStreamVar *gio.IOStream) (*gio.IOStream, error)
}

var xNetworkServiceGLibType func() types.GType

func NetworkServiceGLibType() types.GType {
	return xNetworkServiceGLibType()
}

type NetworkServiceBase struct {
	Ptr uintptr
}

func (x *NetworkServiceBase) GoPointer() uintptr {
	if x == nil {
		return 0
	}
	return x.Ptr
}

func (x *NetworkServiceBase) SetGoPointer(ptr uintptr) {
	x.Ptr = ptr
}

// Asynchronously attempts to determine whether or not the host described by
// @service's #CamelNetworkService:connectable property can be reached, without
// actually trying to connect to it.
//
// For more details, see camel_network_service_can_reach_sync().
//
// When the operation is finished, @callback will be called.  You can then
// call camel_network_service_can_reach_finish() to get the result of the
// operation.
func (x *NetworkServiceBase) CanReach(CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	XCamelNetworkServiceCanReach(x.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)

}

// Finishes the operation started with camel_network_service_can_reach().
func (x *NetworkServiceBase) CanReachFinish(ResultVar gio.AsyncResult) (bool, error) {
	var cerr *glib.Error

	cret := XCamelNetworkServiceCanReachFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

// Attempts to determine whether or not the host described by @service's
// #CamelNetworkService:connectable property can be reached, without actually
// trying to connect to it.
//
// If @service believes an attempt to connect will succeed, the function
// returns %TRUE.  Otherwise the function returns %FALSE and sets @error
// to an appropriate error (such as %G_IO_ERROR_HOST_UNREACHABLE).
//
// The function will also update the @service's
// #CamelNetworkService:host-reachable property based on the result.
func (x *NetworkServiceBase) CanReachSync(CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := XCamelNetworkServiceCanReachSync(x.GoPointer(), CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

// Attempts to establish a network connection to the server described by
// @service, using the preferred #CamelNetworkSettings:security-method to
// secure the connection.  If a connection cannot be established, or the
// connection attempt is cancelled, the function sets @error and returns
// %NULL.
func (x *NetworkServiceBase) ConnectSync(CancellableVar *gio.Cancellable) (*gio.IOStream, error) {
	var cls *gio.IOStream
	var cerr *glib.Error

	cret := XCamelNetworkServiceConnectSync(x.GoPointer(), CancellableVar.GoPointer(), &cerr)

	if cret == 0 {
		return nil, cerr
	}
	cls = &gio.IOStream{}
	cls.Ptr = cret
	if cerr == nil {
		return cls, nil
	}
	return cls, cerr

}

// Returns the default network port number for @service and the security
// method @method, as defined in /etc/services.  For example, the default
// port for unencrypted IMAP or encrypted IMAP using STARTTLS is 143, but
// the default port for IMAP over SSL is 993.
func (x *NetworkServiceBase) GetDefaultPort(MethodVar NetworkSecurityMethod) uint16 {

	cret := XCamelNetworkServiceGetDefaultPort(x.GoPointer(), MethodVar)
	return cret
}

// Returns %TRUE if @service believes that the host pointed to by
// #CamelNetworkService:connectable can be reached.  This property
// is updated automatically as network conditions change.
func (x *NetworkServiceBase) GetHostReachable() bool {

	cret := XCamelNetworkServiceGetHostReachable(x.GoPointer())
	return cret
}

// Returns the standard network service name for @service and the security
// method @method, as defined in /etc/services.  For example, the service
// name for unencrypted IMAP or encrypted IMAP using STARTTLS is "imap",
// but the service name for IMAP over SSL is "imaps".
func (x *NetworkServiceBase) GetServiceName(MethodVar NetworkSecurityMethod) string {

	cret := XCamelNetworkServiceGetServiceName(x.GoPointer(), MethodVar)
	return cret
}

// Returns the socket endpoint for the network service to which @service
// is a client.
//
// The returned #GSocketConnectable is referenced for thread-safety and
// must be unreferenced with g_object_unref() when finished with it.
func (x *NetworkServiceBase) RefConnectable() *gio.SocketConnectableBase {
	var cls *gio.SocketConnectableBase

	cret := XCamelNetworkServiceRefConnectable(x.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &gio.SocketConnectableBase{}
	cls.Ptr = cret
	return cls
}

// Sets the socket endpoint for the network service to which @service is
// a client.  If @connectable is %NULL, a #GSocketConnectable is derived
// from the @service's #CamelNetworkSettings.
func (x *NetworkServiceBase) SetConnectable(ConnectableVar gio.SocketConnectable) {

	XCamelNetworkServiceSetConnectable(x.GoPointer(), ConnectableVar.GoPointer())

}

// Creates a #GTlsClientConnection wrapping @base_stream, which is
// assumed to communicate with the server identified by @service's
// #CamelNetworkService:connectable.
//
// This should typically be called after issuing a STARTTLS command
// to a server to initiate a Transport Layer Security handshake.
func (x *NetworkServiceBase) Starttls(BaseStreamVar *gio.IOStream) (*gio.IOStream, error) {
	var cls *gio.IOStream
	var cerr *glib.Error

	cret := XCamelNetworkServiceStarttls(x.GoPointer(), BaseStreamVar.GoPointer(), &cerr)

	if cret == 0 {
		return nil, cerr
	}
	cls = &gio.IOStream{}
	cls.Ptr = cret
	if cerr == nil {
		return cls, nil
	}
	return cls, cerr

}

// GetPropertyHostReachable gets the "host-reachable" property.
// Whether the host is reachable
func (x *NetworkServiceBase) GetPropertyHostReachable() bool {
	obj := gobject.Object{}
	obj.Ptr = x.GoPointer()
	var v gobject.Value
	obj.GetProperty("host-reachable", &v)
	return v.GetBoolean()
}

var XCamelNetworkServiceCanReach func(uintptr, uintptr, uintptr, uintptr)
var XCamelNetworkServiceCanReachFinish func(uintptr, uintptr, **glib.Error) bool
var XCamelNetworkServiceCanReachSync func(uintptr, uintptr, **glib.Error) bool
var XCamelNetworkServiceConnectSync func(uintptr, uintptr, **glib.Error) uintptr
var XCamelNetworkServiceGetDefaultPort func(uintptr, NetworkSecurityMethod) uint16
var XCamelNetworkServiceGetHostReachable func(uintptr) bool
var XCamelNetworkServiceGetServiceName func(uintptr, NetworkSecurityMethod) string
var XCamelNetworkServiceRefConnectable func(uintptr) uintptr
var XCamelNetworkServiceSetConnectable func(uintptr, uintptr)
var XCamelNetworkServiceStarttls func(uintptr, uintptr, **glib.Error) uintptr

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xNetworkServiceGLibType, libs, "camel_network_service_get_type")

	core.PuregoSafeRegister(&XCamelNetworkServiceCanReach, libs, "camel_network_service_can_reach")
	core.PuregoSafeRegister(&XCamelNetworkServiceCanReachFinish, libs, "camel_network_service_can_reach_finish")
	core.PuregoSafeRegister(&XCamelNetworkServiceCanReachSync, libs, "camel_network_service_can_reach_sync")
	core.PuregoSafeRegister(&XCamelNetworkServiceConnectSync, libs, "camel_network_service_connect_sync")
	core.PuregoSafeRegister(&XCamelNetworkServiceGetDefaultPort, libs, "camel_network_service_get_default_port")
	core.PuregoSafeRegister(&XCamelNetworkServiceGetHostReachable, libs, "camel_network_service_get_host_reachable")
	core.PuregoSafeRegister(&XCamelNetworkServiceGetServiceName, libs, "camel_network_service_get_service_name")
	core.PuregoSafeRegister(&XCamelNetworkServiceRefConnectable, libs, "camel_network_service_ref_connectable")
	core.PuregoSafeRegister(&XCamelNetworkServiceSetConnectable, libs, "camel_network_service_set_connectable")
	core.PuregoSafeRegister(&XCamelNetworkServiceStarttls, libs, "camel_network_service_starttls")

}
