// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type MimeFilterBestencClassGType struct {
	_ structs.HostLayout

	ParentClass MimeFilterClassGType

	Reserved [20]uintptr
}

func (x *MimeFilterBestencClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type MimeFilterBestencPrivate struct {
	_ structs.HostLayout
}

func (x *MimeFilterBestencPrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type BestencEncoding int

const (
	Bestenc7bitValue BestencEncoding = 0

	Bestenc8bitValue BestencEncoding = 1

	BestencBinaryValue BestencEncoding = 2

	BestencTextValue BestencEncoding = 256
)

type BestencRequired int

const (
	BestencGetEncodingValue BestencRequired = 1

	BestencGetCharsetValue BestencRequired = 2

	BestencLfIsCrlfValue BestencRequired = 256

	BestencNoFromValue BestencRequired = 512
)

type MimeFilterBestenc struct {
	MimeFilter
}

var xMimeFilterBestencGLibType func() types.GType

func MimeFilterBestencGLibType() types.GType {
	return xMimeFilterBestencGLibType()
}

func MimeFilterBestencNewFromInternalPtr(ptr uintptr) *MimeFilterBestenc {
	cls := &MimeFilterBestenc{}
	cls.Ptr = ptr
	return cls
}

var xNewMimeFilterBestenc func(uint) uintptr

// Create a new #CamelMimeFilterBestenc object.
func NewMimeFilterBestenc(FlagsVar uint) *MimeFilterBestenc {
	var cls *MimeFilterBestenc

	cret := xNewMimeFilterBestenc(FlagsVar)

	if cret == 0 {
		return nil
	}
	cls = &MimeFilterBestenc{}
	cls.Ptr = cret
	return cls
}

var xMimeFilterBestencGetBestCharset func(uintptr) string

// Gets the best charset that can be used to contain this content.
func (x *MimeFilterBestenc) GetBestCharset() string {

	cret := xMimeFilterBestencGetBestCharset(x.GoPointer())
	return cret
}

var xMimeFilterBestencGetBestEncoding func(uintptr, BestencEncoding) TransferEncoding

// Get the best encoding, given specific constraints, that can be used to
// encode a stream of bytes.
func (x *MimeFilterBestenc) GetBestEncoding(RequiredVar BestencEncoding) TransferEncoding {

	cret := xMimeFilterBestencGetBestEncoding(x.GoPointer(), RequiredVar)
	return cret
}

var xMimeFilterBestencSetFlags func(uintptr, uint)

// Set the flags for subsequent operations.
func (x *MimeFilterBestenc) SetFlags(FlagsVar uint) {

	xMimeFilterBestencSetFlags(x.GoPointer(), FlagsVar)

}

func (c *MimeFilterBestenc) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *MimeFilterBestenc) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xMimeFilterBestencGLibType, libs, "camel_mime_filter_bestenc_get_type")

	core.PuregoSafeRegister(&xNewMimeFilterBestenc, libs, "camel_mime_filter_bestenc_new")

	core.PuregoSafeRegister(&xMimeFilterBestencGetBestCharset, libs, "camel_mime_filter_bestenc_get_best_charset")
	core.PuregoSafeRegister(&xMimeFilterBestencGetBestEncoding, libs, "camel_mime_filter_bestenc_get_best_encoding")
	core.PuregoSafeRegister(&xMimeFilterBestencSetFlags, libs, "camel_mime_filter_bestenc_set_flags")

}
