// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

// A collation callback function.
type DBCollate func(uintptr, int, uintptr, int, uintptr) int

// A callback called for the SELECT statements. The items at the same index of @colvalues
// and @colnames correspond to each other.
type DBSelectCB func(uintptr, int, []string, []string) bool

type DBClassGType struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClassGType

	Reserved [20]uintptr
}

func (x *DBClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type DBPrivate struct {
	_ structs.HostLayout
}

func (x *DBPrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type DBError int

const (

	// database is corrupt
	DbErrorCorruptValue DBError = 0
)

type DB struct {
	gobject.Object
}

var xDBGLibType func() types.GType

func DBGLibType() types.GType {
	return xDBGLibType()
}

func DBNewFromInternalPtr(ptr uintptr) *DB {
	cls := &DB{}
	cls.Ptr = ptr
	return cls
}

var xNewDB func(string, **glib.Error) uintptr

// Creates a new #CamelDB instance and calls camel_db_open() to
// open a database file. Free the returned object with
// g_object_unref(), when no longer needed.
func NewDB(FilenameVar string) (*DB, error) {
	var cls *DB
	var cerr *glib.Error

	cret := xNewDB(FilenameVar, &cerr)

	if cret == 0 {
		return nil, cerr
	}
	cls = &DB{}
	cls.Ptr = cret
	if cerr == nil {
		return cls, nil
	}
	return cls, cerr

}

var xDBAbortTransaction func(uintptr) bool

// Ends an ongoing transaction by ignoring the changes.
func (x *DB) AbortTransaction() (bool, error) {
	var cerr *glib.Error

	cret := xDBAbortTransaction(x.GoPointer())
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xDBBeginTransaction func(uintptr) bool

// Begins transaction. End it with camel_db_end_transaction() or camel_db_abort_transaction().
func (x *DB) BeginTransaction() (bool, error) {
	var cerr *glib.Error

	cret := xDBBeginTransaction(x.GoPointer())
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xDBEndTransaction func(uintptr) bool

// Ends an ongoing transaction by committing the changes.
func (x *DB) EndTransaction() (bool, error) {
	var cerr *glib.Error

	cret := xDBEndTransaction(x.GoPointer())
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xDBExecSelect func(uintptr, string, uintptr, uintptr, **glib.Error) bool

// Executes a SELECT statement and calls the @callback for each selected row.
func (x *DB) ExecSelect(StmtVar string, CallbackVar *DBSelectCB, UserDataVar uintptr) (bool, error) {
	var cerr *glib.Error

	cret := xDBExecSelect(x.GoPointer(), StmtVar, glib.NewCallback(CallbackVar), UserDataVar, &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xDBExecStatement func(uintptr, string, **glib.Error) bool

// Executes an SQLite statement.
func (x *DB) ExecStatement(StmtVar string) (bool, error) {
	var cerr *glib.Error

	cret := xDBExecStatement(x.GoPointer(), StmtVar, &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xDBGetFilename func(uintptr) string

func (x *DB) GetFilename() string {

	cret := xDBGetFilename(x.GoPointer())
	return cret
}

var xDBHasTable func(uintptr, string) bool

// Checks whether the @table_name exists in the @cdb.
func (x *DB) HasTable(TableNameVar string) bool {

	cret := xDBHasTable(x.GoPointer(), TableNameVar)
	return cret
}

var xDBHasTableWithColumn func(uintptr, string, string) bool

// Checks whether the @table_name exists in the @cdb and contains
// column named @column_name.
func (x *DB) HasTableWithColumn(TableNameVar string, ColumnNameVar string) bool {

	cret := xDBHasTableWithColumn(x.GoPointer(), TableNameVar, ColumnNameVar)
	return cret
}

var xDBMaybeRunMaintenance func(uintptr) bool

// Runs a @cdb maintenance, which includes vacuum, if necessary.
func (x *DB) MaybeRunMaintenance() (bool, error) {
	var cerr *glib.Error

	cret := xDBMaybeRunMaintenance(x.GoPointer())
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xDBOpen func(uintptr, string, **glib.Error) bool

// Opens the database stored as @filename. The function can be called
// only once, all following calls will result into failures.
func (x *DB) Open(FilenameVar string) (bool, error) {
	var cerr *glib.Error

	cret := xDBOpen(x.GoPointer(), FilenameVar, &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xDBReaderLock func(uintptr)

// Acquires a reader lock on the @cdb. It can be called multiple times.
// Call pair function camel_db_reader_unlock() to release it. it's okay
// to call this function when a writer lock is already acquired by the
// calling thread.
func (x *DB) ReaderLock() {

	xDBReaderLock(x.GoPointer())

}

var xDBReaderUnlock func(uintptr)

// Releases a reader lock on the @cdb previously acquired by
// calling camel_db_reader_lock().
func (x *DB) ReaderUnlock() {

	xDBReaderUnlock(x.GoPointer())

}

var xDBSetCollate func(uintptr, string, string, uintptr) bool

// Defines a collation @collate, which can be used in SQL (SQLite)
// statement as a collation function. The @func is called when
// colation is used.
func (x *DB) SetCollate(ColVar string, CollateVar string, FuncVar *DBCollate) bool {

	cret := xDBSetCollate(x.GoPointer(), ColVar, CollateVar, glib.NewCallback(FuncVar))
	return cret
}

var xDBWriterLock func(uintptr)

// Acquires a writer lock on the @cdb. It can be called multiple times.
// Call pair function camel_db_writer_unlock() to release it.
//
// Note: This adds a transaction on the DB. Not all statements can be executed
//
//	in the transaction.
func (x *DB) WriterLock() {

	xDBWriterLock(x.GoPointer())

}

var xDBWriterUnlock func(uintptr)

// Releases a write lock on the @cdb previously acquired
// by calling camel_db_writer_lock().
func (x *DB) WriterUnlock() {

	xDBWriterUnlock(x.GoPointer())

}

func (c *DB) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *DB) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

var xDBErrorQuark func() glib.Quark

func DBErrorQuark() glib.Quark {

	cret := xDBErrorQuark()
	return cret
}

var xDBFreeSqlizedString func(string)

// Frees a string previously returned by camel_db_sqlize_string().
func DBFreeSqlizedString(StringVar string) {

	xDBFreeSqlizedString(StringVar)

}

var xDBReleaseCacheMemory func()

// Instructs sqlite to release its memory, if possible. This can be avoided
// when CAMEL_SQLITE_FREE_CACHE environment variable is set.
func DBReleaseCacheMemory() {

	xDBReleaseCacheMemory()

}

var xDBSqlizeString func(string) string

// Converts the @string to be usable in the SQLite statements.
func DBSqlizeString(StringVar string) string {

	cret := xDBSqlizeString(StringVar)
	return cret
}

var xDBSqlizeToStatement func(*glib.String, string, DBSqlizeFlags)

// Encodes the @str to be safe to use as a string
// in an SQL statement and appends it to the @stmt.
// When @str is %NULL, a NULL word is appended.
func DBSqlizeToStatement(StmtVar *glib.String, StrVar string, FlagsVar DBSqlizeFlags) {

	xDBSqlizeToStatement(StmtVar, StrVar, FlagsVar)

}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xDBGLibType, libs, "camel_db_get_type")

	core.PuregoSafeRegister(&xNewDB, libs, "camel_db_new")

	core.PuregoSafeRegister(&xDBAbortTransaction, libs, "camel_db_abort_transaction")
	core.PuregoSafeRegister(&xDBBeginTransaction, libs, "camel_db_begin_transaction")
	core.PuregoSafeRegister(&xDBEndTransaction, libs, "camel_db_end_transaction")
	core.PuregoSafeRegister(&xDBExecSelect, libs, "camel_db_exec_select")
	core.PuregoSafeRegister(&xDBExecStatement, libs, "camel_db_exec_statement")
	core.PuregoSafeRegister(&xDBGetFilename, libs, "camel_db_get_filename")
	core.PuregoSafeRegister(&xDBHasTable, libs, "camel_db_has_table")
	core.PuregoSafeRegister(&xDBHasTableWithColumn, libs, "camel_db_has_table_with_column")
	core.PuregoSafeRegister(&xDBMaybeRunMaintenance, libs, "camel_db_maybe_run_maintenance")
	core.PuregoSafeRegister(&xDBOpen, libs, "camel_db_open")
	core.PuregoSafeRegister(&xDBReaderLock, libs, "camel_db_reader_lock")
	core.PuregoSafeRegister(&xDBReaderUnlock, libs, "camel_db_reader_unlock")
	core.PuregoSafeRegister(&xDBSetCollate, libs, "camel_db_set_collate")
	core.PuregoSafeRegister(&xDBWriterLock, libs, "camel_db_writer_lock")
	core.PuregoSafeRegister(&xDBWriterUnlock, libs, "camel_db_writer_unlock")

	core.PuregoSafeRegister(&xDBErrorQuark, libs, "camel_db_error_quark")
	core.PuregoSafeRegister(&xDBFreeSqlizedString, libs, "camel_db_free_sqlized_string")
	core.PuregoSafeRegister(&xDBReleaseCacheMemory, libs, "camel_db_release_cache_memory")
	core.PuregoSafeRegister(&xDBSqlizeString, libs, "camel_db_sqlize_string")
	core.PuregoSafeRegister(&xDBSqlizeToStatement, libs, "camel_db_sqlize_to_statement")

}
