// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gio"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type FilterGetFolderFunc func(uintptr, string, uintptr, **glib.Error) uintptr

type FilterPlaySoundFunc func(uintptr, string, uintptr)

type FilterShellFunc func(uintptr, int, string, uintptr)

type FilterStatusFunc func(uintptr, uintptr, int, string, uintptr)

type FilterSystemBeepFunc func(uintptr, uintptr)

type FilterDriverClassGType struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClassGType

	Reserved [20]uintptr
}

func (x *FilterDriverClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type FilterDriverPrivate struct {
	_ structs.HostLayout
}

func (x *FilterDriverPrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type FilterDriver struct {
	gobject.Object
}

var xFilterDriverGLibType func() types.GType

func FilterDriverGLibType() types.GType {
	return xFilterDriverGLibType()
}

func FilterDriverNewFromInternalPtr(ptr uintptr) *FilterDriver {
	cls := &FilterDriver{}
	cls.Ptr = ptr
	return cls
}

var xNewFilterDriver func(uintptr) uintptr

func NewFilterDriver(SessionVar *Session) *FilterDriver {
	var cls *FilterDriver

	cret := xNewFilterDriver(SessionVar.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &FilterDriver{}
	cls.Ptr = cret
	return cls
}

var xFilterDriverAddRule func(uintptr, string, string, string)

// Adds a new rule to set of rules to process by the filter driver.
func (x *FilterDriver) AddRule(NameVar string, MatchVar string, ActionVar string) {

	xFilterDriverAddRule(x.GoPointer(), NameVar, MatchVar, ActionVar)

}

var xFilterDriverFilterFolder func(uintptr, uintptr, *UIDCache, uintptr, bool, uintptr, **glib.Error) int

// Filters a folder based on rules defined in the FilterDriver
// object.
func (x *FilterDriver) FilterFolder(FolderVar *Folder, CacheVar *UIDCache, UidsVar uintptr, RemoveVar bool, CancellableVar *gio.Cancellable) (int, error) {
	var cerr *glib.Error

	cret := xFilterDriverFilterFolder(x.GoPointer(), FolderVar.GoPointer(), CacheVar, UidsVar, RemoveVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xFilterDriverFilterMbox func(uintptr, string, string, uintptr, **glib.Error) int

// Filters an mbox file based on rules defined in the FilterDriver
// object. Is more efficient as it doesn't need to open the folder
// through Camel directly.
func (x *FilterDriver) FilterMbox(MboxVar string, OriginalSourceUrlVar string, CancellableVar *gio.Cancellable) (int, error) {
	var cerr *glib.Error

	cret := xFilterDriverFilterMbox(x.GoPointer(), MboxVar, OriginalSourceUrlVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xFilterDriverFilterMessage func(uintptr, uintptr, uintptr, string, uintptr, string, string, uintptr, **glib.Error) int

// Filters a message based on rules defined in the FilterDriver
// object. If the source folder (@source) and the uid (@uid) are
// provided, the filter will operate on the CamelFolder (which in
// certain cases is more efficient than using the default
// camel_folder_append_message() function).
func (x *FilterDriver) FilterMessage(MessageVar *MimeMessage, InfoVar *MessageInfo, UidVar string, SourceVar *Folder, StoreUidVar string, OriginalStoreUidVar string, CancellableVar *gio.Cancellable) (int, error) {
	var cerr *glib.Error

	cret := xFilterDriverFilterMessage(x.GoPointer(), MessageVar.GoPointer(), InfoVar.GoPointer(), UidVar, SourceVar.GoPointer(), StoreUidVar, OriginalStoreUidVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xFilterDriverFlush func(uintptr)

// Flush all of the only-once filter actions.
func (x *FilterDriver) Flush() error {
	var cerr *glib.Error

	xFilterDriverFlush(x.GoPointer())
	if cerr == nil {
		return nil
	}
	return cerr

}

var xFilterDriverLogInfo func(uintptr, string, ...interface{})

// Logs an informational message to a filter log. The function does
// nothing when @driver is %NULL or when there is no log file being
// set in @driver.
func (x *FilterDriver) LogInfo(FormatVar string, varArgs ...interface{}) {

	xFilterDriverLogInfo(x.GoPointer(), FormatVar, varArgs...)

}

var xFilterDriverRemoveRuleByName func(uintptr, string) bool

// Removes a rule by name, added by camel_filter_driver_add_rule().
func (x *FilterDriver) RemoveRuleByName(NameVar string) bool {

	cret := xFilterDriverRemoveRuleByName(x.GoPointer(), NameVar)
	return cret
}

var xFilterDriverSetDefaultFolder func(uintptr, uintptr)

// Sets a default folder for the driver. The function adds
// its own reference for the folder.
func (x *FilterDriver) SetDefaultFolder(DefVar *Folder) {

	xFilterDriverSetDefaultFolder(x.GoPointer(), DefVar.GoPointer())

}

var xFilterDriverSetFolderFunc func(uintptr, uintptr, uintptr)

// Sets a callback (of type #CamelFilterGetFolderFunc) to get a folder.
func (x *FilterDriver) SetFolderFunc(GetFolderVar *FilterGetFolderFunc, UserDataVar uintptr) {

	xFilterDriverSetFolderFunc(x.GoPointer(), glib.NewCallback(GetFolderVar), UserDataVar)

}

var xFilterDriverSetLogfile func(uintptr, uintptr)

// Sets a log file to use for logging.
func (x *FilterDriver) SetLogfile(LogfileVar uintptr) {

	xFilterDriverSetLogfile(x.GoPointer(), LogfileVar)

}

var xFilterDriverSetPlaySoundFunc func(uintptr, uintptr, uintptr)

// Sets a callback to call when a play of a sound is requested.
func (x *FilterDriver) SetPlaySoundFunc(FuncVar *FilterPlaySoundFunc, UserDataVar uintptr) {

	xFilterDriverSetPlaySoundFunc(x.GoPointer(), glib.NewCallback(FuncVar), UserDataVar)

}

var xFilterDriverSetShellFunc func(uintptr, uintptr, uintptr)

// Sets a shell command callback, which is called when a shell command
// execution is requested.
func (x *FilterDriver) SetShellFunc(FuncVar *FilterShellFunc, UserDataVar uintptr) {

	xFilterDriverSetShellFunc(x.GoPointer(), glib.NewCallback(FuncVar), UserDataVar)

}

var xFilterDriverSetStatusFunc func(uintptr, uintptr, uintptr)

// Sets a status callback, which is used to report progress/status.
func (x *FilterDriver) SetStatusFunc(FuncVar *FilterStatusFunc, UserDataVar uintptr) {

	xFilterDriverSetStatusFunc(x.GoPointer(), glib.NewCallback(FuncVar), UserDataVar)

}

var xFilterDriverSetSystemBeepFunc func(uintptr, uintptr, uintptr)

// Sets a callback to use for system beep.
func (x *FilterDriver) SetSystemBeepFunc(FuncVar *FilterSystemBeepFunc, UserDataVar uintptr) {

	xFilterDriverSetSystemBeepFunc(x.GoPointer(), glib.NewCallback(FuncVar), UserDataVar)

}

func (c *FilterDriver) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *FilterDriver) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xFilterDriverGLibType, libs, "camel_filter_driver_get_type")

	core.PuregoSafeRegister(&xNewFilterDriver, libs, "camel_filter_driver_new")

	core.PuregoSafeRegister(&xFilterDriverAddRule, libs, "camel_filter_driver_add_rule")
	core.PuregoSafeRegister(&xFilterDriverFilterFolder, libs, "camel_filter_driver_filter_folder")
	core.PuregoSafeRegister(&xFilterDriverFilterMbox, libs, "camel_filter_driver_filter_mbox")
	core.PuregoSafeRegister(&xFilterDriverFilterMessage, libs, "camel_filter_driver_filter_message")
	core.PuregoSafeRegister(&xFilterDriverFlush, libs, "camel_filter_driver_flush")
	core.PuregoSafeRegister(&xFilterDriverLogInfo, libs, "camel_filter_driver_log_info")
	core.PuregoSafeRegister(&xFilterDriverRemoveRuleByName, libs, "camel_filter_driver_remove_rule_by_name")
	core.PuregoSafeRegister(&xFilterDriverSetDefaultFolder, libs, "camel_filter_driver_set_default_folder")
	core.PuregoSafeRegister(&xFilterDriverSetFolderFunc, libs, "camel_filter_driver_set_folder_func")
	core.PuregoSafeRegister(&xFilterDriverSetLogfile, libs, "camel_filter_driver_set_logfile")
	core.PuregoSafeRegister(&xFilterDriverSetPlaySoundFunc, libs, "camel_filter_driver_set_play_sound_func")
	core.PuregoSafeRegister(&xFilterDriverSetShellFunc, libs, "camel_filter_driver_set_shell_func")
	core.PuregoSafeRegister(&xFilterDriverSetStatusFunc, libs, "camel_filter_driver_set_status_func")
	core.PuregoSafeRegister(&xFilterDriverSetSystemBeepFunc, libs, "camel_filter_driver_set_system_beep_func")

}
