// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type SaslXOAuth2OutlookClassGType struct {
	_ structs.HostLayout

	ParentClass SaslXOAuth2ClassGType
}

func (x *SaslXOAuth2OutlookClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type SaslXOAuth2OutlookPrivate struct {
	_ structs.HostLayout
}

func (x *SaslXOAuth2OutlookPrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type SaslXOAuth2Outlook struct {
	SaslXOAuth2
}

var xSaslXOAuth2OutlookGLibType func() types.GType

func SaslXOAuth2OutlookGLibType() types.GType {
	return xSaslXOAuth2OutlookGLibType()
}

func SaslXOAuth2OutlookNewFromInternalPtr(ptr uintptr) *SaslXOAuth2Outlook {
	cls := &SaslXOAuth2Outlook{}
	cls.Ptr = ptr
	return cls
}

func (c *SaslXOAuth2Outlook) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *SaslXOAuth2Outlook) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}
