// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gio"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type StreamNullClassGType struct {
	_ structs.HostLayout

	ParentClass StreamClassGType

	Reserved [20]uintptr
}

func (x *StreamNullClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type StreamNullPrivate struct {
	_ structs.HostLayout
}

func (x *StreamNullPrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type StreamNull struct {
	Stream
}

var xStreamNullGLibType func() types.GType

func StreamNullGLibType() types.GType {
	return xStreamNullGLibType()
}

func StreamNullNewFromInternalPtr(ptr uintptr) *StreamNull {
	cls := &StreamNull{}
	cls.Ptr = ptr
	return cls
}

var xNewStreamNull func() uintptr

// Returns a null stream.  A null stream is always at eof, and
// always returns success for all reads and writes.
func NewStreamNull() *StreamNull {
	var cls *StreamNull

	cret := xNewStreamNull()

	if cret == 0 {
		return nil
	}
	cls = &StreamNull{}
	cls.Ptr = cret
	return cls
}

var xStreamNullGetBytesWritten func(uintptr) uint

func (x *StreamNull) GetBytesWritten() uint {

	cret := xStreamNullGetBytesWritten(x.GoPointer())
	return cret
}

var xStreamNullGetEndsWithCrlf func(uintptr) bool

func (x *StreamNull) GetEndsWithCrlf() bool {

	cret := xStreamNullGetEndsWithCrlf(x.GoPointer())
	return cret
}

func (c *StreamNull) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *StreamNull) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// Tests if the stream supports the #GSeekableIface.
func (x *StreamNull) CanSeek() bool {

	cret := gio.XGSeekableCanSeek(x.GoPointer())
	return cret
}

// Tests if the length of the stream can be adjusted with
// g_seekable_truncate().
func (x *StreamNull) CanTruncate() bool {

	cret := gio.XGSeekableCanTruncate(x.GoPointer())
	return cret
}

// Seeks in the stream by the given @offset, modified by @type.
//
// Attempting to seek past the end of the stream will have different
// results depending on if the stream is fixed-sized or resizable.  If
// the stream is resizable then seeking past the end and then writing
// will result in zeros filling the empty space.  Seeking past the end
// of a resizable stream and reading will result in EOF.  Seeking past
// the end of a fixed-sized stream will fail.
//
// Any operation that would result in a negative offset will fail.
//
// If @cancellable is not %NULL, then the operation can be cancelled by
// triggering the cancellable object from another thread. If the operation
// was cancelled, the error %G_IO_ERROR_CANCELLED will be returned.
func (x *StreamNull) Seek(OffsetVar int64, TypeVar glib.SeekType, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := gio.XGSeekableSeek(x.GoPointer(), OffsetVar, TypeVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

// Tells the current position within the stream.
func (x *StreamNull) Tell() int64 {

	cret := gio.XGSeekableTell(x.GoPointer())
	return cret
}

// Sets the length of the stream to @offset. If the stream was previously
// larger than @offset, the extra data is discarded. If the stream was
// previously shorter than @offset, it is extended with NUL ('\0') bytes.
//
// If @cancellable is not %NULL, then the operation can be cancelled by
// triggering the cancellable object from another thread. If the operation
// was cancelled, the error %G_IO_ERROR_CANCELLED will be returned. If an
// operation was partially finished when the operation was cancelled the
// partial result will be returned, without an error.
func (x *StreamNull) Truncate(OffsetVar int64, CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := gio.XGSeekableTruncate(x.GoPointer(), OffsetVar, CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xStreamNullGLibType, libs, "camel_stream_null_get_type")

	core.PuregoSafeRegister(&xNewStreamNull, libs, "camel_stream_null_new")

	core.PuregoSafeRegister(&xStreamNullGetBytesWritten, libs, "camel_stream_null_get_bytes_written")
	core.PuregoSafeRegister(&xStreamNullGetEndsWithCrlf, libs, "camel_stream_null_get_ends_with_crlf")

}
