// Package camel was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package camel

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type SMIMEContextClassGType struct {
	_ structs.HostLayout

	ParentClass CipherContextClassGType

	Reserved [20]uintptr
}

func (x *SMIMEContextClassGType) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type SMIMEContextPrivate struct {
	_ structs.HostLayout
}

func (x *SMIMEContextPrivate) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type SMIMEDescribe int

const (
	SmimeSignedValue SMIMEDescribe = 1

	SmimeEncryptedValue SMIMEDescribe = 2

	SmimeCertsValue SMIMEDescribe = 4

	SmimeCrlsValue SMIMEDescribe = 8
)

type SMIMESign int

const (
	SmimeSignClearsignValue SMIMESign = 0

	SmimeSignEnvelopedValue SMIMESign = 1
)

type SMIMEContext struct {
	CipherContext
}

var xSMIMEContextGLibType func() types.GType

func SMIMEContextGLibType() types.GType {
	return xSMIMEContextGLibType()
}

func SMIMEContextNewFromInternalPtr(ptr uintptr) *SMIMEContext {
	cls := &SMIMEContext{}
	cls.Ptr = ptr
	return cls
}

var xNewSMIMEContext func(uintptr) uintptr

// Creates a new sm cipher context object.
func NewSMIMEContext(SessionVar *Session) *SMIMEContext {
	var cls *SMIMEContext

	cret := xNewSMIMEContext(SessionVar.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &SMIMEContext{}
	cls.Ptr = cret
	return cls
}

var xSMIMEContextDescribePart func(uintptr, uintptr) uint32

func (x *SMIMEContext) DescribePart(PartVar uintptr) uint32 {

	cret := xSMIMEContextDescribePart(x.GoPointer(), PartVar)
	return cret
}

var xSMIMEContextSetEncryptKey func(uintptr, bool, string)

func (x *SMIMEContext) SetEncryptKey(UseVar bool, KeyVar string) {

	xSMIMEContextSetEncryptKey(x.GoPointer(), UseVar, KeyVar)

}

var xSMIMEContextSetSignMode func(uintptr, SMIMESign)

func (x *SMIMEContext) SetSignMode(TypeVar SMIMESign) {

	xSMIMEContextSetSignMode(x.GoPointer(), TypeVar)

}

func (c *SMIMEContext) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *SMIMEContext) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

var xSMIMEContextUtilNssErrorToString func(int) string

// Utility function to get a localized text description for an error code
// returned by PORT_GetError().
//
// Note: the function returns always NULL when the library was not compiled
//
//	with S/MIME support.
func SMIMEContextUtilNssErrorToString(NssErrorCodeVar int) string {

	cret := xSMIMEContextUtilNssErrorToString(NssErrorCodeVar)
	return cret
}

func init() {
	core.SetPackageName("CAMEL", "camel-1.2")
	core.SetSharedLibraries("CAMEL", []string{"libcamel-1.2.so.66"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("CAMEL") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xSMIMEContextGLibType, libs, "camel_smime_context_get_type")

	core.PuregoSafeRegister(&xNewSMIMEContext, libs, "camel_smime_context_new")

	core.PuregoSafeRegister(&xSMIMEContextDescribePart, libs, "camel_smime_context_describe_part")
	core.PuregoSafeRegister(&xSMIMEContextSetEncryptKey, libs, "camel_smime_context_set_encrypt_key")
	core.PuregoSafeRegister(&xSMIMEContextSetSignMode, libs, "camel_smime_context_set_sign_mode")

	core.PuregoSafeRegister(&xSMIMEContextUtilNssErrorToString, libs, "camel_smime_context_util_nss_error_to_string")

}
