// Package gsk was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gsk

import (
	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
)

var xTransformParse func(string, **Transform) bool

// Parses a given into a transform.
//
// Strings printed via [method@Gsk.Transform.to_string]
// can be read in again successfully using this function.
//
// If @string does not describe a valid transform, false
// is returned and `NULL` is put in @out_transform.
func TransformParse(StringVar string, OutTransformVar **Transform) bool {

	cret := xTransformParse(StringVar, OutTransformVar)
	return cret
}

func init() {
	core.SetPackageName("GSK", "gtk4")
	core.SetSharedLibraries("GSK", []string{"libgtk-4.so.1"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("GSK") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xTransformParse, libs, "gsk_transform_parse")

}
