// Package icalglib was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package icalglib

import (
	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
)

type ErrorEnum int

const (
	ICalNoErrorValue ErrorEnum = 0

	ICalBadargErrorValue ErrorEnum = 1

	ICalNewfailedErrorValue ErrorEnum = 2

	ICalAllocationErrorValue ErrorEnum = 3

	ICalMalformeddataErrorValue ErrorEnum = 4

	ICalParseErrorValue ErrorEnum = 5

	ICalInternalErrorValue ErrorEnum = 6

	ICalFileErrorValue ErrorEnum = 7

	ICalUsageErrorValue ErrorEnum = 8

	ICalUnimplementedErrorValue ErrorEnum = 9

	ICalUnknownErrorValue ErrorEnum = 10
)

type ErrorState int

const (
	ICalErrorFatalValue ErrorState = 0

	ICalErrorNonfatalValue ErrorState = 1

	ICalErrorDefaultValue ErrorState = 2

	ICalErrorUnknownValue ErrorState = 3
)

var xBt func()

func Bt() {

	xBt()

}

var xErrnoReturn func() ErrorEnum

// Returns the error stored in the library. If no error, return I_CAL_NO_ERROR.
func ErrnoReturn() ErrorEnum {

	cret := xErrnoReturn()
	return cret
}

var xErrorClearErrno func()

func ErrorClearErrno() {

	xErrorClearErrno()

}

var xErrorCrashHere func()

// Shout out the errors to the compiler.
func ErrorCrashHere() {

	xErrorCrashHere()

}

var xErrorGetErrorState func(ErrorEnum) ErrorState

// Gets the state of an error.
func ErrorGetErrorState(ErrorVar ErrorEnum) ErrorState {

	cret := xErrorGetErrorState(ErrorVar)
	return cret
}

var xErrorPerror func() string

// Gets the #ICalErrorEnum in the string representation. This method called the icalerrorno_return to get
// the current error.
func ErrorPerror() string {

	cret := xErrorPerror()
	return cret
}

var xErrorRestore func(string, ErrorState)

// Restores the error to specified state.
func ErrorRestore(ErrorVar string, EsVar ErrorState) {

	xErrorRestore(ErrorVar, EsVar)

}

var xErrorSetErrno func(ErrorEnum)

// Sets the errno.
func ErrorSetErrno(XVar ErrorEnum) {

	xErrorSetErrno(XVar)

}

var xErrorSetErrorState func(ErrorEnum, ErrorState)

// Sets the state to the corresponding error in the library.
func ErrorSetErrorState(ErrorVar ErrorEnum, StateVar ErrorState) {

	xErrorSetErrorState(ErrorVar, StateVar)

}

var xErrorStopHere func()

func ErrorStopHere() {

	xErrorStopHere()

}

var xErrorStrerror func(ErrorEnum) string

// Translates the #ICalErrorEnum to the string representation.
func ErrorStrerror(EVar ErrorEnum) string {

	cret := xErrorStrerror(EVar)
	return cret
}

var xErrorSupress func(string) ErrorState

// Suppresses the error.
func ErrorSupress(ErrorVar string) ErrorState {

	cret := xErrorSupress(ErrorVar)
	return cret
}

func init() {
	core.SetPackageName("ICALGLIB", "libical-glib")
	core.SetSharedLibraries("ICALGLIB", []string{"libical-glib.so.3"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("ICALGLIB") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xBt, libs, "i_cal_bt")
	core.PuregoSafeRegister(&xErrnoReturn, libs, "i_cal_errno_return")
	core.PuregoSafeRegister(&xErrorClearErrno, libs, "i_cal_error_clear_errno")
	core.PuregoSafeRegister(&xErrorCrashHere, libs, "i_cal_error_crash_here")
	core.PuregoSafeRegister(&xErrorGetErrorState, libs, "i_cal_error_get_error_state")
	core.PuregoSafeRegister(&xErrorPerror, libs, "i_cal_error_perror")
	core.PuregoSafeRegister(&xErrorRestore, libs, "i_cal_error_restore")
	core.PuregoSafeRegister(&xErrorSetErrno, libs, "i_cal_error_set_errno")
	core.PuregoSafeRegister(&xErrorSetErrorState, libs, "i_cal_error_set_error_state")
	core.PuregoSafeRegister(&xErrorStopHere, libs, "i_cal_error_stop_here")
	core.PuregoSafeRegister(&xErrorStrerror, libs, "i_cal_error_strerror")
	core.PuregoSafeRegister(&xErrorSupress, libs, "i_cal_error_supress")

}
